(fifthQuint)Efficacy Study of Amodiaquine-Artesunate and Artemether-Lumefantrine for the Treatment of Uncomplicated Malaria.

 Study design and site An open randomized study was conducted to test the hypothesis that the risk of recurrent parasitaemia after 42 days is not inferior in the group receiving artesunate and amodiaquine (ASAQ) regimen compared to the group receiving artemether-lumefantrine (AL) regimen.

 The patients were recruited from the outpatient department of the general reference hospital of Pweto, health district of Pweto, province of Katanga, Democratic Republic of Congo (DRC), between April 2008 and March 2009.

 Procedures Children aged between six and 59 months and with a body weight 5kg were eligible for enrolment if they had P.

 falciparum infections (density threshold at inclusion between 2,000 and 200,000/ mu l), fever or history of fever in the previous 24 hours, no signs of severe malaria, no reported hypersensitivities of the studied drugs, and no serious concomitant febrile illness.

 The children included were randomized in one of the two treatment arms, in a 1:1 ratio without any stratification.

 The randomization list was generated by a computer in blocks of six.

 Treatment allocations were kept in sealed and numbered opaque envelopes.

 Participants were enrolled in the same order in which they were diagnosed.

 ASAQ (ASAQ Winthrop(R), Sanofi-Aventis) was administered once daily for three days, as follows: one tablet of artesunate 25mg/amodiaquine 67.

5 mg for children between 5 to 8.

9 kg, artesunate 50mg/amodiaquine 135 mg for children between 9 to 17.

9 kg.

 One tablet of artemether 20 mg/lumefantrine 120 mg; (Coartem(R) Novartis Pharma, Basel, Switzerland) was administered twice daily for three days to children with a body weight of 5 to 14.

9 kg and two tablets were administered twice daily for three days to children with a body weight of 15 to 24.

9 kg.

 All doses of drugs were administered under direct observation for the three days.

 Full doses of drugs were re-administered if a patient vomited within 30 min after receipt.

 Patients who vomited more than twice were excluded from the study.

 Signs of severe malaria or any other serious health condition (i.

e.

 severe malnutrition), intake of anti-malarial treatment in the last seven days, and mixed malaria infection were also exclusion criteria.

 Clinical assessment (including measurement of axillary temperature), tick and thin smears and haemoglobin measurement were performed on days 2, 3, 7, 14, 21, 28, 35 and 42 or any day in between in the event of illness.

 Malaria outcome classification Outcomes were classified according to 2009 WHO guidelines as adequate clinical and parasitological response (ACPR), early treatment failure (ETF), late clinical failure (LCF), late parasitological failure (LPF) or follow-up interrupted.

 Follow-up interrupted included treatment protocol violation, lost to follow-up, use of other anti-malarials (such as quinine) outside the study protocol or withdrawal of consent prohibiting further follow-up.

 Drug tolerability was also assessed clinically.

 An adverse event was defined as any undesirable symptom in a patient during the study regardless of whether it was related to the treatment.

 PCR genotyping In areas of intense transmission, where multiple genotype infections are common , a second episode of malaria or a recurrent parasitaemia during the drug-free follow-up period may be due to the same infection or a different infection (a recrudescence, thus a treatment failure, or a new infection, respectively).

 To distinguish these two events, polymorphic P.

 falciparum genes, such as the merozoite surface protein 1 and 2 genes (msp1 and msp2) and the glutamate-rich protein gene (glurp) were genotyped by PCR, as previously described.

 PCR analyses, conducted at the Epicentre research base, Mbarara, Uganda, were performed using paired samples from all patients experiencing late clinical or parasitologic failure.

 Blood was collected on filter paper (Whatman FTA(R) Cards) on the day of enrollment and the day treatment failure occurred.

 The genotypic profiles for pre- and post-treatment parasites were compared; patients in which pre- and post-treatment genotypes were identical were considered as recrudescences and patients in which pre- and post-treatment genotypes were different were considered as new infections.

 All ETFs were considered to be due to recrudescence.

 Patients meeting the criteria for LCF or LPF in whom genotyping was done; according to the results, patients were classified as either (i) resolved by PCR and further categorized as recrudescences or new infections or (ii) unsuccessfully genotyped with the reason recorded (missing sample, PCR not done or result inconclusive).

 Statistical analysis The primary outcome was the PCR-adjusted parasitological cure rate up to day 42 of the follow-up period.

 Two analytical approaches were used to assess efficacy data.

 First a per protocol (PP) analysis was performed including only the patients who were followed throughout the protocol, defined follow-up period and in whom a clear treatment outcome can be determined.

 The risk of failure for each treatment group was calculated as the proportion of patients classified as failure (the numerator) divided by the number of patients in the evaluable population (the denominator).

 In the second approach, survival analysis was performed and patients with incomplete follow-up who did not reach the primary outcome interest were included in the analysis as non-failures, but censored on the last day of follow-up.

 The risk of failure was calculated using the Kaplan-Meier product limit formula with data censored for patients who were not classified as failures and with interrupted follow-up.

 Patients wrongly included, who did not meet study inclusion criteria, were excluded from both analyses.

 In the PP analysis (adjusting by genotyping), the evaluable population included only patients classified as ACPR, ETF or LCF/LPF due to recrudescence.

 In the survival analysis, the evaluable population for adjusted and unadjusted calculations included all patients enrolled in the study, with the exception that LCF/LPF outcomes with unsuccessful genotyping outcomes were excluded from the adjusted calculations.

 For the unadjusted calculations, patients with follow-up interrupted and non-falciparum new infections were censored on the last day of observation.

 For the adjusted calculations, censored patients also included those with new P.

 falciparum infections.

 Other variables, such as the baseline characteristics of the patients of the two treatment arms, were compared using the chi2 test or Fisher's exact test for variables and Student's test for continuous variables.

 Data were double entered and validated using Epidata version 3.

1 (Odense, Danemark).

 All analyses were performed with Stata, version 10 (Stats-Corp, College Station, Texas).

 A p-value < 0.

05 was considered statistically significant.

.

 Efficacy Study of Amodiaquine-Artesunate and Artemether-Lumefantrine for the Treatment of Uncomplicated Malaria@highlight

In the Democratic Republic of Congo (DRC), malaria is an important cause of morbidity and mortality.

 It is estimated that malaria is responsible for 30% of admissions to hospital averaged throughout the country and for 25-30% mortality in children under five.

 In 2005, DRC adopted artesunate and amodiaquine (ASAQ) as first-line anti-malarial treatment.

 As WHO recommended that the efficacy of antimalarial drugs was monitored regularly to avoid an upsurge of mortality and morbidity due to continued use of ineffective drugs, a randomized, non-inferiority open-label trial was conducted in Katanga, in order to compare the efficacy of the fixed-dose formulation ASAQ versus artemether-lumefantrine (AL), Children aged six and 59 months with uncomplicated Plasmodium falciparum malaria were enrolledand randomly allocated into one of the two regimens.

 The risk of recurrent parasitaemia by day 42, both unadjusted and adjusted by PCR genotyping to distinguish recrudescence from new infection, was analysed.

 Between April 2008 and March 2009, 301 childrenwere included: 156 with ASAQ and 145 with AL.

 No early treatment failures were reported.

 Among the 256 patients followed-up at day 42, 32 patients developed late clinical or parasitological failure (9.

9% (13/131) in the ASAQ group and 15.

2% (19/125) in the AL group).

 After PCR correction, cure rates were 98.

3% (95%CI, 94.

1-99.

8) in the ASAQ group and 99.

1% (95%CI, 94.

9-99.

9) in the AL group (difference -0.

7%, one sided 95%CI -3.

1).

 Kaplan-Meier PCR-adjusted cure rates were similar.

 Both treatment regimens were generally well tolerated.

 Both ASAQ and AL are highly effective and currently adequate as the first-line treatment of uncomplicated falciparum malaria in this area of Katanga, DRC.

 However, in a very large country such as DRC, and because of possible emergence of resistance from other endemic regions, surveillance of efficacy of artemisinin-based combination treatments, including other evaluations of the resistance of ASAQ, need to be done in other provinces.

