(fifthQuint)Trial of Decitabine as a Sensitizer to Carboplatin in Platinum Resistant Recurrent Ovarian Cancer.

 Decitabine at escalating dose levels will be given IV X 5 days followed by Carboplatin given IV on Day 8 at a dose corresponding to an area under curve (AUC) of 5.

 The maximum dose of Decitabine (20 mg/m2) is based on the results of the myelodysplastic syndrome (MDS) clinical trial that demonstrated biological and clinical efficacy at this dose (15-17).

 It is recognized that higher doses of decitabine can be administered, myelotoxicity being the most significant adverse event.

 This protocol will assess the lower less toxic but biologically active dose.

 Decitabine dose will be escalated as follows.

 Dose level -1: 5 mg/m2 IV per day (QD) X 5 days Dose level 1: 10mg/m2 IV QD X 5 days Dose level 2: 20mg/m2 IV QD X 5 days Each cycle will consist of 28 days, with delays to allow blood count recovery.

 Correlative blood draws will occur on Day1 (baseline) and on Day 8 before Carboplatin for cycle 1 and 2.

 The escalation phase will follow the standard 3+3 design.

 That is, patients will be accrued to each dose level in cohorts of up to 3-6 patients.

 Escalation will continue until a DLT is observed, the highest dose-level is reached, or medical judgment indicates.

 The goal of the phase I cohort is to ensure the safety and tolerability of the combination, not to define the maximum tolerated dose.

 An initial 3 patients will be enrolled at dose level 1.

 If all 3 patients in dose level 1 complete 4 weeks of therapy without dose limiting toxicity (DLT), the study will proceed to enroll 3 patients at dose level 2.

 If all 3 patients in dose level 2 complete 4 weeks of therapy without DLT, we will accrue 3 more to ensure that only 0 or 1 of 6 have a DLT and then proceed to the phase II cohort.

 As dose level 2 represents full doses of both agents, there will be no further dose escalation beyond dose level 2.

.

 Trial of Decitabine as a Sensitizer to Carboplatin in Platinum Resistant Recurrent Ovarian Cancer@highlight

Based on these pre-clinical data, which were generated by our group, the investigators propose to test in a phase I/II clinical trial the following hypothesis: demethylation induced by decitabine results in re-sensitization to platinum in recurrent ovarian cancer.

 To test this hypothesis, the investigators will treat patients with recurrent ovarian cancer platinum resistant (recurrence within 6 months from platinum therapy) or platinum-refractory (no response to platinum) with a combination consisting of decitabine and carboplatin.

 This will be an institutional open label phase I/II trial to determine the safety and the biologic activity of the Decitabine/Carboplatin combination.

 The investigators will determine whether Carboplatin can be safely combined with Decitabine, the optimal dose schedule and the investigators will define whether at this dosage, the regimen is biologically active (i.

e.

 induces demethylation of target genes).

 In the second part of the trial, the investigators will determine the clinical activity of the combination in a population of patients with platinum-resistant ovarian cancer.

