(fifthQuint)Comparison of Non-Invasive Methods of Assessing Fluid Responsiveness in ED and ICU Patients.

 This is a diagnostic accuracy study comparing selected ultrasound techniques to a well validated standard for predicting fluid responsiveness in septic patients (NICOM).

 The primary outcomes will be reported in sensitivity, specificity, positive predictive value, negative predictive value, likelihood ratios, and receiver operating characteristic curves.

 The timeframe for measurement is within 72 hours of the subjects' admission.

 Determination of the outcome (i.

e.

, whether a subject is fluid responsive) is based upon the data generated by the NICOM device.

 The NICOM generates data within 5 minutes of assessment.

 The ultrasound modalities to be studied will generate data within 5 minutes of assessment as well.

 The US data will be compared to the NICOM data to generate the statistics listed in this protocol.

 There is no further planned follow-up for the subjects.

 1.

 The investigators will compare the ability of dynamic changes in inferior vena caval diameter (IVC-CI), dynamic changes in peripheral arterial waveform derived variables (PA Doppler), and dynamic changes in left ventricular outflow tract waveform derived variables (LVOT Doppler) to detect fluid responsiveness (FRes) relative to FRes as assessed by bioreactance cardiac output monitoring before and after passive leg raise (PLR).

 Hypothesis: PA Doppler and LVOT Doppler will have superior sensitivity and specificity to predict FRes in comparison to IVC-CI.

 2.

 The investigators will evaluate data acquisition duration and data acquisition failure rate of IVC-CI, PA Doppler, and LVOT Doppler.

 Hypothesis: PA Doppler will have shorter data acquisition durations in comparison to LVOT velocity variation and IVC-CI.

 Hypothesis: PA Doppler will have lower data acquisition failure rates in comparison to LVOT velocity variation and IVC-CI.

 3.

 The investigators will compare the ability of IVC-CI, PA Doppler, and LVOT Doppler to predict FRes in comparison to FRes as predicted by clinical judgment.

 Hypothesis: PA Doppler and LVOT Doppler will have superior sensitivity and specificity to predict FRes in comparison to clinical judgment.

 4.

 The investigators will evaluate the ability of dynamic changes in PA corrected flow times (cFT) to detect FRes relative to FRes as assessed by bioreactance cardiac output monitoring before and after PLR.

 Hypothesis: cFT will have greatest sensitivity and specificity to predict FRes at a flow time threshold of 15% after PLR.

 Hypothesis: At a flow time threshold of 15%, cFT will have superior sensitivity and specificity to detect FRes in comparison to IVC-CI.

.

 Comparison of Non-Invasive Methods of Assessing Fluid Responsiveness in ED and ICU Patients@highlight

Accurate assessment of fluid responsiveness (FRes) is central to guiding fluid management in septic and critically ill patients.

 As evidence accumulates that both inadequate and excessive fluid resuscitation are associated with increased morbidity and mortality, it is simultaneously becoming increasingly clear that current widely used methods to predict FRes are of questionable accuracy.

 The optimal technique to predict FRes would be a non-invasive point-of-care test with not only a high degree of accuracy, but also one which requires minimal training to perform correctly and may be easily performed repeatedly for serial evaluation of FRes during the ongoing management of the critically ill patient.

 To date, three major ultrasonographic modalities have emerged as viable candidates for the bedside assessment of FRes: 1) measurement of dynamic changes in inferior vena caval diameter (IVC-CI), 2) measurement of dynamic changes in peripheral arterial waveform derived variables (PA Doppler), and 3) echocardiographic measurement of dynamic changes in left ventricular outflow tract waveform derived variables (LVOT Doppler).

 In this study, the investigators will perform the first direct comparison of techniques representing all three of the above modalities in the prediction of FRes against a non-invasive bioreactance cardiac output monitor (the Cheetah NICOM cent ), which has been extensively validated against gold-standard invasive methods of cardiac output measurement.

 The investigators will compare the accuracy of these modalities in both spontaneously breathing and mechanically ventilated patients using passive leg raise testing (PLR) as a surrogate for volume challenge.

 In addition, the investigators will also elicit information from the treating physician(s) on their clinical assessment of FRes.

 The investigators will recruit adult patients in the ED and ICU with sepsis, who have received an initial bolus of 20-30 cc/kg of IV fluid, and can tolerate the PLR and US procedures.

 Prior to US and NICOM measurement, investigators will ask the attending physician managing the patient regarding their assessment of the their fluid status.

 Then, separate investigators will perform US and NICOM measurements independently to ensure blinding.

 NICOM data, which has been well validated in septic patients, will be shared with the attending physician.

 They will then be asked if this new data will change management.

