(fifthQuint)Breast-Conserving Therapy in Patients With Triple-Negative Breast Cancer.

 STUDY POPULATION: Operable patients with T1-2N0-1M0 triple-negative breast cancer OBJECTIVES: Primary To assess the impact of breast-conserving therapy on disease-free survival compared with mastectomy in patients with T1-2N0-1M0 triple-negative breast cancer.

 Secondary To assess the impact of breast-conserving therapy on locoregional recurrence-free survival (LRRFS) and distant metastasis-free survival (DMFS) compared with mastectomy in patients with T1-2N0-1M0 triple-negative breast cancer.

 OUTLINE: This is a prospective, randomized, open, single-center Phase III clinical study.

 Patients undergo either lumpectomy or mastectomy with surgical axillary staging with all lesions resected to negative margins based on the results of randomization generated by computer.

 Patients with stage I and II receive adjuvant chemotherapy using TC and TAC regimen respectively.

 Since all tumors are smaller than 5cm and metastatic lymph nodes are less than 4, patients undergoing mastectomy do not receive radiation therapy.

 On the hand, within 4-8 weeks after completion of chemotherapy, patients undergoing breast-conserving surgery receive radiation therapy as follows: (1) N0: Radiation therapy to whole breast (+boost to tumor bed) or consideration of partial breast irradiation in selected patients; (2) N1: Radiation therapy to whole breast (+boost to tumor bed), infraclavicular region, and supraclavicular area with or without radiation therapy to internal mammary nodes.

 After completion of study treatment, patients are followed up every 3 months for 2 years and then 6 months for years 3-5.

.

 Breast-Conserving Therapy in Patients With Triple-Negative Breast Cancer@highlight

RATIONALE: Triple-negative breast cancer (TNBC) is an aggressive subtype shown to have a high risk of locoregional recurrence (LRR) and distant metastasis (DM).

 The equivalent impact of breast-conserving therapy (BCT) and mastectomy on disease-free survival in patients with early breast cancer has been established by a number of large randomized controlled trials and meta-analysis.

 However, ongoing dispute exists on whether TNBC is a good candidate for BCT.

 PURPOSE: This prospective, randomized, open, single-center Phase III clinical study is conducted to compare efficacy and safety of breast-conserving therapy and mastectomy in treating Chinese patients with early TNBC.

