(fifthQuint)Testing for Tuberculosis in the United Kingdom HIV Infected Population.

 The investigators would like to assess a cohort of human immunodeficiency virus (HIV) infected individuals at the Ian Charleson Centre, Royal Free Hospital to assess the rates of latent tuberculosis infection (LTBI) using both tuberculin skin test (TST) and interferon gamma release assay (IGRA), systematically investigating for active tuberculosis (TB) with a symptom questionnaire and chest X ray, and test for Mycobacterium tuberculosis (MTb) in their sputum, both coughed up spontaneously where possible and by inducing sputum using a saline nebuliser and testing this using microscopy and culture (the established method for detecting MTb), nucleic acid amplification testing (using Xpert.

TB, a new genetic test for TB that decreases the time required for detection) and a novel 16S ribosomal ribonucleic acid (RNA) test, used to look for TB burden.

 A cohort of people with HIV infection will be invited to take part in the study.

 Subjects will have varying place of origin, TB exposure risk, blood cluster of differentiation 4 (CD4) cell count, HIV viral load, exposure to antiretroviral drugs used to treat HIV.

 All patients with a new diagnosis of HIV will be invited, as will a group of subjects already undergoing HIV care (selected by stratified sampling) in order to recruit 180 subjects originating from sub-Saharan African countries and 120 from lower TB incidence countries (such as the United Kingdom, UK and Western Europe).

 The study is powered to detect a difference between all forms of TB infection in subjects from sub-Saharan Africa to those from the UK (or other low TB prevalence countries) with 80% power, allowing a 5% type I error.

 The participants will be recruited and a questionnaire, X ray, sputum induction, TST and IGRA can be taken in one visit.

 They will need to return 48--72 hours later to have the TST read on their arm.

 Those with evidence of LTBI (with positive TST or IGRA) will be invited to TB/HIV clinic and quality of life scores recorded as part of the study.

 Research Questions: 1.

 To determine the feasibility, yield and cost--effectiveness of testing for M.

 tuberculosis infection in UK HIV infected individuals.

 2.

 To determine the prevalence of subclinical and active TB in a UK HIV infected clinic 3.

 To determine the sensitivity and specificity of systematic screening questionnaires for detecting cases of active TB outside of high TB prevalence settings 4.

 To determine concordance between TST and blood IGRA (T-Spot.

TB) in latent TB infection 5.

 To identify risk factors for latent TB infection in the clinic population 6.

 To determine the underlying frequency of airways disease (using spirometry) and of respiratory symptoms 7.

 To determine the sensitivity and specificity of 'Xpert MTB/RIF' polymerase chain reaction (PCR) testing of sputum and induced sputum compared to mycobacterial microscopy and culture 8.

 To compare the Molecular Bacterial Load (MBL) assay, based on 16S rRNA, and other available molecular assays, with Xpert MTB/RIF for detection of Mtb 9.

 To determine quality of life scores (EQ-5D) for those with HIV infection, with and without latent TB infection and/or undergoing treatment On those with evidence of LTBI: 10.

 To determine uptake of latent TB therapy (6 months isoniazid treatment) 11.

 To determine cost of latent TB treatment (including screening costs, clinic time) 12.

 To determine quality of life and rate and severity of adverse events on latent TB treatment 13.

 To determine rate and time until active TB in those with LTBI on or off antiretroviral therapy (ART) and/or isoniazid prophylaxis In all patients (over 20 year follow up): 14.

 To determine the rate of incident active TB 15.

 To determine the time until progression to active TB with in patients with abnormal radiographic changes consistent with old tuberculosis exposure or disease Data will be generated by the Research team and University College London (UCL) Statistics team.

.

 Testing for Tuberculosis in the United Kingdom HIV Infected Population@highlight

Human Immunodeficiency Virus (HIV) is the strongest individual risk factor for the reactivation of tuberculosis (TB) after previous exposure to Mycobacterium tuberculosis (MTb).

 This risk is reduced but not completely eliminated when HIV is treated with antiretroviral therapy (ART).

 Both the British HIV Association (BHIVA) and National Institute of Health and Care Excellence (NICE) suggest testing for latent TB infection in HIV infected individuals, but use different criteria.

 The cost -effectiveness of either approach has not been assessed, nor is testing widespread.

 A certain proportion of HIV infected subjects in Africa have MTb detectable in their sputum despite not having symptoms (such as cough or weight loss), nor changes on a chest x ray.

 It is unclear if this happens in lower TB prevalence areas such as the United Kingdom (UK).

 We intend to test a cohort of HIV infected subjects for evidence of latent TB using a tuberculin skin test (TST) and Interferon Gamma Release Assay (IGRA), ask about symptoms (using a standardised questionnaire) and to induce sputum using a saline nebuliser, to detect MTb using microscopy and culture, and newer nucleic acid amplification (genetic) techniques.

 Some patients, despite being exposed to TB in the past, will not mount a response using an IGRA or TST, which maybe due to an abnormal immune response.

 This lack of response seems more common in HIV.

 By investigating the number of patients with positive TST, IGRA, chest X ray and evidence of MTb in their sputum, in the context of place of birth, previous exposure to TB, CD4 count and other medications, we can assess the cost- effectiveness of systematic TB screening and the use anti-TB antibiotics to prevent reactivation of TB.

 In time, we will be able to answer important questions about the time taken to reactivate TB in individuals with HIV who do or don't take preventative anti-TB medications in the UK.

