(secondQuint)MCG Post Myocardial Infarction Study.

 Magnetocardiography (MCG) is a non-contact, passive, imaging technique that detects the magnetic fields generated by the electrical activity of the heart.

 The MCG technology has been evaluated in several clinical studies, demonstrating its potential usefulness in the detection of patients with stable angina and acute coronary syndrome (ACS), including non-ST segment elevation myocardial infarction (NSTEMI).

 Previous studies have been completed using earlier versions of the Vitalscan device.

 Results showed that the device could differentiate between patients with confirmed ischaemic heart disease (IHD) and NSTEMI, those with non-IHD experiencing chest pain and healthy (non-ischaemic) control subjects.

 The aim of this pilot study is to assess the difference between abnormal MCG images from patients with a confirmed and recent myocardial infarction (MI)and normal images from previously obtained healthy volunteer controls scanned with the current device, so that comparisons can be made to the data acquired from the previous studies.

.

 MCG Post Myocardial Infarction Study@highlight

The study is being performed to evaluate a new portable medical device, the Creavo Vitalscan Magnetocardiograph (Vitalscan) on patients who have had a confirmed myocardial infarction (heart attack) within the previous 12 weeks.

