(fifthQuint)Functional Electrical Stimulation (FES) and Reconstructive Tetraplegia Hand and Arm Surgery.

 In the rehabilitation of patients with a tetraplegia, FES is a common used method to improve the function of the arms and hands.

 The effects of FES also gain in importance considering the procedure of reconstructive arm and/or hand surgery in tetraplegic patients.

 The functioning of arm and hand muscles can be improved by surgically inverting intact muscles.

 Therefore, strengthening of the donor and recipient muscles with FES seems to be reasonable.

 So far it is not established if systematic training with FES before and after reconstructive hand and arm surgery could additionally improve the outcome in terms of strength, motor learning and function.

 However, clinical observations show a possible positive effect of FES.

 The aim of the present randomized controlled study is to evaluate the use of FES before and after a reconstructive arm and/or hand surgery in order to increase the strength of the donor and recipient muscles, and thus, improving the result regarding strength and functionality.

 A total of 30 tetraplegic patients who are planned to have a reconstructive arm and/or hand surgery at the Swiss Paraplegic Centre will be included into the study.

 The participating subjects will be randomized into two groups: a control and an intervention group.

 The control group (15 patients) will receive defined standardized physio- and occupational therapy after the surgery.

 The intervention group (15 patients) will receive a combination of standardized physio- and occupational therapy and FES, before and after surgery.

 The standardized therapy will be supplemented with FES for 3 months, 3 x 30min per week.

 To verify the effects of FES on muscular strength and functionality of the arms and hands, several assessments will be conducted at 4 different time points (T1: 12 weeks before surgery // T2: just before surgery // T3: 4 weeks post-surgery // T4: 16 weeks post-surgery).

 The course of the voluntary muscular strength and the strength generated by FES of both, the donor and the recipient muscle will be measured.

 In addition, the change in muscle volume in forearm and upper arm will be assessed by ultrasound.

 Furthermore, a standardized test to check several grasping action will be performed and there will also be a manual testing of the muscles in arms and hands.

 Statistical analysis of these assessments enable an estimation of the benefit and effect of FES as an additional therapy in the context of reconstructive arm and/or hand surgery for tetraplegic patients.

.

 Functional Electrical Stimulation (FES) and Reconstructive Tetraplegia Hand and Arm Surgery@highlight

FES is a common and established method in the rehabilitation of persons with spinal cord injury (SCI).

 Some known effects of FES were investigated in several studies e.

g.

 avoiding disuse and denervation atrophy, improving muscle force, power output and endurance changing muscle fibre type, increasing cross sectional area of muscle, increasing muscle mass, activation of nerve sprouting, reducing spasticity and motor learning.

 Most of the studies investigated the impact of FES in the lower limbs.

 For the upper extremities fewer studies exist.

 However, it is supposed that the effects of FES are similar.

 In the rehabilitation of persons with tetraplegia, FES, especially the stimulation of the upper extremities triggered by electromyography (EMG) is an established method to generally improve hand and arm function.

 However, none of those studies has investigated the effect of FES in combination with reconstructive tetraplegia hand surgery.

 Improved muscle strength is supposed to improve the functional outcome in participation.

 Additionally, FES could increase the motor learning process.

 Supported by the clinical observation we hypothesize that FES has a positive influence on the outcome of surgical reconstruction of tendon and/or nerve transfers.

