(fifthQuint)Association Between Heat Pain Detection Threshold and Area of Secondary Hyperalgesia.

 The study participants will be tested with 3 types of clinical pain models on two separate identical study days.

 A minimum of 7 days will separate the two study days, thus, the minimum length of the study is 7 days, but can be higher.

 The 3 types of pain conditioning consist of 1) Brief thermal sensitisation (BTS), 2) Heat pain detection threshold (HPDT), and pain during 1 min.

 thermal stimulation (p-TS.

 The order of the stimulations (HPDT and BTS) is randomised for each patient and each study day, by a random allocation sequence, computer-generated by Copenhagen Trial Unit and stored in sealed and opaque envelopes to secure adequate allocation concealment.

 p-TS is conducted subsequent to BTS and HPDT.

 The participants will complete the psychological tests Pain Catastrophizing Scale (PCS) and Hospital Anxiety and Depression Scale (HADS) in their private home prior to study day 1.

 The completed tests will be placed in opaque sealed envelopes to secure blinding of the investigator and outcome assessor.

.

 Association Between Heat Pain Detection Threshold and Area of Secondary Hyperalgesia@highlight

The purpose of this prospective study is to investigate how close Heat Pain Detection Threshold is associated with the area of secondary hyperalgesia, elicited by the clinical pain model Brief Thermal Sensitization.

 Furthermore we wish to investigate how close the clinical pain model: Pain during 1 min.

 heating of the skin (45 degrees celsius), and the psychological tests, Pain Catastrophizing Scale and Hospital Anxiety and Depression Scale are associated with the area of secondary hyperalgesia, elicited by the clinical pain model Brief Thermal Sensitization.

