(fifthQuint)Diabetes Prevention Using SMS Technology.

 Recruitment: - Target recruitment number will be 1834 in total (1134 for India and 700 for UK).

 - In India people at risk will be ascertained using the Indian Diabetes Risk Score followed by measurement of a single blood sample to assess glucose regulation (HbA1c) in those with high scores.

 - In the UK, high risk subjects will be ascertained from the National Health service (NHS) Health Check Scheme and from routine screening in primary care; UK recruitment will also be based on HbA1c.

 Trial Design: 1.

 Visit 1 (Screening) - Potential subjects will be invited to clinic for screening to determine their prediabetic state (defined as an HbA1c of 6.

0-6.

4%)and suitability to take part in the study.

 - Screening involves clinical measurements, physical measurements and laboratory measurements.

 Also, baseline questionnaires will be carried out at this visit.

 - ActiGraph, physical activity monitoring device will be fitted on that is to be kept for 7 days.

 2.

 Visit 2 (Education and Randomization) - One-to-One structured education on healthy lifestyle will be given to all successfully screened subjects.

 - The subjects then will be randomized using computer generated numbers either to usual care (control arm) or usual care with text messaging (intervention arm).

 3.

 Visit 3 (6 month follow up), Visit 4 (12 month follow-up) and Visit 5 (24 month follow-up) - each visit involves - clinical measurements, physical measurements and laboratory measurements - Questionnaires - Fitting ActiGraph on subject Efficacy: - The primary outcome will be progression to type 2 diabetes - Secondary outcomes will be: - Change in physical activity as measured by Actigraph and Recent Physical Activity Questionnaire (RPAQ) - Change in weight, BMI, waist circumference, hip circumference and waist:hip ratio - Change in fasting plasma glucose and HbA1c - Change in lipid profile - Liver function as measured by alanine transaminase (ALT), aspartate transaminase (AST) and gamma-glutamyl transferase (GGT) - Change in diet assessed by validated food frequency questionnaire - Quality of life assessed by EQ-5D questionnaire - Cardiovascular biomarkers including hsCRP, adiponectin, PAI (plasminogen activator inhibitor), uric acid, white cell count, albumin, IL-6, IL-1, TNF-, monocytes chemotactic protein-1, leptin, resistin, endothelin-1, E-selectin, soluble vascular cellular adhesion molecule-1 (sVCAM-1) and soluble interstitial cellular adhesion molecule-1 (sICAM-1) - Insulin secretion and sensitivity as calculated from fasting plasma glucose and insulin measurements Data: - During the course of the study visits some data will be stored on laptop computers, not connected to the internet, for later statistical analysis.

 These data will be coded and non identifiable.

 - Participant data will be stored in a locked filing cabinet in a secure room in Imperial College Healthcare NHS Trust.

 Only the research team (clinical research fellow and research nurse) will have access to the filing cabinet.

 - At the end of each visit the anonymised data will be transferred immediately to the secure NHS computers and will be deleted from the laptop.

 Access to NHS computers is only by members of NHS staff with appropriate log in privileges.

 - All data will be stored in an anonymised form by using study numbers for identification of participants.

 - The NHS code of confidentiality will be followed and all activity will meet the requirements of the data protection act.

 - Only members of the clinical research team and those responsible for direct care will have access to subjects' data during the study.

 - The data generated by the study will be analyzed by the research team from Imperial College.

 The analysis will be on anonymised data and will take place in Imperial College Healthcare NHS Trust and in Imperial College academic buildings in the Faculty of Medicine.

 Direct Access to Source Data/Documents: *The investigator(s)/institution(s) will permit trial-related monitoring, audits, and regulatory inspection(s), providing direct access to source data/documents.

 Statistics: - Sample size is based on previous data from the Indian Diabetes Prevention studies.

 We estimate that the two year conversion rate to diabetes in the control group will be 25%.

 A total of 1134 individuals per group are required across both countries to detect a 20% reduction in risk of progression with 80% power at 5% significance.

 A study of this size will be able to address the question of whether, overall, the text messaging system is effective in reducing progression to diabetes in high risk individuals.

 It will not be sufficiently powered to address this question in each country separately, nor to detect differences of effect between them.

 However, a study of this size is extremely well powered to detect an impact on the continuously distributed secondary outcome of moderate to vigorous physical activity (MVPA) as assessed by Actigraph.

 The standard deviation of MVPA in the ProActive trial was 17 minutes per day.

 Thus the study overall has >99% power to detect a difference of 4 minutes per day of extra walking between groups.

 It will be possible, therefore, to examine country specific effects of the intervention on MVPA - Missing, unused, and spurious data will be assessed on an individual basis and may be ignored, withdrawn or the visit may be removed from the analysis with appropriate justification adjudicated by the Principal Investigator.

 - Data will be analyzed using parametric and nonparametric statistical methods for the primary and secondary outcomes.

 Regulatory Issues: - Ethics Approval The Chief Investigator has obtained approval from the Westminster Research Ethics Committee.

 Local Research and Development(R&D) Approval at each participating NHS Trust is also required before accepting participants into the study.

 The study will be conducted in accordance with the recommendations for physicians involved in research on human subjects adopted by the 18th World Medical Assembly, Helsinki 1964 and later revisions.

 - Consent to enter the study must be sought from each participant only after a full explanation has been given, an information leaflet offered and time allowed for consideration.

 Signed participant consent should be obtained.

 The right of the participant to refuse to participate without giving reasons must be respected.

 All participants are free to withdraw at any time from the protocol treatment without giving reasons and without prejudicing further treatment.

 - The Chief Investigator will preserve the confidentiality of participants taking part in the study and is registered under the Data Protection Act.

 - Indemnity Imperial College London holds negligent harm and non-negligent harm insurance policies which apply to this study.

 - Imperial College Academic Health Science Centre will act as the main Sponsor for this study.

 Delegated responsibilities will be assigned to the NHS trusts taking part in this study.

 - The study may be subject to inspection and audit by Imperial College London under their remit as sponsor and other regulatory bodies to ensure adherence to GCP and the NHS Research Governance Framework for Health and Social Care (2nd edition).

.

 Diabetes Prevention Using SMS Technology@highlight

Type 2 diabetes is a major healthcare problem in the developed and developing world.

 Recent clinical trials have demonstrated that it may be prevented by lifestyle intervention focused on diet and physical activity.

 These trials have been expensive and labour intensive and this has limited translation of the known benefits to the population at large.

 We propose using a mobile phone intervention for lifestyle change and will assess it in a clinical trial(study) in people with impaired glucose regulation (high risk at developing type 2 diabetes).

 The study will be conducted in both India and the UK.

 The purpose of the study is to assess the effectiveness and acceptability of a text messaging system to prevent the progression to diabetes in people with high risk.

 The study involves five visits to clinic over 2 year period.

 Study participants will be divided into two groups by the computer generated random method - one is 'Usual Care' group and the other 'Text Messaging' group.

 - Usual care will consist of a 30 minute interview, delivering personalized diet and exercise advice, supplemented by written material and education regarding diabetes.

 This will be delivered once at the beginning of the study.

 - The intervention group will undergo the same initial interview and, in addition, will receive 3 times weekly text messaging with education, advice, support and motivation.

 These messages will be personalized to individual targets set at the initial interview.

 The primary outcome will be progression to diabetes, with and without SMS intervention.

 Secondary outcomes will be improvements in physical activity (reported and directly measured), body weight and other cardiovascular risk factors (blood pressure, total and HDL cholesterol and serum triglycerides).

