(thirdQuint)Adaptive Recalibration of Prosthetic Leg Neural Control System.

 The investigators propose to use a powered knee-ankle prosthesis that is not yet commercially available.

 The hierarchical control framework the investigators are developing will be equally applicable to any prosthetic leg that needs to be transitioned between ambulation modes, including microprocessor-controlled passive devices.

 The overall objective is to develop and evaluate an adaptive framework for controlling lower limb prostheses that compensates for changes in EMG signals.

 When a participant walks on a lower limb prosthesis, the output of the high-level controller (or ambulation mode predictor) directly influences patterns generated by the participant.

 After the participant has completed the subsequent stride, a gait pattern estimator (GPE), will provide a label of what the participant actually did.

 This may differ from the ambulation mode predictor output if there was a misclassification.

 The label will then be used to update the ambulation mode predictor algorithm such that future steps are predicted with higher accuracies.

 Finally, the resulting system will be transferred to an embedded system and tested in real-time with transfemoral amputees and compared to a non-adaptive system.

.

 Adaptive Recalibration of Prosthetic Leg Neural Control System@highlight

The purpose of this study is for transfemoral amputees to walk with an experimental robotic prosthesis.

 Electric signals will be measured from their muscles and used to help control an artificial leg.

 The investigators will record from sensors placed on a prosthesis and electric signals measured from muscles in the participants leg to see if the investigators can develop better computer programs to help predict subject actions and prostheses function.

