(thirdQuint)Out-of-Hospital Resuscitation in Winterthur - an Outcome Study.

 The Primary objective of this study is to evaluate the Quality of out-of-Hospital resuscitation by the ambulance Service from the Kantonsspital Winterthur including a 1-year follow-up of the survivors.

 In this follow-up we evaluate the Quality of life by a validated questionnaire.

 The following endpoints will be retrospectively analysed: time-to-Response Interval; Initial cardiac rhythm; medications given; number of Defibrillations; return of spontaneous circulation, Overall costs for the local health System Furthermore length of hospital-stay, survival until Hospital discharge, one-year survival, Quality of life one year after resuscitation and total costs will be analysed.

.

 Out-of-Hospital Resuscitation in Winterthur - an Outcome Study@highlight

The investigators will retrospectively examine all patients with out-of-hospital resuscitation by the emergency medical Team (EMT) from the Kantonsspital Winterthur in the year 2013 with a one year follow-up and a structured interview about Quality of life.

 Furthermore, the costs generated by the local health system are analysed.

