(fifthQuint)Pressure Support Ventilation With the Anesthetic Conserving Device.

 Pharmacological sedation is often necessary in mechanical ventilated intubated patient.

 Since a little time, sevoflurane can be used in the intensive care unit via a specific heat and moister exchanger called the Anesthetic Conserving Device (AnaConDa(R), SedanaMedical AB, Uppsala, Sweden) placed between the Y piece of the ventilatory circuit and the endotracheal tube.

 Sevoflurane is known to have ventilatory interesting effects such as bronchodilatation that can be useful in the treatment of severe asthma.

 These effects could be of interest in the intensive care ventilated patients.

 On the other hand, the AnaConDa(R) device could have negative influence on ventilatory mechanics caused by the increased dead space and the resistance to air flow.

 This negative effect with worsening of work of breathing (WOB) was demonstrated with classic heat and moister exchanger compared to heated humidifiers in pressure support ventilation (PSV).

 In this way, we would like to study the mechanical effects of the sevoflurane administered with the AnaConDa(R) compared to a classic management with a heated humidifier and sedation with intravenous remifentanil in PSV consecutive intensive care patients.

.

 Pressure Support Ventilation With the Anesthetic Conserving Device@highlight

Sevoflurane inhalational anesthetic has got pulmonary effects such as bronchodilatation.

 These effects could be of interest in intensive care patients ventilated in pressure support ventilation mode.

 The purpose of this study is to evaluate mechanical respiratory effects of sevoflurane administered through a new specific heat and moister exchanger called the Anesthetic Conserving Device (AnaConDa(R)) in pressure support ventilation in intensive care patients.

 In fact, dead space and resistance generated by the device could cancel and even deteriorate the potential positive effects of sevoflurane on ventilation.

