(thirdQuint)Use of the Stethoscope to Confirm Breathing Tube Placement.

 Unrecognized esophageal intubation results in disastrous consequences.

 Fortunately, a variety of techniques have been cited to confirm placement of the endotracheal tube.

 However, even end-tidal CO2 monitoring, considered to be the gold standard, has been associated with false positive and false negative results.

 In addition, use of this monitor requires ventilation through the tube, resulting in gastric distention if the esophagus has been intubated.

 When the lateral neck is auscultated during insertion of an endotracheal tube, there is a distinct difference between the sounds generated by a tube placed in the esophagus compared to a tube inserted into the trachea.

 Stethoscopes are readily available in any OR setting, and ventilation and release of cricoid pressure need not occur prior to confirmation of tube placement.

 However, this technique has yet to be validated.

 A series of sounds heard at the lateral neck during both tracheal and esophageal intubation will be recorded using an electronic stethoscope.

 These sound files will be played to a group including both experienced and inexperienced intubators, who will be asked to identify which sounds represent tracheal and esophageal intubation.

 Overall accuracy will be determined for the group of listeners.

.

 Use of the Stethoscope to Confirm Breathing Tube Placement@highlight

This study is intended to validate the use of neck auscultation with an electronic stethoscope during intubation to confirm tracheal tube placement.

 It is hypothesized that the ability to confirm correct tube placement with this technique will be similar to that of the end-tidal CO2 monitor, the current gold-standard device for confirming tracheal intubation.

