(fifthQuint)Assay Development for Cancer Biomarkers.

 Potential participants will be approached by clinical or research team members and asked whether they would be interested in joining this study.

 Participant Information Sheet will be handled and discusses with individuals, highlighting their involvement, risk and benefit of this research.

 In particular, participation in the study will not alter any current therapies of the volunteers.

 Having left sufficient time to decide, potential participants will be asked to sign a Consent Form.

 After obtaining informed consent, volunteers will be asked to donate blood, urine, sputum (saliva) or other body fluids, like bronchoalveolar lavage, for our study, at the same time other analyses are carried out as part of individuals' usual medical care.

 If some participants are already scheduled to receive a novel drug therapy in an existing trial, we may ask them to contribute with small amount of blood, saliva, urine or other body fluids, twice, before and after the programmed treatment.

 Samples will be collected at the same time as participants' routine medical examinations are carried out.

 Biological specimens will be collected and stored according to sample type and test specifications; then separation of cellular components and soluble factors from liquid part will be performed by research team members.

 Isolation techniques will vary based on the sample source.

 Depending on the specific assay to be developed, protein content will be analysed by flow cytometry, enzyme-linked immunoassay (ELISA) or other immunoassays, including the beads-based Luminex(R) technology.

 In all these laboratory techniques, the unique interaction between a specific antibody and antigen enables identification of single or multiple target proteins inside a complex protein mixture.

 Flow cytometry uses fluorescence properties of some dyes to evaluate the presence of specific markers on the surface or inside healthy or cancerous cells.

 This will help establish frequency of specific cell populations or intensity of specific markers on the cells.

 Likewise, ELISA allows qualitative and quantitative characterisation of soluble substances; multiple target proteins in suspension can be evaluated with Luminex(R) procedure within the same sample.

 Other biochemical techniques, such as immunoblotting can be used to determine presence/ absence of proteins located either on the cell surface of or intracellularly.

 In addition to proteins, nucleic acid content can be assessed, including DNA, RNA or microRNA by biomolecular techniques.

 Research data will be generated by these laboratory methods as software-specific files, such as flow cytometry standard (FCS) files for results by flow cytometry, images and data tables.

 Parameters like sensitivity, limit of detection and assay variability will also be evaluated and reported in numeric tables.

 During assay development, data from both healthy donors and cancer patients will be compared with standard statistical packages, in order to establish robust tests that can discriminate between the two groups.

.

 Assay Development for Cancer Biomarkers@highlight

Tumour biomarkers are substances produced by cancer or by other cells of the body in response to cancer conditions.

 They are used to help detect, diagnose, manage and predict outcome or recurrence of some types of cancer.

 Tumour biomarkers can also help doctors choose the most appropriate therapy or judge if treatment is successful.

 Several tumour biomarkers are already used in the clinic; however, many others do not meet rigorous scientific standards to enter into clinical practice and some solid cancers can be only detected using tissue biopsy, a rather invasive procedure.

 Likewise, evaluating efficacy of novel therapies during clinical trials relies on adequate and specific laboratory tests.

 Therefore novel biomarkers and novel methods, to measure them, still represent an un-met clinical need.

 This study aims to develop innovative, more sensitive and reliable tests for better targets, in order to assess and monitor circulating cancer biomarkers.

 Easily accessible samples, like blood, will be tested such that invasive tissue biopsies can be avoided.

 Both healthy individuals and cancer patients will be recruited in this study to establish if a laboratory test is powerful enough to distinguish between individuals that may have cancer or not.

 Participants' involvement will also support development of novel tests to decide if a novel therapy is efficiently counteracting cancer growth or not.

 Participants in the study will be asked to donate blood, sputum, urine or other body fluids, depending on the cancer and the assay being developed.

 After participants give their informed consent, the researchers will isolate cells, soluble factors or nucleic acids from body fluids.

 Researchers will then use various laboratory techniques to screen cells, soluble factors or nucleic acids for specific markers.

 This study looks at the effectiveness of using laboratory tests to quantify tumour markers in body fluids and, subsequently, to monitor patients' response to treatments.

