(firstQuint)Application of Magnetic Fields as Adjunctive Treatment for Type II Diabetes.

 The purpose of this pilot study is to determine whether application of magnetic fields generated by the Resonator result in statistically significant reductions in finger stick blood glucose levels, serum glucose and hemoglobin A1c levels.

 The study will also investigate any induced changes in serum lipids and liver function tests as indirect markers of insulin resistance.

.

 Application of Magnetic Fields as Adjunctive Treatment for Type II Diabetes@highlight

The purpose of this study is to see if using a device called the Resonator, that puts out a very low electromagnetic field, effects blood glucose and A1c levels in people with Type 2 Diabetes.

