(fifthQuint)The Effect of Intermittent Energy Restriction Using Meal Replacements in Overweight Chinese Subjects.

 1.

 STUDY DESIGN This will be a single centre, randomized controlled trial (RCT), comparing the intervention in question (Intermittent Energy Restriction (IER), "5:2 diet", treatment: 2 consecutive days of fasting (using meal replacement, Optifast(R)) per week) with a control of "advice only", with 15 participants in each arm, in an adult overweight, Chinese sample, for an intervention period of 12 weeks.

 Each potential participant will be subjected to a pre-study assessment and a trial of 2 consecutive fasting days with Optifast(R) as per intervention.

 Potential participants will be formally enrolled into the study if they successfully tolerated the 2 consecutive fasting days with no contraindications to participation.

 The actual study period is 12 weeks, consisting of 4 study visits and 3 telephone calls between the study visits.

 This study design with a control arm (and randomisation) would provide more conclusive evidence if there is a significant difference between the two groups at the end of the study, with the difference most likely attributed to the intervention (IER, "5:2 diet", treatment).

 2.

 METHODS AND ASSESSMENTS 2.

1.

 Randomisation and Blinding Eligible subjects will be randomised to two groups: the intervention group and the control group.

 This will be achieved using an online randomisation plan generator (www.

randomization.

com), with the plan generated by the Clinical Research Unit in Khoo Teck Puat Hospital (KTPH).

 Assignment will be contained within opaque sealed envelopes, and opened only in the presence of the investigator and the subject.

 With regards to blinding, only personnel performing laboratory measurements will be blinded to the group allocation of the subjects.

 The rest of the study personnel, including the research nurse taking the anthropometric measurements, will not be blinded.

 2.

2.

 Contraception and Pregnancy Testing Females of childbearing age included in the trial will be discouraged from getting pregnant during the study period, but contraception will not be strictly enforced.

 However, if any participant is found to be pregnant or might be pregnant during the course of the study, she will be withdrawn from the study in view of the nutritional demands of pregnancy.

 2.

3.

 Study Visits and Procedures 1.

 Pre-study trial and procedures Interested participants will be assessed for their suitability for the study including physical and psychological health, and their motivation to lose weight.

 Those who continue to be eligible will be given a trial of 2 consecutive fasting days with Optifast(R) as per intervention in this study.

 Those who successfully completed this trial and still express interest in this study will be formally recruited into the study, and the first study visit will then be arranged.

 2.

 Week 0: Study Visit 1 Measurements (height, weight, waist circumference, hip circumference, %body fat by bio-electrical impedance analysis, blood pressure) and laboratory tests (Fasting Lipids, Fasting Glucose, Fasting Insulin, Liver panel, Full Blood Count, B-hydroxybutyrate) will be done during this visit.

 Quality Of Life (QOL) will be assessed using the RAND Short Form (SF)-36 health survey during this visit.

 3.

 Week 4: Study Visit 2 Measurements (height, weight, waist circumference, hip circumference, %body fat by bio-electrical impedance analysis, blood pressure) and laboratory tests (Fasting Lipids, Fasting Glucose, Fasting Insulin, Liver panel, Full Blood Count, B-hydroxybutyrate) will be done during this visit.

 Adherence to the dietary interventions will be assessed based on 7-day food diaries done prior to study visit.

 4.

 Week 8: Study Visit 3 Only measurements (height, weight, waist circumference, hip circumference, %body fat by bio-electrical impedance analysis, blood pressure) will be done during this visit.

 5.

 Weeks 2, 6 and 10: Telephone Call Subjects will be contacted via telephone to reinforce compliance to study protocol and asked for any adverse effects during these calls.

 6.

 Week 12: Final Study Visit Measurements (height, weight, waist circumference, hip circumference, %body fat by bio-electrical impedance analysis, blood pressure) and laboratory tests (Fasting Lipids, Fasting Glucose, Fasting Insulin, Liver panel, Full Blood Count, B-hydroxybutyrate) will be done during this visit.

 Adherence to the dietary interventions will be assessed based on 7-day food diaries done prior to study visit.

 QOL will be assessed using the RAND Short Form-36 health survey.

 7.

 Discontinuation Visit and Procedures Participants may withdraw voluntarily from participation in the study at any time.

 If this occurs, the reason to withdraw will be documented and participants will be offered other obesity treatment options in Health For Life Centre (HFLC), KTPH.

 Subjects who accept other treatment options will be managed accordingly like usual patients treated in HFLC, KTPH and there will be no further trial procedures for these subjects.

 However, if subjects no longer wish to embark on a weight loss journey, they will be advised to continue scheduled evaluations as per protocol as far as possible to facilitate an intention to treat analysis.

.

 The Effect of Intermittent Energy Restriction Using Meal Replacements in Overweight Chinese Subjects@highlight

Background and Aims: The "5:2 diet", a form of intermittent energy restriction, has been popularized in Europe and USA.

 The rationale behind this approach is that two days of dieting is potentially more achievable, yet long enough to reduce overall weekly energy intake.

 However, this specific approach is lacking in evidence.

 Therefore, we are keen to investigate the effectiveness of this form of intermittent energy restriction compared with a control intervention (providing dietary and exercise advice only), in overweight, Chinese subjects, for an intervention period of 12 weeks.

 Design and Methods: This will be a randomized controlled trial, with 15 subjects in each arm, for an intervention period of 12 weeks.

 Subjects randomized to the treatment group will take three packets of a meal replacement product (Optifast(R)) per day during two consecutive fasting days, and take a healthy balanced diet that meet estimated energy requirements for the remaining five days.

 Subjects randomized to the control group will be given general diet advice and allowed to eat ad libitum throughout the study period.

 Measurements and laboratory tests will be done at baseline, 4 weeks and 12 weeks.

 Adherence to the dietary interventions will be assessed at 4 weeks and 12 weeks using 7-day food diaries.

 Significance: This will be the first study looking at an Asian population and will serve as a pilot towards a larger randomized trial.

 If this approach is found to be safe, effective and easier to adhere compared to the traditional continuous energy restriction, then it will be a very valuable option in the treatment of obesity, which has become an increasing problem globally including Singapore.

