(firstQuint)Goal Direct Therapy to Prevent Acute Kidney Injury.

 This is a prospective, randomized controlled trial to assess the influence of use of angiotensin-converting enzyme inhibitors (ACEI) and angiotensin receptor blockers (ARB) in the development of the Acute Kidney Injury in the postoperative period of cardiac surgery.

 Patients undergoing cardiac surgery at the Heart Institute (InCor) - Brazil, will be randomized and in accordance with a list of random numbers, generated by a computer program, will be allocated in one of the groups (GDT or standard).

.

 Goal Direct Therapy to Prevent Acute Kidney Injury@highlight

This is an randomised controlled trial to investigate an strategy based in a protocol in prevention of acute kidney injury after cardiac surgery.

