(firstQuint)Analysis of De-identified Data From Commercially-available App Lose It!.

 The study team analyzed de-identified user data collected by Lose It! for the purposes of investigating behavioral aspects of weight loss and maintenance, including engagement with the platform; user-reported data on diet, exercise, and other behaviors; data generated by Lose It! describing macronutrient or total calorie intake; periodicity of weight-related actions; user-reported demographic information; and any data from linked applications within Lose It!.

 All data was anonymized and exchanged as limited data sets.

.

 Analysis of De-identified Data From Commercially-available App Lose It!@highlight

The study team analyzed de-identified user data provided by the commercial app Lose It!, an entity of FitNow, Inc.

