(thirdQuint)Efficacy and Safety of Half Dose Alteplase Added to Heparine, in Patients With Moderate Pulmonary Embolism.

 The guidelines of the European Society of Cardiology (ESC2014) confirm the indication for pharmacological revascularization with thrombolysis only to cases of pulmonary embolism at high risk and thus hemodynamically unstable (class of recommendation I, level of evidence B), reserving the surgical or interventional procedures to cases where thrombolysis has failed or is contraindicated, while it remains controversial the role of thrombolysis in patients with pulmonary embolism at intermediate risk; the current state, in EP intermediate risk, the standard treatment involves the administration of low molecular weight heparin (LMWH), or fondaparinux (for 5-10 days followed by anticoagulation therapy with vitamin K antagonists) or alternatively the new anticoagulants oral (NAO).

 Although the results of the study PEITHO, recently published, confirm the indication for thrombolytic therapy for primary reperfusion in patients with embolism pulmonary high risk and provide element of reflection about the incidence of intracranial hemorrhage major, recent studies suggest that the thrombolysis with tPA to reduced dose (about half the dose that used in standard thrombolysis) in addition to anticoagulants (low molecular weight heparin) may reduce pulmonary hypertension (systolic artery pulmonary pressure> 40 mmHg) and the incidence of recurrent PE.

 In this protocol, based on the study MOPETT and pharmacokinetic data available, it is used a "safe dose" (safe dose reduced) of alteplase which provides a intravenous (iv) bolus loading dose of 10 mg in 1 min, followed by intravenous infusion 40 mg within two hours (for patients weighing 65 -70 years (increased risk of bleeding complications related age and comorbidities).

.

 Efficacy and Safety of Half Dose Alteplase Added to Heparine, in Patients With Moderate Pulmonary Embolism@highlight

The primary aim of this study is to evaluate whether mid dose (safe dose) of Alteplase in addition to standard treatment with heparin (LMWH) in patients with pulmonary embolism (PE) at intermediate risk, it is effective to reduce: - right ventricular dysfunction - pulmonary hypertension 24 hours and 7 days after the treatment - PE recurrence to 7days and 30 days after the treatment without increasing the incidence of bleeding intra-extracranial