(fifthQuint)Differences in Human Germinal Center B Cell Selection Revealed by Analysis of IgVH Gene Hypermutation and Lineage Trees in Inflammatory Bowel Disease.

 1.

 Extraction of Ig gene sequences from IBD patient gut samples.

 The proposed study aims to elucidate the role of B cells in IBD via investigating their Ig gene diversification.

 Hence the first step should be to extract Ig gene sequences from samples (cases of resection procedure) archived in the pathology laboratory of the Sheba Medical Center.

 Samples from both CD and UC cases will be used, DNA will be extracted and Ig gene sequences will be amplified via PCR, in order to generate sufficient data for the bioinformatical analysis.

 Samples from inflamed gut segments will be compared to samples from uninflamed segments (where available), in order to provide an internal control for the comparison of IBD-related and unrelated B cell clones.

 2.

 Investigation of the repertoire and the degree of clonality in B cells implicated in IBD, based on the sequences extracted under aim (1).

 We assume that B cells involved in a chronic disease state undergo Ig gene diversification for much longer times than B cells in normal short-term immune responses, and hence Ig gene sequences from IBD-related B cells will exhibit a high degree of clonality.

 There may also be biases in specific Ig variable region (V) gene segment usage, as has been observed in other chronic diseases.

 Hence, the sequences obtained under aim (1) will be aligned with human germline V segment sequences, in order to identify any possible biases in V segment usage, and to identify clonal relationships between sets of sequences from the same patient.

 Since even gut samples from healthy humans contain many clonally related Ig gene sequences (see below), we expect to find many such clonal sequences in most samples.

 3.

 Elucidation of the dynamics of the responding B cell clones, using lineage tree analysis of clonal Ig gene sequences found under aim (2).

 Sets of clonally-related Ig gene sequences discovered under aim (3) will be subjected to lineage tree analysis using the methods developed by the Mehr group.

 The results of this analysis will point at the differences between IBD-related and unrelated B cell clones in the dynamics of somatic hypermutation and antigen-driven selection.

 4.

 Search for correlations between the parameters resulting from lineage tree analysis (aim 3) and clinical and patient parameters.

 A particularly interesting question is whether the parameters generated by lineage tree analysis of Ig gene sequences are correlated with clinical parameters describing the patients (e.

g.

 age, gender), the course of the disease (e.

g.

 age of onset, disease duration, symptom severity) and histological characteristics.

 We expect that analysis of these two types of data (bioinformatical and clinical) will reveal quite a few correlations, and that based on these correlations we may be able to enhance the set of diagnostic and prognostic tools currently available to clinicians specializing in IBD.

.

 Differences in Human Germinal Center B Cell Selection Revealed by Analysis of IgVH Gene Hypermutation and Lineage Trees in Inflammatory Bowel Disease@highlight

Our overall objective in this study is to study the role of B cells in inflammatory bowel disease (IBD), using a combination of high-throughput experimental and novel bioinformatical techniques.

 Idiopathic IBD includes Crohn's disease (CD) and Ulcerative Colitis (UC), which are chronic inflammatory disorders of the intestine.

 IBD is common in developed countries, with up to 1 in 200 of individuals affected by theses diseases.

 It is currently thought that the disease arises owing to a complex array of genetic, environmental and immunologic susceptibility factors.

 T cells are thought to cause the lesions, but the B cell population apparently has a significant role as well, through secreting antibodies against certain self-antigens.

 We believe that a major contribution to the understanding of the pathogenesis of IBD, and especially of the immune pathway leading to CD, can be achieved by analysis of the B cell clones participating in immune responses in the gut, in particular their immunoglobulin (Ig) variable region gene diversity, which has never before been studied in the context of IBD.

 The adaptive immune system is one of the only two biological systems capable of continuously learning and memorizing its experiences.

 This is a highly complex, distributed system, in which pathogen recognition, decision-making and action are performed by an interacting network of diverse lymphocytes.

 Immune learning and memory are embedded in the dynamical states of the complete lymphocyte repertoire, and cannot be understood by studying the behavior of single cell types.

 This complexity, further increased by the non-linear behavior of each component, can only be elucidated by using theoretical tools to complement experimental and clinical studies.

 Needless to say, many aspects of the deregulation of lymphocyte clones are not evident in the phenotype of the single cell but rather in the population dynamics of a whole clone (or many clones) of cells, as in B cell lymphomas.

 Such aspects are best elucidated by studies of the population dynamics and genetics of the relevant B cell clone(s).

 In this study, we propose to utilize a novel bioinformatical approach - the analysis of the shapes of Ig gene mutational lineage trees.

 This is the main innovative feature in our proposal, as it taps into parameters that have never before been measured or analyzed with respect to B lymphocytes in IBD.

 While the method is new, it has already been shown that graphical analysis of B cell lineage trees and mathematical quantification of tree properties provide novel insights into the mechanisms of normal and malignant B cell clonal evolution.

 A preliminary analysis of lineage trees from other autoimmune diseases (shown below) indicates that, given sufficient amounts of data, the method could elucidate changes in Ig gene diversification and selection in IBD patients.

 Moreover, we aim to search for correlations between the parameters characterizing Ig gene diversification and parameters characterizing patients, disease history and severity, and histological markers, as this has the potential of yielding novel diagnostic and prognostic tools.

