(fifthQuint)Evaluation of Local Doxycycline in Smokers With Chronic Periodontitis.

 VI- Methods 1.

 Sample Selection After submission and approval of this project to the Research Ethics Committee (CEP) of the Piracicaba Dental School - UNICAMP, will be selected among the patients who seek spontaneously treatment in clinics Graduate FOP-UNICAMP (where also will be performed the clinical phase of the study), 40 patients with an average age between 30 and 59 years, of both genders (male or female) according to the following inclusion criteria: - Patients smokers, but overall good health - patients initially diagnosed with moderate or severe chronic periodontitis (according to the American Academy of Periodontology- AAP, 1999) verified the presence of radiographic periodontal pockets and bone loss; - Patients who have at least four bleeding sites with probing depth (PD)> 5 mm in uniradiculares teeth.

 - Presence of a minimum of 20 teeth; - formal consent to participate in research, after explaining the risks and benefits for individual not involved in it.

 (Resolution No.

 196 of October 1996 and the Dental Code of Professional Ethics (C.

F.

O.

) 179/93).

 The exclusion criteria are: - periapical or pulp change Presence - Presence of systemic changes or use of medications (6 months prior to the study) that may influence response to periodontal treatment (eg, phenytoin, cyclosporine, calcium channel antagonists, and anti-inflammatory steroids and non-steroidal); - Presence hypersensitivity to tetracyclines and their derivatives; - Teeth with involvement furcation in the case of premolars.

 - Pregnancy and lactation 2.

 Study design The study will be clinical, randomized, controlled, double-blind, parallel design, and the treatments are randomly distributed among the patients.

 Selected patients will be divided into 2 groups, whose teeth receive the treatments, as follows: DB group (20 patients), - mechanical debridement in one session and application of placebo microspheres in four periodontal pockts greater than 5 mm DB + DOX group (20 patients), - mechanical debridement in one session associated with the application of 1 mg of microspheres loaded with doxycycline per periodontal pockt, into four sites equal to or greater than 5 mm.

 The PLGA microspheres, used in this study as a controlled drug delivery system, will be produced in the Biomaterials Laboratory of Medicine of the Catholic University of Sao Paulo, according to Moura, 2015.

 The microspheres are loaded with doxycycline hydrochloride ( EMS Sigma Pharma-Generics, Hortolandia, Brazil).

 3.

 Research Plan Initial examination: Selection of 40 patients according to pre-established criteria.

 Initial therapy: All patients will be educated about the causes and consequences of periodontal disease as well as on the importance of prevention techniques, (sulcular brushing and flossing) for periodontal therapy.

 In this phase, there will be supragingival periodontal debridement of all mouth and removal of plaque retentive factors.

 Treatment: All patients will be treated by subgingival debridement of mouth all by the same operator and will be reassessed in 3 months by the study investigator.

 Randomization will be performed through a list generated by computer.

 Reviews of treatment: Patients will be instructed in oral hygiene and will be held the professional control of supragingival biofilm in follow-up visits.

 To standardize the location of the collection of clinical data, guiding probing devices will be made - "stents" with acrylic sheets 1mm thick in a vacuum plasticizing, to survey the sites with PS 7 mm.

 Clinical: The clinical parameters are: 1.

 Gingival Index - IG (Loe and Silness, 1963): Inflammatory signals are collected through the following scores: 0 (absence of gingival inflammation); 1 (mild inflammation - small change in color, texture, absence of bleeding on probing); 2 (moderate inflammation - moderate brightness, redness, swelling and hypertrophy, bleeding on probing); 3 (severe inflammation - marked redness and hypertrophy; spontaneous bleeding, and tendency to ulceration) 2.

 Plaque Index - IP (Ainamo & Bay, 1975): Evaluation of the presence / absence of plaque in binominal standard.

 Number of faces engaged with plate divided by the number present in all faces the patient's teeth 0- no visible plaque; 1- presence of visible plaque 3.

 Bleeding on probing - SS (Muhlemann & Son, 1971): Standard dichotomous.

 0-absence of bleeding; 1- presence of bleeding.

 4.

 position gingival margin - PMG: distance of demarcation in the "stent" to the free gingival margin.

 e Insertion Relative Clinical Level - NICR: distance of demarcation in the "stent" to the base, clinically detectable, the periodontal pocket.

 f- Depth Survey - PS (NICR - PMG): distance from the gingival margin to the base, clinically detectable, the periodontal pocket.

 All clinical parameters are obtained using a periodontal probe of the North Carolina type at baseline, 45 and 90 days after.

 Description of the methods that affect the research subjects: Once selected the study volunteers, they receive all the guidelines relating to the Consent and Informed research following the recommendations of Resolution 466/12 of the CNS.

 Any discomfort that may be caused by periodontal debridement treatment by ultrasound are not different from those caused by treatment coronorradicular scraping, consisting of moderate pain in the treated area and the possibility of dentine hypersensitivity due to exposure of dentinal tubules on the root surface.

 To minimize possible discomfort for these volunteers will be prescribed aftertreatment analgesics and mouthwash fluoride solution in all cases, regardless of whether or not feature dentinal hypersensitivity.

 Local administration of antibiotics (doxycycline) poses no risk to volunteers, since the administered dose will cause only local effects, according to the studies consulted for the preparation of this project.

 Moreover, even if undesirably the administered antibiotic does not achieve the expected results, it can be said that this will not result in patient exposure to some kind of risk, since the dose to be given is insufficient to cause increased discomfort.

 Still, if the conventional treatment with or without the local use of the antibiotic does not yield results in some patients, they will be benefited by the methods of oral hygiene education and clarification on oral health, which contribute to improving the quality of life of patients .

 Microbiological evaluation: It will be done by polymerase chain reaction (PCR) of the "real time".

 This test will allow the quantitative detection of the following bacteria: Porphyromonas gingivalis, Tannerella forsythia, Treponema denticola, Aggregatibacter actinomycetemcomitans and Prevotella intermedia, held in the Discipline of Periodontology Laboratories, located in FOP / UNICAMP.

 1.

 collection of subgingival The area for the collection of material, will be properly insulated and dry with sterile cotton rolls.

 The portion of supragingival bacterial biofilm is removed to then obtain samples of subgingival plaque, by placing strips of paper (Periopaper - (OraFlow Inc.

, New York, USA)) inside bags moderate (5-6 mm ) and deep pockets ( 7 mm) of each patient, for 45 - 60 seconds.

 The volume of gingival crevicular fluid collected is measured with the Periotron 8000 (OraFlow Inc.

, New York, USA) and the paper strips are then placed in microcentrifuge tubes (Eppendorf), coded for each of the patients, and 400 or 200l phosphate buffered saline (PBS) and 0.

05% Tween-20.

 2.

 DNA Purification The bacterial strains obtained from the American Type Culture Collection (ATCC) P.

 intermedia (Pi) (ATCC 25611), P.

 gingivalis (Pg) (ATCC 33277), A.

 actinomycetemcomitans (Aa) (ATCC 29522) from a culture pure T.

 denticola (Td) and T.

forsythia (TF) will be used as positive controls and standards.

 The bacterial DNA is purified using DNA isolation kit PowerSoil(R) (MO BIO Laboratories, Inc.

).

 The DNA concentration is adjusted to 15 ng / ul in water and then an additional six dilutions in 10-fold serial be made.

 Three replicate samples of each dilution (5 ul / sample) are then assayed as described below for each specific DNA.

 The sensitivity of each assay was determined as the lowest dilution of DNA that produced a statistically significantly lower (p , IL-4, IL-6, IL 8, IL-10, IL-17, IL-23, TGF-, TNF-alfa, IFN-alfa and GM-CSF.

 For this analysis, are added to beads labeled sample to monoclonal antibodies specific for each marker to be quantified.

 After the addition of the beads, the sample is hybridized placed on plates and incubated for 2 hours at 37 C.

 The plate is then washed and a secondary antibody joined to a substrate (biotin) is added.

 This assembly is then incubated for 1 hour until, after washing, fluorescent marker (Streptavidin / R-phycoerythrin).

 The plates will then be analyzed by a Luminex 100 instrument program (MiraiBio, Alameda, CA, USA).

 This identifies and quantifies the fluorescence of each bead, corresponding to the inflammatory marker.

 This fluorescence is then transformed, by means of standard curves (third-orderpolynomialequation) values are processed in pg / ml.

 Analysis of proteolytic enzyme activity - zymography Will evaluate the presence and activity of two proteolytic enzymes - MMP 9 (gelatinase - which degrades mainly collagen type IV) and MMP 8 (collagenase - major degradation of collagen type I, II, III) after three months of the completion of debridement mechanical subgingival.

 For this purpose it will be used zymography technique.

 This technique is based on digestion of association between the substrate and verification of the molecular weight of the protease.

 It is used to identify proteolytic activity in enzymes separated (bands) in a polyacrylamide gel under nonreducing conditions.

 Gels are stained with Coomassie blue and the enzyme activity is demonstrated by the absence of coloration (white streaks) in areas where the substrate was degraded.

 Gel zymography: The gel zymography resembles gel electrophoresis also being mounted on a plate system.

 This gel is composed of two parts: Starting from the gel and gel separation.

 The two are divided as to have different position and composition.

.

 Evaluation of Local Doxycycline in Smokers With Chronic Periodontitis@highlight

Summary The aim of this study is to evaluate through clinical, microbiological and immunological parameters using PLGA microspheres (lactic-co-glycolic acid polyacid) containing doxycycline in periodontal therapy in smokers with chronic periodontitis.

 For this study, 40 patients will be selected, with an average age between 30 and 59 years old of both genders (male and female), who spontaneously seek the clinic graduate of the Piracicaba Dental School -FOP / UNICAMP, and exhibiting at least four bleeding sites, including 2 sites with a probing depth (PD) between 5 and 6 mm and two sites PS 7 mm in uniradiculares teeth.

 Patients should have a minimum of 20 teeth.

 Will be excluded from relevant systemic disease carriers or antibiotics used in the 6 months preceding the study.

 All patients will receive oral hygiene instruction and will undergo a pre-treatment, which will be held supragingival sweeps and removal of plaque retentive factors.

 Patients will be divided into 2 groups (DB + DOX: Debridement + Doxycycline, test group and DB: only debridement, control group) of 20 patients who will receive the following treatments: periodontal debridement ultrasound for 45 minutes associated with the local administration of 1 mg microspheres containing doxycycline, or just mechanical debridement, for each selected site.

 Will be assessed the following clinical parameters: gingival index (GI) Plaque Index (PI), Bleeding on Probing (BOP), Position of the gingival margin (PGM), Probing Depth (PD) and Relative Clinical Attachment Level (RCAL).

 The microbiological evaluation will be made by means of polymerase chain reaction - real time ( "real time" - PCR) to detect bacteria: Porphyromonas gingivalis, Tannerella forsythia, Treponema denticola, Aggregatibacter actinomycetemcomitans and Prevotella intermedia.

 The enzyme immunoassay (LUMINEXMAGPIX) allow the detection of cytokine levels of GM-CSF, INF-, IL-10, IL-12, IL-13, IL-1, IL-4, IL-6, IL-8 and TNF-.

 The analysis of the proteolytic enzyme activity is accomplished by using zymography to assess MMP-8 and MMP-9.

 The described parameters will be evaluated at baseline, 45 and 90 days after the initial visit.

 The results are compared statistically by analysis of variance with repeated measures with 5% significance level.

