(thirdQuint)Registry for Patients With X-linked Hypophosphatemia.

 Methodology This is an international, multicentre, prospective, non-interventional, observational registry of patients with X-linked hypophosphatemia (XLH).

 The objectives of the registry is to collect natural history data of XLH to characterise the treatment, progression and long-term outcomes of XLH in both adult and paediatric patients.

 The registry will include patients with XLH independent of treatment regimen (unless participating in an interventional clinical trial) at the time of identification.

 Those patients participating in an interventional clinical trial will be approached to take part in the registry when their involvement in the clinical trial has ended.

 All eligible patients at the participating clinics will be asked to participate in the registry.

 - Informed consent will be obtained from adult patients.

 - Parental informed consent for the inclusion of a child will be obtained the child's legally designated representative in line with national guidance.

 - Assent will also be sought from children of applicable age in line with national guidance.

 In all cases the health professional responsible for enrolling the patient into the registry will assess the appropriateness of gaining assent from an individual at their discretion.

 After the patient or legally designated representative have signed the informed consent, the patient data will be recorded in the registry, including baseline, retrospective and prospective data.

 Data will be collected using a web-based Electronic Data Capture (EDC) system.

 A patient identification number will be automatically generated by the system upon enrolment.

 No pre-determined follow-up requirements will apply.

 However, physicians will be prompted to update patient data in the registry in relation to the patients' visits to the physician.

 Physicians will be reminded to update the registry at 12 months after the previous visit information was entered for a patient.

 For those patients who attend clinic at more frequent intervals as part of their standard care, data for these visits will be entered at the 12-month intervals with an option to add multiple dates.

 This is a prospective observational registry and no additional interventions other than standard clinical practice are required by the protocol.

.

 Registry for Patients With X-linked Hypophosphatemia@highlight

This is an international, multicentre, prospective, non-interventional, observational registry of patients with X-linked hypophosphatemia (XLH).

 The main objective of the registry is to collect data to characterise the treatment, progression and long-term outcomes of XLH in both adult and paediatric settings.

