(fifthQuint)Testing the Efficacy of Self-Generation Treatment Protocol.

 If self- generation can be successfully adapted and applied to a treatment program for individuals with MS, it has the potential to improve their rehabilitation and treatment by facilitating new learning and memory.

 In addition, if treatment and rehabilitation are successful and productive, it is expected that the application of self-generation strategy to improve learning/ relearning will help to improve the ability of individuals with MS to maintain their current lifestyles at home, work, and within the community.

 We expect that persons with MS who complete the proposed treatment will acquire the trained strategy, recognize the everyday situations in which the trained strategy could be applied and then map and adapt the trained strategy to real-world situations.

 Fourty participants with clinically definite MS and objectively documented impairment in verbal new learning will be included in the study.

 Participants will be randomly assigned to either the treatment group (n=20) or the control group (n=20).

 Participants will be enrolled only following an informed consent procedure, with the expectation of being able to participate for the full duration of the study (6 treatment sessions and two assessment sessions).

 All participants enrolled in the study will undergo pre and post treatment assessment to assess their levels of cognitive, emotional, and functional performance.

 Treatment for both experimental and control groups will consist of 6 individualized treatment sessions, 2 x per week for 3 weeks.

 Each session will last for approximately 45 minutes, and will include various memory tasks that will range from learning list of words to learning tasks related to everyday life.

 Participants in the control group will only be asked to perform the same memory tasks as the treatment group.

 The treatment for the experimental group will couple self-generated learning with awareness-training techniques, which are geared toward helping patients self-discover their performance strengths and limitations through integration of direct and personal experiences.

 Personal experience will be gained by practicing various memory tasks using self-generation strategy.

 This proposed self-generation program is expected to increase memory, task specific awareness and functional performance; ultimately improving quality of life and self-regulation.

.

 Testing the Efficacy of Self-Generation Treatment Protocol@highlight

Past research has shown that items self-generated by an individual, such as words or concepts, are remembered better than items that are simply read or heard.

 The current study seeks to demonstrate the effectiveness of using the principles of the generation effect in a treatment intervention to improve memory and functional performance in individuals with Multiple Sclerosis who have learning and memory difficulties.

The main purpose of the study is to conduct an experimental investigation on the effects of a self-generation strategy treatment, embedded within practice of various activities ranging from laboratory tasks (e.

g.

 words and concepts) to functional tasks (e.

g.

 activities of daily living).

 The treatment to be tested is geared toward helping patients selfdiscover their own strengths and abilities while using self-generation to be able to utilize it independently in everyday life situations.

 Design: The proposed pilot study is a randomized clinical trial.

 Participants: Participants will include forty (40) persons with MS, between the ages of 18 and 65, who demonstrate memory impairments.

 Half of the participants will receive the self-generation training while learning different types of tasks (experimental group) and half of the participants (control group) will be asked to learn the same information but will receive a conventional practice (e.

g.

 repetitions).

 Expected results: We expect that participants undergoing the self-generation-training intervention will show better memory performance, functional performance, quality of life, and satisfaction with treatment and life compared to participants in the control condition.

