(fifthQuint)Brain Activation During Accommodation to Painful Stimulation With FMRI.

 Background: Over the past 14 years, BOLD FMRI studies have non-invasively shown that pain activates a matrix of areas, but that this activation decays during stimulation, possibly reflecting the body's ability to "accommodate" to the stimulation.

 The majority of these use short applications of pain lasting 1 to 30 seconds.

 However, investigators are now using stimulations much longer than the periods that were typical a few years ago.

 The effect of signal decay on the activation maps generated by these longer tasks is not known.

 Because the signal change in many of the subcortical areas involved in pain processing is low, errors in analysis due to neglecting the signal decay may induce significant artifact.

 Materials and Methods: Using transcutaneous electrical nerve stimulation, 20 healthy volunteers will experience two different painful stimulations: a repeating 30-second long stimulation and a constant 2 minute stimulation.

 The brain activity for each will be determined and compared.

 In addition, the signal decay during each painful stimulation will be quantified and compared.

 Significance: Investigators are using longer stimulations periods in an attempt to understand how the brain processes "real- life" pain instead of the artificial on-off pattern of earlier studies.

 However, significant attention has not been paid to the possible effect of accommodation on the stimulus and how this may impact the activity pattern found.

 In addition, proof of activation of pain-control areas like the periaquaductal gray while inverse changes are occurring in pain-perceiving areas has not been sought.

 This study will address both of these issues with a single BOLD FMRI experiment.

.

 Brain Activation During Accommodation to Painful Stimulation With FMRI@highlight

Blood oxygen level dependant (BOLD) functional magnetic resonance imaging (FMRI) investigations of pain have provided substantial insight into the workings of the human brain.

 To date, however, the vast majority of studies have dealt with short painful stimulations.

 This work will expand the investigators knowledge of how longer stimulations are processed by comparing the activation pattern from a two minute painful stimulation with that of an 30-second painful stimulus.

 The investigators hypothesis that accommodation to the longer stimulation will be evident by either decreases in signal intensity in brain areas known to process pain, or by increasing activity in brain areas thought to be responsible for the modulation of painful perception.

