(fifthQuint)Evaluation of a Protocol of Pupil Dilation Before Laser-assisted Cataract Surgery.

 Femtosecond laser-assisted cataract surgery (FLACS) is a major surgical development that would allow systematization of surgery and even improved safety of the procedure.

 The development of this new surgical technique must now face certain obstacles, in particular (i) financial considering the extra cost generated by the use of the laser and (ii) technique due to the need to re-learn certain gestures and certain variations related to the laser procedure and more specifically the instability of the pupillary mydriasis (dilatation) during the actual surgery.

 The use of a systematic preoperative pharmacological mydriasis protocol should allow maximum intraoperative mydriasis to be maintained, allowing satisfactory surgery throughout the procedure.

 Several drugs or medical devices are now indicated in cataract surgery, but their effectiveness has not been specifically evaluated for the laser technique.

 This study could thus make it possible to validate or not a protocol of mydriasis that could make consensus in the future for the practice of FLACS.

.

 Evaluation of a Protocol of Pupil Dilation Before Laser-assisted Cataract Surgery@highlight

Laser-assisted cataract surgery is an innovative and growing procedure to improve the safety and results of modern cataract surgery.

 However, this technique faces to some obstacles: economics in the one hand due to the cost and time spent for the laser procedure before the conventional surgery, and technical in the other hand, especially due to some loss of pupil dilation during the surgery, which is highly important to ensure a perfect procedure.

 The present study aims at assessing a pharmacological protocol to maintain an accurate pupil dilation all along the surgery in order to improve the whole procedure.

