(firstQuint)Cupping in Osteoarthritis of the Knee.

 Cupping is a traditional therapy in many cultures of the world and is used to treat osteoarthritis of the knee.

 In this randomised trial we want to study the effect of pulsatile cupping in osteoarthritis of the knee compared to waiting list control.

 Pulsatile cupping is administered by a special cupping machine (HeVaTec) with silicone cupping glasses to the knee joint.

 Pulsatile pressure is generated by a pump that generates vacuum.

.

 Cupping in Osteoarthritis of the Knee@highlight

The purpose of this exploratory randomised trial is to study the effect of pulsatile cupping in osteoarthritis of the knee compared to waiting list control.

