(firstQuint)Study to Determine the Antibody Response to 500g G17DT in Treatment of Patients With Gastric Cancer.

 Another study, GC2, initiated prior to the start of this study investigated the appropriate dose and dosing schedule for G17DT in patients with Stage I-III gastric cancer.

 The highest dose tested in the GC2 study was 250 mu g.

 This dose was well tolerated but was not considered sufficiently immunogenic.

 Since tolerability had not constrained dosing up to 250 mu g, the GC5 study was designed to investigate a 500 mu g dose administered as a regimen of 0, 2, and 6 weeks.

.

 Study to Determine the Antibody Response to 500g G17DT in Treatment of Patients With Gastric Cancer@highlight

This study was designed to investigate the antibody response generated by a 500 mu g dose of G17DT in patients with gastric cancer.

