(fifthQuint)Plasma Rich Growth Factors in Venous Ulcers.

 An open, randomized, of parallel groups, and controlled clinical trial.

 Patients will be allocated on first come to one of the two treatment groups using a block random sequence generated by computer that will remain hidden from the researchers and patients until allocation.

 Experimental group: PRGF together with the corresponding dressing according to annex IV.

 Control group: Corresponding dressing according to annex IV.

 Both groups will be submitted to a cleaning, debridement, occlusive dressing and use of antibiotic if necessary in each visit.

 After signing consent form, and previously of randomization, patients will be submitted to a blood extraction where it will be determinate: Albumine (in g/dl), Hemoglobin (in g/dl), Hematocrit (in %), Creatinine (in mg/dl).

 If patients have data collected through previous analysis performed until 30 days before, it will not be necessary a new extraction.

 Patients will be also submitted to an initial valuation of: - medical antecedents: history of chronic venous insufficiency, previous medical treatments.

 - general state: dependence grade through Barthel index, mobility, ankle arm index.

 - ulcer characteristics:exudate, sing of location of ulcer, antiquity of ulcer, tunneling,infection, pain through a Visual Analogue Scale (VAS).

 - Anthropometric characteristics; Weight, height and Body Mass Index (BMI).

 Patients will go to the physician's consult every fours days (on Monday or Tuesday and Thursday or Friday).

 When one ulcer is closed, patient will go to physician's consult to confirm that it remains closed at seven and fifteen days.

 In both intervention and control groups, the bad evolution of ulcer with deterioration at least during four consecutive weeks, will obligate to ask a preferred inter-consultation with Vascular Surgery Service.

 In each visit the following variables will be measured: - Wound surface (in cm2) measured through PUSH scale (Pressure Ulcer Scale for Healing) belonging to GNEAUPP group (National Group to study and advice about pressure ulcers and chronic wounds).

 This variable will be measured in each visit.

 - Safety variable: Pruritus (Yes/No), Pain (through VAS scale), Sings of infection (Yes/No).

 If patient experience one adverse effect which according to judgment of nurse precludes its continuation into the study, the nurse will communicate it to physician who will discharge from study if it is necessary.

 All this will be collected in Case Report Form (CRF).

.

 Plasma Rich Growth Factors in Venous Ulcers@highlight

OBJECTIVES: Main objective: To evaluate the effectiveness of plasma rich in growth factors (PRGF) in the treatment of patients with venous ulcers.

 Secondary objective: To evaluate the safety of plasma rich in growth factors in treating patients with venous ulcers.

 DESIGN: Randomized, open clinical trial in parallel groups, controlled with conventional treatment.

 SAMPLE: Over age patients, of primary care centers of Vitoria, with at least one venous ulcers of 6 or more weeks of evolution and 0.

5-6 cm of diameter.

 INTERVENTION: 1-Experimental group: Autologous PRGF administrated once a week (day 1) + conventional treatment administrated twice a week (days 1 and 4)for 12 weeks of treatment, but in those cases where there has been no complete healing in this period, patients will continue the same management protocol to get it.

 2-Control group: Conventional treatment twice a week (days 1 and 4)for 12 weeks of treatment.

 Conventional treatment includes: Cleaning and debridement of the wound, the application of corresponding dressing, and using of antibiotic if necessary in each visit.

 STATISTICAL ANALYSIS:The primary outcome analysis was done by logistic regression.

 The crude model and the adjusted model (for confounding variables)will be built.

 The healing time of ulcers (in days) were analyzed using the Kaplan Meier survival analysis and the corresponding comparison using the log rank test.

