(fifthQuint)Stress Echo and Electric Impedance Tomography (EIT) Pilot Study.

 In 15 patients who routinely have to undergo stress echocardiography Electric Impedance Tomography (EIT) measurements are performed parallel to measurements of cardiac output at rest, low stress generated by a dosage of 10 mu g dobutamine, at peak generated by a dosage between 20-40 mu g dobutamine (individually)and at relaxation(pulse <100).

 Therefore prior to the examination a rubber belt with 16 integrated electrocardiographic electrodes is placed around the thorax at the fifth or sixth intercostal space, connected with an EIT device.

 EIT data are generated by application of a small alternating electrical current of 5mA and 50kHz and are stored and analyzed offline on a personal computer.

 Changes due to ventilation as well as changes due to perfusion will be measured by EIT.

 Cardiac output will be retrospectively compared to parameters of the EIT.

 EIT data are stored in a database and pseudonymized evaluated in relationship to routinely measured stress echocardiography data.

.

 Stress Echo and Electric Impedance Tomography (EIT) Pilot Study@highlight

Electric Impedance Tomography (EIT) is a technique based on the injection of small currents and voltage measurements using electrodes on the skin surface generating cross-sectional images representing impedance change in a slice of the thorax.

It is a radiation free, non- invasive and portable lung imaging technique.

 Impedance changes in lung ventilation as well as in lung perfusion can be shown.

 To investigate lung perfusion by EIT measurements, cardiac output measured by routinely undergone stress echocardiography at rest and stress are compared to parameters measured by EIT.

