(firstQuint)Efficacy and Safety Study of Rifaximin Vaginal Tablets in Bacterial Vaginosis.

 THIS IS A PHASE 2B, RANDOMIZED, DOUBLE-BLIND, PLACEBO CONTROLLED STUDY PLANNING TO ENROL 626 SUBJECTS AFFECTED BY BACTERIAL VAGINOSIS.

 PRIMARY ENDPOINT: TO COMPARE THE EFFICACY OF TWO DOSES (25 MG AND 100 MG) OF RIFAXIMIN VAGINAL TABLETS VERSUS PLACEBO IN SUBJECTS WITH BACTERIAL VAGINOSIS SECONDARY ENDPOINT: TO COMPARE THE EFFICACY OF TWO DOSES (25 MG AND 100 MG) OF RIFAXIMIN VAGINAL TABLETS VERSUS METROGEL VAGINAL IN SUBJECTS WITH BACTERIAL VAGINOSIS.

.

 Efficacy and Safety Study of Rifaximin Vaginal Tablets in Bacterial Vaginosis@highlight

THE STUDY HAS BEEN DESIGNED TO COMPARE THE EFFICACY OF TWO DOSES (25 MG AND 100 MG) OF RIFAXIMIN VAGINAL TABLETS VERSUS PLACEBO IN SUBJECTS WITH BACTERIAL VAGINOSIS