(secondQuint)Comparison of Two Different NCPAP Methods in Preterm Infants With Respiratory Distress Syndrome.

 Study Design NCPAP support was provided with continuous positive airway pressure, which was generated by a neonatal ventilator (SLE; Infant Flow System, Viasys Corp.

, USA) and infant flow-driver device (SLE; The respiratory parameter settings were a PEEP of 5-8 cmH2O.

 CPAP was stopped when PEEP 5 cmH2O and infants showed no signs of RDS with FiO2 0.

40, surfactant will be given as early rescue therapy by means of non-invasive method (by using a thin catheter - take care method- while spontaneous breathing continues) in order to keep target oxygen saturation between 90-95 %.

 The second dose of surfactant will be given 6 hours after the first dose by means on non-invasive method in order to keep target oxygen saturation between 90-95 % in case of FiO2 need is 0.

30.

 Non-invasive respiratory support failure is set as follows: - FiO2 of 0.

50 in order to keep oxygen saturation measured by pulse oximetry above 90 % and higher, - Apnea requiring more than 6 alerts in a 24 -hour period in 6 consecutive hours or more than 1 apnea requiring positive pressure ventilation, - Persistent acidosis; presence of pH 65 mmHg in two different blood gases drawn with an interval of at least 30 minutes or treatment-resistant metabolic acidosis, - Severe respiratory distress, - Pulmonary haemorrhage and cardiopulmonary arrest.

.

 Comparison of Two Different NCPAP Methods in Preterm Infants With Respiratory Distress Syndrome@highlight

is to compare introduction of two different NCPAP methods in terms of mechanical ventilation (MV) need (non-invasive respiratory support failure) and surfactant need within the first 72 hours of life in preterm infants with Respiratory Distress Syndrome (RDS) at 26-30 weeks of gestation.

