(thirdQuint)Bioequivalence Study of Amoxicillin-Clavulanic Acid 600 mg-42.

9 mg/ 5 mL Oral Suspension Under Fed Conditions.

 This was a single center, randomized, single-dose, open label, 2 - way crossover bioequivalence study to compare the rate and extent of absorption of a test amoxicillin-clavulanic acid versus Augmentin ES-600, a reference amoxicillin- clavulanic acid, under fed conditions.

 Prior to the study commencement, subjects were randomly assigned to a treatment in accordance with the randomization scheme generated by Anapharm.

 Subjects were confined to the Anapharm Clinical research Facility from at least 11 hours prior to drug administration until after the 12.

0 hour post-dose blood draw, in each period.

 The treatment phases were separated by a washout period of 14 days.

 A total of sixty-two (62) healthy adult subjects signed the study specific informed consent form and were confined for period I; of these subjects forty eight (48), (21 males and 27 females) were enrolled and dosed in the study; forty six (46) of these enrolled subjects completed the clinical phase of the study.

 Bioequivalence Study of Amoxicillin-Clavulanic Acid 600 mg-42.

9 mg/ 5 mL Oral Suspension Under Fed Conditions@highlight

The objective of this study was to compare the rate and extent of absorption of Ranbaxy Laboratories Limited, India, Amoxicillin-Clavulanic acid and GlaxoSmithKline, U.

S.

A.

 (Augmentin ES-600), amoxicillin-clavulanic acid, administered as a 1 x 5 mL (600 mg - 42.

9 mg) oral suspension, under fed conditions.

