(firstQuint)Oocyte Survival After Vitrification in an Open or Closed Device With Closed Storage.

.

 Donor sibling oocytes will be vitrified with two commercially available devices.

 The first device is closed vitrification with closed storage and the second device is open vitrification with closed storage.

 Oocyte acceptors receive oocytes from both devices.

 With the increase in cooling rate generated by the open vitrification (second device), we expect to get an increase in survival rate of 10%.

 Besides this, embryo quality will be assessed with oocytes obtained from both devices.

.

 Oocyte Survival After Vitrification in an Open or Closed Device With Closed Storage.

@highlight

The survival rate (and embryo quality) of donor oocytes with two commercially available devices.

