(fifthQuint)Effects of Antenatal Pelvic Floor Preparation Techniques for Childbirth.

 METHODS: Participants: Primigravidae women over 18 years old will be selected, from the 32th gestational week and wishing to have a vaginal delivery.

 Interventions: Pregnant women will be randomly allocated into three groups: perineal massage, vaginal dilator and pelvic floor muscles training.

 The technique should be practiced from the 34th week of pregnancy until the beginning of labor.

 Randomization will be done by a researcher who was not involved with the recruitment, assessment and treatment of the participants.

 All participants will undergo a clinical and functional assessment of the pelvic floor before the beginning of the technique practice, as well as a reassessment of these items and an assessment of perineal integrity between 45 and 60 days after delivery for a blind physiotherapist regarding the interventional procedures.

 Objective: To compare the effects of perineal massage, vaginal dilator and pelvic floor muscles training on the perineal integrity of primiparae women.

 Outcome: The perineal integrity will be verified by the presence or absence of perineal laceration as well as their characteristics observed immediately after delivery.

 Randomization: Participants randomization will be done from a sequence generated by a computer program.

 Blinding: The evaluative procedures will be done by a 'blinded' physiotherapist in relation to the intervention procedures and the randomization procedure by a researcher who was not involved with the recruitment, evaluation and participant's treatment.

 Discussion: The knowledge of the effects of antenatal pelvic floor preparation techniques on the perineal integrity and pelvic floor muscles function after delivery, will allow a better choice about which approach is the best to pregnant women to prevent perineal trauma.

.

 Effects of Antenatal Pelvic Floor Preparation Techniques for Childbirth@highlight

Perineal trauma during childbirth is an important etiological factor of various undesirable complications to women's health, with emphasis on pelvic floor dysfunction.

 Thus, methods that preserve the perineal integrity have been a challenge to practices among health professionals working in the gravid-puerperal cycle assistance.

 Despite the remarkable importance of beneficial effects of pelvic floor preparation prior to vaginal birth on prevention of perineal trauma, there are few studies in the literature that point which is the best method to be used to reduce the chances of perineal lesions.

 Therefore, there is need for more studies to compare existing methods.

 The objective this present study is to compare the effects of perineal massage, the vaginal dilator and training of the muscles of the pelvic floor to prepare the pelvic floor for vaginal birth on perineal integrity of primiparous.

 Primigravidae women are selected over 18 years, from the 32th gestational week and wishing to have a vaginal birth.

 Women will be randomly allocated into 3 groups: perineal massage, vaginal dilator and pelvic floor muscles training and should practice the technique from the 34th week of pregnancy until the time of delivery.

 All the women will be subject to clinical evaluation, functional assessment of pelvic floor and perineal integrity assessment prior to the beginning of the practice of the technique and between 45 and 60 days after childbirth.

