(fifthQuint)Statins for Oxidative Stress and Mitochondrial Function in Diabetic Polyneuropathy.

 Introduction Nerve dysfunction system in patients with diabetes is known as diabetic neuropathy and is considered as the most prevalent microvascular complication -up to 60%- in type 2 Diabetes Mellitus (T2DM) subjects.

 Diabetic polyneuropathy (DPN) comprise 70% of all cases.

 Its diagnosis is established by means of validated scores based on clinical features and abnormal nerve conduction studies (NCS).

 Pathophysiologic findings include loss of multifocal and focal nerve fibers secondary to axonal degeneration an segmental demyelinization, basically due to oxidative stress induced by chronic hyperglycemia, which leads to neural apoptosis.

 Other mechanisms involved in peripheral nerve injure is nitrosative stress induced by nitric oxide (NO).

 Ezetimibe diminishes cholesterol esters content in chylomicrons by reducing liver cholesterol intake which in consequence increases LDL uptake and plasma depuration; as monotherapy it reduces LDL-C by 17%.

 When combined with simvastatin, cholesterol reduction is potentially increased; furthermore, pleiotropic effects of statins include an increase on nuclear factor kappa B activity and amelioration of superoxide ions after 12 week treatment.

 Another hydroxy-methyl-glutaryl coenzyme A inhibitor, rosuvastatin, has an antioxidant effect by acting as free radical carrier diminishing mitochondrial and cellular lipid peroxidation (LPO) production.

 We conducted this study to evaluate the effect of ezetimibe/simvastatin and rosuvastatin on oxidative stress in patients with DPN.

 Methods Study design A randomized, double blinded, placebo controlled phase II clinical trial was performed in the Clinic and Experimental Therapeutics Institute, University of Guadalajara, Mexico.

 Subjects were assigned to three group treatments in blocks with a parallel sequence 1:1:1 through a randomized computer-based list, generated by a different researcher unaware of drugs given.

 Patients were divided to: control group that received placebo, ezetimibe/simvastatin and rosuvastatin as a daily single dose for 16 weeks.

 The selection period was performed from February 2012 to January 2013.

 We selected 5 non-randomized healthy subjects (HS) from a blood bank to compare the oxidative stress status.

 Study population Inclusion criteria were 18 years old, T2DM according to American Diabetes Association and DPN by Dyck et.

 al.

3 criteria, HbA1c 1/2L of serum where processed with a chromogen substance that reacts with malondialdehyde (MDA) and 4-hydroxy-alkenals (HNA), the absorbance measured at 586 nm, and results expressed in nmol/mL.

 Previous deproteinization of the samples, we performed a colorimetric for determining the concentration of NO with 85 mu L of serum (Nitric Oxide Assay Kit, User protocol 482650), with results expressed as pmol/mL.

 Total antioxidant capacity (TAC) was realized with 200 mu L of serum, to obtain values of millimole (mM) equivalent of uric acid (Total Antioxidant Power Kit, No.

 02090130, Oxford Biomedical Research(R)).

 Clinical and nerve conduction variables Neuropathic symptoms (NSS) and disability scores (NIS) described by Dyck, et.

 al.

 were obtained by physical examination and anamnesis.

 We also measured the latency, duration, amplitude and motor nerve conduction velocity from fibula, tibial, median and ulnae nerves, and sensitivity parameters from sural, median and ulnae nerves, as required by the American Association of Electrodiagnostic Medicine.

 Ethical considerations The study was approved by the Research and Ethics Committee of the Health Science University Center, University of Guadalajara, Mexico.

 Identification codes were assigned to each participant to guarantee patient confidentiality, and an informed consent form was signed before entering the protocol, according to national and international laws, and also as stipulated by the Helsinki Statements (http://www.

wma.

net/es/30 publications/ 10 policies/b3/17c.

pdf, accessed January 2011).

 Statistical analysis The sample size was obtained by a clinical study design formula taking in account a difference change of 0.

05 nmol/mL in LPO, 95% confidence interval, 80% potency, and two-tailed p standard deviation.

 Kolmogorov-Smirnov and Shapiro-Wilk tests were performed to determine the non-parametric distribution of variables.

 Friedman and Wilcoxon tests were realized for before and after measurements, and Kruskal-Wallis with Mann-Whitneys U as post-hoc analysis for between group comparisons.

 Qualitative variables were expressed as frequencies and percentages.

 Chi square test was used to evaluate differences in dichotomy variables before and after treatment, between group comparisons were determined by Fishers exact test and 2 as needed.

 Significance level was established with p value <0.

05.

.

 Statins for Oxidative Stress and Mitochondrial Function in Diabetic Polyneuropathy@highlight

Aims: To evaluate the effect of ezetimibe/simvastatin and rosuvastatin on oxidative stress and mitochondrial function in patients with DPN.

 Methods: We performed a randomized, double-blinded, placebo-controlled phase II clinical trial in adult patients with type 2 Diabetes Mellitus (T2DM) who had Diabetic Polyneuropathy (DPN) evaluated by composite scores and nerve conduction studies (NCS), HBA1C standard deviation (SD) or standard error of the mean (SEM), frequencies and percentages.

 Non-parametric analysis was used.

