(fifthQuint)Quantitative Characterization of Safe Irrigation for Ventricular Shunt Catheters.

 Primary Objective: To collect pressure and flow rate measurements during shunt revision surgeries in human patients.

 Pressure recordings of the injected fluid will be obtained using disposable off-the-shelf sterile pressure transducers (which are typically used for intracranial and arterial pressures monitoring) readily available in the operating room.

 First, the surgeon will attempt to flush the catheter using the Alcyone in-line Flusher device.

 If this fails, the surgeon may elect to attempt to flush using a standard syringe attached to the catheter.

 The flow rates will be measured by video, recording the syringe during the flushing maneuver, and then extracting plunger motion information by applying image processing on the acquired videos.

 In the event the recording equipment is not available (in that these operations are usually unscheduled and sometimes urgent), the same irrigation techniques may be used without the pressure recordings.

 Secondary Objective: To analyze the collected data and establish maximal allowable injection pressure and flow rate.

 The collected data segments for each patient will be analyzed and maximal values for pressure and the saline injection rate will be recorded in a spreadsheet.

 Inter-patient variation in the results, presumably due to different degrees of occlusion, will be statistically evaluated.

 We will also determine if any of the catheters which appear occluded in the operating room resume flow with the flushing maneuvers.

.

 Quantitative Characterization of Safe Irrigation for Ventricular Shunt Catheters@highlight

The objective of this pilot study is to perform a set of pressure and flow rate measurements in order to quantitatively characterize safe irrigation or "flushing" of a ventricular shunt catheter, a routine maneuver performed by a neurosurgeon during a shunt revision surgery.

 This maneuver involves injecting saline with a syringe to clear plugged shunt catheters.

 Based on data obtained in Stage I of the study, a device has been fabricated which provides the same small-volume pulse of fluid used by surgeons.

 In Stage II of the study, pressure and flow rate measurements generated by this specialized flusher device will be collected and measured.

