(fifthQuint)H-Type Hypertension Precision Medicine Trial.

 This study consists of 3 phases: Screening, Run-in Period, Double-Blind Treatment.

 Phase I: Screening(V0) Phase I takes place for about 2-10 days.

 The purpose is to obtain informed consent and make a preliminary assessment of the patient.

 At the first screening visit (V0), or prior to the official treatment visit, a clinical examination will be performed to determine the patient's clinical diagnosis and to determine eligibility for inclusion in the study.

 General demographic information and questions related to the inclusion/exclusion criteria of this study will be obtained.

 Additionally, this will be the time to discuss the impact of participant vacation/travel plans on adherence and compliance with the trial protocol.

 Before carrying out any research procedures, the purpose of the study and study procedures will be explained and the participant's informed consent will be obtained.

 Prior to the start of the Run-in Period, baseline data and efficacy evaluation data will be collected according to the study flow chart; blood and urine samples will also be collected.

 Phase II: Run-in Period (V1-V2) All eligible patients will begin a treatment of enalapril (10mg/d) for a 2-week open induction period, during which time other antihypertensive drugs may also be concurrently used.

 MTHFR C677T genotype will also be determined during this phase.

 The primary purpose of this phase is to assess participant compliance for following the enalapril treatment regimen as well as to observe the participant's tolerance to enalapril, so as to avoid admitting those participants with poor compliance or intolerance to enalapril into the double-blind treatment phase.

 Newly diagnosed hypertensives should be given enalapril during the Run-in Period and can be given other antihypertensive drugs at the clinician's discretion.

 For hypertensive patients currently using medication, if not currently using enalapril, the clinician should, based on the patient's medical condition, add or switch the patient's medication to enalapril.

 Phase III: Double-Blind Treatment (V2-V6) The third phase consists of 8 weeks of a randomized, double-blind treatment.

 Patients who remain eligible for participation in the study will first be stratified by gender and MTHFR C677T genotype (CC, CT, TT), for a total of 6 strata at the start of V2.

 Each of the 6 strata will then be randomized into 8 treatment groups: either enalapril only (10mg), or one of the other 7 treatment combinations with various doses of folic acid .

 During the 8-week double-blind treatment period, other antihypertensive drugs can be combined with the treatment drug to achieve blood pressure control; the patient will be followed-up every 2 weeks during the treatment period, and the treatment drug will be distributed at each visit.

 During this period, participants should continue to avoid taking medications that may interfere with the evaluation of treatment efficacy.

 For participants who complete the Run-in Period and are eligible to remain in the study, a randomized treatment allocation list will be generated using a stratified, blockwise, randomized approach by MTHFR C677T genotype and gender.

 This list will assign a unique study ID to every study participant.

 The ID corresponds to a specific treatment allocation; therefore, the ID assignment determines the treatment type the participant will receive.

 This study will use a two-level blinding procedure.

 The first level of blinding will generate a randomized sequence table corresponding each study ID to one of the eight different treatment groups.

 Each treatment will be given a treatment group code (from a to h) so that the actual treatment can not be identified from this table.

 The second level of blinding will denote the type of treatment that corresponds to each of the eight different coded treatment groups (a through h) that were generated from the first level of blinding.

 The randomized ID's will be generated by a statistical analysis group; the blinding program and all electronic documents regarding the level one and two blinding will be sealed in separate envelopes and protected by the sponsor.

 The seal cannot be broken before the trial officially undergoes the unblinding process.

 In addition, the research drug management center will maintain a copy of the treatment allocation list and will be responsible for encoding the treatment drugs and dispensing the medications to the participants based on the treatment allocation list.

.

 H-Type Hypertension Precision Medicine Trial@highlight

This is a multicenter, randomized, double-blind, controlled clinical trial.

 It aims to investigate the effects of different doses of folic acid on lowering homocysteine (Hcy) in patients with hypertension with different genotypes of MTHFR C677T and to determine a dose-response relationship.

 This study consists of 3 phases: Screening ( 2-10 Days ), Run-in period (2 Weeks), Double-Blind Treatment (8 Weeks).

 Follow-up visits will take place at the beginning of both the Run-in Period and the Double-Blind Treatment Period, and at the end of the 2nd, 4th, 6th, and 8th weeks.

 No medications that could affect the assessment of efficacy may be taken during any stage of the study.

