(fifthQuint)Magnetocardiography (MCG) in the Diagnosis of Chest Pain Syndrome.

 Cardiomagnetism refers to the detection, analysis and interpretation of the magnetic fields generated by the electrical activity of the heart.

 The peak value of the magnetic fields of the heart is more than a million times smaller than the Earth's magnetic field.

 A major breakthrough in the capability of measuring such small fields came with the invention of the SQUID (superconducting quantum interference device) in the late sixties.

 The first magnetocardiograms (MCGs) measured with the SQUID were recorded by Cohen et al.

 in 1970 (1).

 These earlier measurements were performed in very expensive magnetically shielded rooms, initially utilizing only one or two SQUID probes.

 In the eighties this technology was tested in several laboratories creating a magnetic field map by moving one SQUID sequentially above the chest to create an image of the whole hearts magnetic field.

 These maps were then attempted correlated with various pathologies (2,3).

 Since then the technology has been greatly improved and several multichannel machines are in use across the world for research purpose for arrhythmia localization and ischemia detection.

 However, at present time, only one company (CardioMag Imaging) has developed a machine that operates outside a shielded room.

 The CardiomagImaging (CMI) Magnetocardiograph (MCG) is capable of noninvasive recording of magnetic fields arising from the electrical activity of the heart with very high spatial and temporal resolution.

 The temporal trace of the MCG is analogous to an ECG, and, similarly, can be recorded in multiple leads.

 This MCG device has been specifically developed for the general purpose (outside shielded room) of non-contact, non-invasive diagnostics of ischemia.

 The CMI MCG device has been approved as safe for patients.

 It is FDA approved for the noninvasive detection and display of the heart's magnetic field created by the electrical currents, and is awaiting FDA approval for the detection of ischemia in chest pain patients.

 A similar SQUID technology utilized in magnetically shielded rooms has already been FDA approved for localization of epileptic focus.

 When utilized in this matter it is referred to as MEG (magnetoencephalogram).

 Several abstracts have been presented primarily at meetings on Biomagnetism, that confirm the safety and indicate the efficacy of the MCG for the detection of ischemia.

 In particular, it has been suggested that the resting MCG is capable of detecting ischemia in patients with chest pain, when the 12-leads ECG is normal (4,5,6).

 However, this has not been tested in larger prospective blinded studies.

 Cedars-Sinai Medical Center Non-invasive Cardiac Laboratory will be the first center in the US evaluating the CardioMag Imaging MCG in a clinical environment for the detection of ischemia in an acute coronary syndrome patient population.

 Patients will be enrolled in a similar protocol at Johns Hopkins Medical Center, Baltimore, Mayo clinic, Rochester, and at Klinikum Hoyerswerda, Germany.

 The early detection of ischemia (before Troponins become positive) with high negative and positive predictive values may prove cost effective and decrease risk by improving prompt treatment and triage to higher or lower grade monitoring at time of hospitalization.

.

 Magnetocardiography (MCG) in the Diagnosis of Chest Pain Syndrome@highlight

The purpose of this research study is to evaluate a better way of diagnosing heart artery disease, heart attack and damage to the heart muscle early on.

 Currently, it often takes several hours after admission before lab tests will show that there has been any damage to the heart muscle.

 Although the standard electrocardiogram is quick and non-painful it may miss many cases of significant coronary heart disease.

 The investigators are proposing that a new entirely non-contact tool, the Magnetocardiograph (MCG), with high accuracy is able to predict the presence of significant coronary heart disease early on before other studies become positive.

 The investigators hope by this that the investigators can develop an algorithm for better triage and management of patients with chest pain.

 This research study is designed to test the effectiveness of the investigational use of the Magnetocardiograph (MCG) that has been approved by the U.

S Food and Drug Administration (FDA).

 While the MCG used in the study is FDA-approved as a tool for the non-contact measurement and display of the magnetic fields of the heart generated by the electrical currents, it is not yet approved for the specific diagnosis of heart artery disease (ischemia).

