(fifthQuint)Effect of Deep Neuromuscular Block (NMB), Inhalation or TIVA on Pneumoperitoneum.

.

 Background and rationale The value of administering a deep neuromuscular block (NMB) to reach a post-tetanic count (PTC) of 0.

50 mu g/kg/min; sevoflurane > 1 MAC and deep neuromuscular block (rocuronium given with PTC 7 to an end tidal CO2 below 35 mmHg to prevent diaphragmatic activation.

 A verres needle will be placed minimum 15 minutes after induction.

 If the surgeon is not able to place the verres needle in two attempts, every patient will be given a rocuronium bolus of 0.

6 mg/kg IBW and the surgeon is asked after 5 minutes to repeat the trocar positioning.

 This will be noted as a failure to position the verres needle and to inflate the abdomen.

 When the abdomen is inflated the first trocar is placed and the positions of the trocar and gastric tube verified, and the stomach confirmed to be empty.

 The first abdominal pressure volume relation (APVR) will be measured using the following procedure by the surgeon: 1.

 The abdomen is deflated of all air by manual palpation of the abdomen and turning the trocar.

 The abdomen is re-inflated successively to 0.

5, 1, 1.

5, and 2 liters (IAV), and, at each volume, the intra-abdominal pressure (IAP) is measured while inflation is stopped.

 A maximum pressure of 15 mmHg is used.

 The lowest IAP or end expiration value is taken.

 This allows the drawing of the first APVR, the calculation of the E, PV0, and inflated volume at 15 mmHg.

 2.

 At the end of insufflation, the insufflator is stopped and the insufflation line is closed with a clamp.

 The IAP is recorded while pressure stabilizes.

 If no stabilization is achieved in 15 seconds, a leak is possible and the patient is not included in the study or the step-wise inflation is repeated after the leak is closed.

 Breathing against the ventilator or pressing is diagnosed when the IAP rises 5 mmHg above the set pressure not by a surgical act, when capnography shows irregularities in the waveform, or when the respiratory rate is higher than the set value.

 All remaining patients will be randomly assigned to three groups.

 A randomization number will be generated by the secretary of anesthesia at the moment of the patient's enrollment, using a random number generator.

 The anesthesiologist will be informed of the number when ready to prepare the drugs available from the pharmacy.

 The anesthesiologist will not be blinded (i.

e.

, he/she will know what drug he/she gives), because the administration routes are different: iv infusion, iv bolus, or inhalation.

 The surgeon and OR nurses will be blinded to the drugs used as iv infusion and bolus will always be given.

 Group A: A bolus of remifentanyl 2 mu g/kg IBW (0,2 ml/ 10 kg IBW) will be given and followed by 10 - 50 ug/kg IBW/h remifentanyl infusion (1 - 5 ml / 10 kg IBW / h).

 The propofol and dexmedetomidine infusion will be continued but adapted in dose when needed after the measurements.

 Group B: Desflurane inhalation at 1 MAC N2/O2 will be started with a fresh gas flush of the ventilator ( using et tidal control function) until the end tidal concentration reaches 1 MAC while the propofol infusion is stopped.

 The Ketamine Lidocaine Dexmedetomidine infusion is continued.

 Group C: A bolus dose of rocuronium 1 mg/kg IBW will be given while the propofol and Dexmedetomidine infusion is continued.

 After the above drugs are administered, there will be a waiting period of 5 minutes while the abdomen remains deflated in all groups.

 The BIS value should stay below 40% in all groups until the second APVR is measured, using the same setup as the first measurement.

 After the second APVR measurement the pressure needed to reach 4 liter is calculated and the insufflator is set to this value with a maximum of 15 mmHg in every patient.

 If during the second APVR the patient presses or breathes against the ventilator this will be noted as a failure to measure the APVR.

 A dose of rocuronium 1 mg/kg IBW is given followed by an infusion to keep PTC < 4.

 The anesthesia is continued with propofol/remifentanyl/Dex in group A, with sevoflurane/Dex in group B, and with Propofol/Dex/Rocuronium in group C.

 A bolus of sufentanil can be added in any patient after the two APVR measurements, at the discretion of the anesthesiologist.

 The surgeon is asked if he has sufficient workspace to reach all places he need to operate.

 He is asked to grade this on a scale of 1 to 5, with 5 excellent and 1 impossible.

 If the grade is less than 3 and patient didn't get yet any NMB until that time a bolus of rocuronium 1 mg/kg IBW is given.

 The NMB will be kept in these patients at train of four (TOF) = 0 and PTC < 4 until release of the pneumoperitoneum.

 A reversal with 4 mg/kg sugammadex will be given before awakening the patient.

 Any inadvertent event will be noted.

 TOF monitoring will be used in all patients to verify when and how deep NMB is given and to verify that sugammadex returns the TOF to a minimum of 90%.

 An external statistical group revealed that an enrollment of 12, 14 and 16 patients in the first, second and third group would be sufficient.

 The difference between the three groups is due to the fact that a comparison is needed between NMB and the other drugs, not between remifentanyl and sevoflurane.

 A two way Anova will be used to evaluate the different effect of remifentanyl, sevoflurane versus rocuronium on the abdominal workspace (pressure needed to achieve 4 l) and on the surgical incidence of having an insufficient workspace.

 ( 2 independent variables, three conditions).

 Effect of Deep Neuromuscular Block (NMB), Inhalation or TIVA on Pneumoperitoneum.

@highlight

The objective of this study is to compare the value of deep neuromuscular block (NMB) (using rocuronium) in laparoscopy versus high dose opioids (using remifentanil) or 1 mean alveoalr concentration (MAC) inhalation (using sevoflurane) for the surgeon.

 The study hypothesis is that laparoscopic workspace is larger when using rocuronium versus opioids or inhalation.

 Laparoscopic workspace is measured as the abdominal compliance and the pressure at volume zero (PV0) using the abdominal pressure volume relation.

 Three points allow to calculate the abdominal compliance and the PV0.

