(fifthQuint)A Study of AdCh63 AMA1 Alone and With MVA AMA1.

 AMA1 is a type I integral membrane protein.

 It is produced by mature P.

 falciparum schizonts in infected erythrocytes AMA1 has become a leading candidate vaccine antigen.

 This is based on several facts, most notably that in several field studies an association was found between antibodies to the ectodomain of AMA1 and protection against clinical malaria.

 Also, in the Gambia, presence of antibodies to AMA1 and MSP-1 has been shown to enhance clearance of chloroquine resistant parasites in vivo.

 There are a number of trials currently ongoing in Oxford which are aimed at examining a simian adenovirus as a delivery vehicle and liver and blood stage malaria antigens as inserts.

 AdCh63 is currently in use with the MSP-1 insert, a blood stage antigen, in a phase I dose escalation clinical trial in Oxford (VAC037 / GTAC 166).

 The trial design includes AdCh63 MSP-1 administered alone and with MVA MSP-1 as part of a heterologous prime boost schedule, with sporozoite challenge of 3 volunteers in the higher dose group.

 At the most recent interim analysis, AdCh63 MSP-1 demonstrates an excellent safety profile.

 Also, AdCh63 is currently in use with the ME-TRAP insert, a liver stage antigen in a phase I dose escalation clinical trial in Oxford, (VAC033 / GTAC133) and a phase I/IIa trial with sporozoite challenge (MAL034 / OXREC: 09/H064/9).

 AdCh63 ME-TRAP has been administered alone and with MVA ME-TRAP as part of a heterologous prime boost schedule at various doses with excellent safety and immunogenicity to 87 volunteers at time of interim analysis.

.

 A Study of AdCh63 AMA1 Alone and With MVA AMA1@highlight

This is an open label phase I study, to assess the safety of a novel malaria vaccine, AdCh63 AMA1, simian adenovirus encoding Plasmodium falciparum blood stage antigen, Apical Membrane Antigen -1.

 All volunteers recruited will be healthy adults.

 They will be primed with various doses of AdCh63 AMA1 administered intramuscularly.

 Some of the volunteers will receive a booster vaccination with MVA AMA1 administered via intramuscular route.

 Safety data will be collected for each of the eight regimens.

 Secondary aims of this study will be to assess the immune responses generated by each of these regimes.

