(fifthQuint)Impact of Head of Bed Elevation in Symptoms of Patients With Gastroesophageal Reflux Disease.

 PROBLEM STATEMENT Gastroesophageal reflux disease (GERD) is a clinical condition characterized by troublesome symptoms and medical complications as a result of reflux of gastric contents into the esophagus.

 GERD is diagnosed in 4% of primary care outpatient visits and the disease prevalence in Latin-America reaches 12-31%.

 Nocturnal symptoms have been found in 74% of patients with GERD and are a cause of significant quality of life impairment, when compared with general population and patients with GERD and daytime-only symptoms.

 Sleep interference secondary to nocturnal retrosternal burning has been associated to lower work productivity, even in patients being treated with proton pump inhibitors (PPI).

 Due to several physiological factors such as lack of conscious perception of symptoms, reduced salivation and a lower frequency of nocturnal swallowing, a significantly longer acid exposure overnight has been associated to the emergence of complications like esophagitis, more extra-esophageal symptoms and other illnesses such as asthma.

 As a low-cost non pharmacological anti-reflux treatment for GERD, head of bed elevation (HBE) is nowadays a moderate-strength recommendation with low level of evidence.

 Clinical impact of this measure in patients with night-time symptoms remains unknown, due to inconsistent results and methodological limitations among different clinical trials; most of which were performed before the widespread use of proton pump inhibitors in clinical practice.

 Evidence from several non-randomized studies suggest that HBE could reduce esophageal acid exposure time and could decrease GERD symptoms; however, another study found no significant differences in those same outcomes.

 On the other hand, all randomized controlled clinical trials published this far show inconsistent results.

 A study published before widely accepted clinical use of PPI, revealed significant clinical and endoscopic improvement with HBE in patients with GERD and grade C-D esophagitis, when compared to controls.

 In contrast, a multi-centre clinical trial found no difference in symptom score or antacid use among groups allocated to HBE and control group.

 All cited studies have methodological limitations and heterogeneity in outcome assessments, which makes difficult conducting a meta-analysis with these data.

 No published studies evaluating impact of HBE in quality of life or work productivity were found.

 SAMPLE SIZE CALCULATION Sample size was estimated based on the hypothesis that HBE would produce a difference of at least 10% in RDQ and SF-36 scores.

 Effect size (Cohen d) was calculated as 0,49, keeping in mind an RDQ mean and standard deviation of 3,31,0 previously found in Spanish population with symptomatic GERD.

 An SF-36 mean and standard deviation of 56,920,3 reported in Italian population in medical therapy with PPI were also taken into account.

 The minimally important difference selection was chosen based on the assumption that any difference smaller than 10% would have no clinical relevance.

 Based on this data, 52 patients per group would yield a power greater than 80% for detection of a minimally important difference as large as or larger than 0,6 points in RDQ questionnaire (range: 1 to 6) and 10 points in SF-36 questionnaire (range: 0 to 100).

 Finally, estimated sample size was incremented by 20% to avoid that eventual losses of follow-up may alter study power.

 Therefore, final sample size was 124 patients, 62 patients per group.

 DESIGN AND CARVING OF WOODEN PRISMS 124 prisms of withered pine tree wood with dimensions 20x18x18 cm will be carved from 9 logs of 300x20x20 cm at Aserrio San Ignacio Ltda.

 production plant, located in Soacha, Cundinamarca.

 Given it is an industrial process of chainsaw cutting and wood planing, a quality control will be implemented consisting of verification of prism stability while lying on the floor, and the mean height in millimeters of every prism will also be measured and registered.

 Unsteady products or those with atypical mean heights, defined as a height either exceeding percentile 75 + 1,5 times interquartile range or below percentile 25 - 1,5 times interquartile range, will be discarded and not used during the study.

 After exclusion of defective prisms, n groups of wooden prism pairs according to mean height in millimeters will be formed and every group will be given a random digit generated by computer.

 Afterwards, every random digit of prism groups will be sequentially assigned to a consecutive HBE-allocated patient number, in such a way that every consecutive patient number (among those allocated to HBE) will be linked randomly to a preset known prism height.

 This additional randomization procedure involving prisms according to their mean height, is planned due to the impossibility to guarantee that prism height will be identical with a precision of 1 mm, keeping in mind that products will be cut with chainsaw and will be planed as part of an industrial process.

 RANDOMIZATION A random binomial number list (zeroes and ones) will be generated with the statistical software SPSS 16.

0 for Windows and the list will be used for allocation of 124 patients between intervention and control groups in a 1:1 proportion.

 Each one of the 62 pairs of wooden prisms will be marked with a consecutive number coming from an HBE-allocated patient and the prisms will be stored keeping the marked number out of reach from the sight of the researcher in charge of patient recruiting.

 Patients that meet the inclusion criteria, have no exclusion criteria and who give written informed consent, will be assigned a consecutive number during their outpatient visit according to their order of inclusion in the trial.

 These participants will be randomized to either HBE or control group in the moment that a member of the research team verifies, among the stored prisms, the existence of a prism pair marked with the same number as the consecutive number assigned to the patient.

 In the case that this pair does exist, then the patient will take home that pair of wooden prisms and use them during the first period of the trial according to spoken and written instructions to be given at that moment.

 On the contrary, if a pair of wooden prisms marked with the same consecutive number as the patient, does not exist, then it will be understood that the study participant has been allocated to control group during the first period of the trial.

 The member of the research team who verifies the storehouse of wooden prisms will not be in charge of confirming inclusion and exclusion criteria and will not assign consecutive numbers to patients during outpatient visits.

 ALLOCATION CONCEALMENT The researcher in charge of confirming inclusion and exclusion criteria, fulfilling the Basic Data Formulary and providing the patient with the Informed Consent Format, will not be aware of the allocation sequence order until these 3 documents have been applied to the participant and a consecutive number has been generated according to their order of inclusion in the trial.

 After that, a member of the research team in the prism storehouse will verify the existence of a prism pair marked with the same number as the consecutive number assigned to the patient, and only in that point allocation status of the participant will be known.

 CROSS-OVER After allocation has been completed, patients in the intervention group will receive a pair of numbered wooden prisms with dimensions 20x18x18 cm along with written instructions about the correct use of the intervention.

 The patient must sleep with HBE during 6 weeks and both RDQ and SF-36 questionnaires will be applied again at the end of this first period while the participant is still sleeping with HBE.

 Afterwards, a washout 2 week period follows in which the participant sleeping with HBE will stop using it and will return the pair of wooden prisms to the researchers.

 After washout period has ended and both RDQ and SF-36 questionnaires have been applied again, patients allocated to the control group during the first period of the study will receive a random pair of prisms and will be instructed to use the prisms for sleeping with HBE during a second period of 6 weeks.

 Meanwhile, participants initially allocated to the HBE group will be followed as a control group in this second period of the study.

 BLINDING Because HBE is not susceptible to double-blinding, patients allocated to the intervention group will always be aware of the group they belong to.

 However, the researcher in charge of statistical analysis of data and writing the results report will work with random-generated alphabetical group codes for masking the intervention in each one of the periods of the trial.

 FOLLOW-UP After participant allocation, telephonic follow up will be made during both periods of the trial with a frequency that is dependent on the intervention group of the patient in that period.

 Participants in the HBE group will be called weekly for 2 weeks, and then will be called biweekly for a month, until each period of 6 weeks has ended.

 In contrast, patients in the control group will be called every three weeks along each period.

 With the purpose of verifying both HBE adherence and correct use of wooden prisms, every participant will be asked to send a photograph of the bed head legs during the follow-up telephone call.

 The photograph will be received by the researcher via e-mail or smart-phone and will be encoded and saved in a hard disk.

 At the end of the first period, RDQ and SF-36 questionnaires will be applied and researchers will store the returned prisms during washout period.

 When washout period has ended, RDQ and SF-36 questionnaires will be applied again in order to be sure of the absence of any carry-over effect in the group initially allocated to HBE.

 Finally at week 14, RDQ, SF-36 and Patient Preference questionnaires will be administered to complete study ending outcome assessments.

 STATISTIC ANALYSIS PLAN Quantitative and qualitative variables collected with Basic Data Format, RDQ, SF-36 and Patient Preference questionnaires will be typed in a Microsoft Excel 2007 database.

 Intervention groups will be masked with an alphabetical code provided by an independent collaborator who will not be involved with data analysis or report writing.

 For statistical processing, database will be imported into SPSS 16.

0 for Windows and descriptive statistics will be generated for each variable.

 Statistically significant differences will be searched for categorical data using the Chi-square test and normality will be tested for numerical continuous variables using the Shapiro-Wilk test.

 For normally distributed continuous variables, statistically significant differences will be searched for by using unpaired Student's t test.

 Alternatively, for not normally distributed variables a Wilcoxon signed rank test will be applied.

 For complementary processing of primary outcome and secondary outcome quality of life, score difference between periods will be transformed into a binomial variable and a McNemar test will be applied.

 Differences with one-tail p<0,05 will be accepted as statistically significant.

 Subgroup analysis will explore differences stratified according to age group, sex, ethnic group, BMI, comorbidities, cups of coffee per day, pharmacological adherence, and length and severity of symptoms.

.

 Impact of Head of Bed Elevation in Symptoms of Patients With Gastroesophageal Reflux Disease@highlight

BACKGROUND: Gastroesophageal reflux disease is a very frequent clinical condition and nocturnal symptoms are a cause of quality of life impairment, poor sleep quality and absenteeism.

 Head of bed elevation, as a low-cost non pharmacologic anti-reflux treatment is nowadays recommended, but its clinical impact in patients with nocturnal symptoms remains unknown due to inconsistent results and methodological limitations among different clinical trials, most of which were performed before the widespread use of proton pump inhibitors in clinical practice.

 HYPOTHESIS: Head of bed elevation is a useful treatment for patients with gastroesophageal reflux disease and nocturnal symptoms, and has a positive impact in quality of life in these patients.

 STUDY OBJECTIVE: To assess the effectiveness of head of bed elevation for treatment of patients with gastroesophageal reflux disease and nocturnal symptoms, and to determine the impact of this intervention in quality of life of these patients.

 METHODS: Randomized single-blind single-centre controlled clinical trial with a 2x2 cross-over design.

 A sample of 124 patients attending to the outpatient gastroenterology unit at Clinica Fundadores in Bogota city, who meet the inclusion criteria and have no exclusion criteria will be selected to participate.

 Included patients will be randomized to raise the head of bed with standard 20 cm-height wooden blocks or to sleep without bed inclination during the first 6 week period.

 After a 2 week washout period, allocation will be crossed and participants will be followed again during a second 6 week period.

 During the trial, every patient will receive standard pharmacological treatment with a proton pump inhibitor and/or sodium alginate.

 After allocation concealment, the researchers in charge of statistical analysis and reporting results will be blinded for the non pharmacological intervention under study.

 Primary outcome is a significant symptom change according to Reflux Disease Questionnaire (RDQ) validated form.

 Secondary outcomes include impact on quality of life according to Short Form 36 (SF-36) validated questionnaire, patient preference and adverse events of non-pharmacological intervention.

 Statistical analysis will be carried out with the Statistical Package for Social Sciences (SPSS) 16.

0 for Windows.

 Differences with a p<0,05 will be accepted as statistically significant.

