(fifthQuint)Effects of Photobiostimulation on Endothelial Function in Healthy.

 Detailed Description: The endothelial cell layer is responsible for the control of vascular homeostasis, a process mediated by vasoconstricting and vasodilatory substances.

 The principal endothelium-dependent vascular dilator is nitric oxide (NO), and the reduction of its synthesis or bioavailability is the main cause for the development of endothelial dysfunction.

 The use of photobiostimulation may be beneficial in several clinical situations.

 At the endothelial level, the photostimulatory action on vascular endothelial growth factor, NO secretion, number of capillaries and proliferation of endothelial cells is outstanding.

 It has also been shown an increase in glutathione levels, antioxidant effect and angiogenic potential, which shows a potential vascular effect, and consequently, an improvement in endothelial function.

 The objective of this study is to evaluate the effects of photobiostimulation on the arterial endothelial function of healthy individuals.

 The study design will be a cross-over trial and the sample will be composed of 12 healthy subjects selected by the eligibility criteria, and randomly randomized according to the order of intervention of the groups.

 The hypothesis is that at the end of the irradiation protocol with photobiostimulation an increase in endothelial function and blood markers of endothelial function occurs, and no tissue temperature variation.

 The primary objective is to evaluate the effects of photobiostimulation on the arterial endothelial function of healthy individuals.

 The secondary objectives are: 1) To evaluate the effects of photobiostimulation on blood markers (hemogram) and endothelial markers (cGMP and L-arginine), and Nitric oxide (nitrite and nitrate).

 2) To analyze associations between markers and metabolites with endothelial function due to the effects of Photobiostimulation.

 3) Analyze the local temperature before and after photobiostimulation.

 4) Analyze the local temperature before and after the measurement of Endothelial function.

 5) Evaluate possible associations between blood and endothelial markers, nitric oxide pathway metabolites and Endothelial function with local temperature.

 6) To compare the effects of energy doses of photobiostimulation on endothelial function, blood and endothelial markers, and metabolites of the nitric oxide pathway.

 The research will be developed in room 709 of the Laboratory of Physiotherapy in building II, UFCSPA and, for randomization, the simple technique will be used through numbers generated by a freely available software.

 The generation of the sequence of numbers will be done by blind researcher, after selection of the individuals by the eligibility criteria.

 Individuals will be randomly assigned to: group 1 (energy dose of 2J), group 2 (energy dose of 4J), group 3 (energy dose of 6J), and group 4 (placebo).

 The normality of the data will be evaluated by the Shapiro-Wilk test.

 Data with symmetrical distribution will be presented as mean standard deviation, and data with asymmetric distribution as median and interquartile range (P25 - P75).

 The baseline characteristics of the patients will be compared by Student's t test or Mann-Whitney when the distributions are parametric or non-parametric, respectively.

 The categorical variables will be compared by the Chi-square test.

 Variance Analysis (ANOVA) will be used for repeated measures for pre and post-intervention data analysis, or the Mann-Whitney test (asymmetric distribution), followed by Bonferroni post hoc.

 The Pearson or Sperman correlations will be used for possible association between the analyzed variables.

 Statistical significance of 5% (p <0.

05) will be observed.

.

 Effects of Photobiostimulation on Endothelial Function in Healthy@highlight

The endothelial cell layer is responsible for the control of vascular homeostasis, a process mediated by vasoconstricting and vasodilatory substances.

 The principal endothelium-dependent vascular dilator is nitric oxide (NO), and the reduction of its synthesis or bioavailability is the main cause for the development of endothelial dysfunction.

 The use of photobiostimulation may be beneficial in several clinical situations.

 At the endothelial level, the photostimulatory action on vascular endothelial growth factor, NO secretion, number of capillaries and proliferation of endothelial cells is outstanding.

The objective of this study is to evaluate the effects of photobiostimulation on the arterial endothelial function of healthy individuals.

 The study design will be a cross-over trial and the sample will be composed of 12 healthy subjects selected by the eligibility criteria, and randomly randomized according to the order of intervention of the groups.

 The hypothesis is that at the end of the irradiation protocol with photobiostimulation an increase in endothelial function and blood markers of endothelial function occurs, and no tissue temperature variation.

 The research will be developed in room 709 of the Laboratory of Physiotherapy in building II, UFCSPA.

 Individuals will be randomly assigned to: group 1 (energy dose of 2J), group 2 (energy dose of 4J), group 3 (energy dose of 6J), and group 4 (placebo).

