(thirdQuint)A Study to Assess the Safety of Hep C Vaccine Candidates in HIV Seropositive Individuals.

 Hepatitis C (Hep C) is a common infection.

 Worldwide, over 180 million people are infected.

 Hep C is a blood borne viral infection spread through direct contact with the blood of an infected person.

 People with Hep C frequently have no symptoms and infection can lead to fibrosis (scarring of the liver), liver failure and cancer.

 Infection with the Hep C virus (HCV) progresses more rapidly to liver damage in Human Immunodeficiency Virus (HIV)-infected individuals.

 Researchers at the University of Oxford have developed a novel candidate vaccine against HCV ('NSmut').

 This vaccine has been inserted into the carrier viruses Chimpanzee Adenovirus 3 (AdCh3) and modified vaccinia virus Ankara (MVA), both of which have excellent safety records and have been previously tested in people.

 However, the objective of this study is to use exploratory immunological assays to assess whether vaccines for Hep C can induce immune responses in HIV positive individuals that are similar in strength to those in healthy volunteers.

.

 A Study to Assess the Safety of Hep C Vaccine Candidates in HIV Seropositive Individuals@highlight

This study is aimed at assessing the safety of candidate Hepatitis C (Hep C) vaccines AdCh3NSmut1 and MVA-NSmut when administered to Human Immunodeficiency Virus (HIV) seropositive individuals.

 This study also aims to assess the cellular immune response generated by these vaccines when administered as mentioned above.

