(fifthQuint)Sickle Cell Disease and Endothelial Progenitor Cells (EPCs).

 In the bone marrow, a reservoir of EPCs does exist, which can be mobilized into circulation when needed, for example during ischemia, a situation which may occur in sickle cells disease.

 These cells are able to reach distant targets and to participate to the neovascularisation processes necessary for tissue and vascular healing.

 Conversely, abnormalities of the maturation, mobilization or homing processes would contribute to the thrombotic and ischemic risks associated to ischemia.

 Furthermore, vascular stress such that encountered in SCD leads to the detachment of endothelial cells from the vessels.

 The number of detached mature circulating endothelial cells (CEC) seems to be related to vascular hurting.

 The balance between EPCs and CECs would thus be informative of the vascular condition in patients during the progression of the disease.

 A relatively high level of EPCs would indicate a prominence of a healing neoangiogenesis or vasculogenesis process, while increasing levels of CECs would be indicative severe progression of the disease.

 Our studies and those published by others indicate that the number of EPCs in peripheral blood is tightly regulated.

 Indeed, mediators of inflammation could participate to EPC mobilization and to their recruitment to the diseased areas by local activation of the vascular endothelium.

 In this context, sickle cells disease provokes transient occlusion episodes, leading to a situation of chronic ischemia in different organs, sometimes with acute episodes.

 This suggests defect of the maintenance of the vascular integrity in these target organs.

Within this project, we will compare the number of EPCs and CECs in 25 SCD patients and 25 normal individuals in search of a correlation with the severity of the disease.

 SCD patients with potential confounding factors that may alter endothelial physiology (drugs, blood transfusions, hydroxyurea therapy) are excluded.

 In addition, we will analyse and compare in culture and in vivo the phenotypic and functional characteristics of EPCs obtained from patients and controls.

 We have a working bilateral hypothesis, since we do not know whether SCD subjects have appropriate angiogenic balance (high EPCs/CEC ratio with functional EPCs) to face the situation of endothelial activation and tissue hypoxia induced by SCD.

 Therefore, we will quantitatively and qualitatively study several distinct biological steps:1.

 Evaluate the number of colonies generated by the EPCs in culture and their kinetics of appearance in patients (major end point)2.

 Enumerate EPCs and CECs by flow cytometry using a specific set of markers (CD133, CD146, KDR).

3.

 Measure of the plasma concentrations of PlGF, VEGF, EPO, ET-1, modulators of angiogenesis.

4.

 Test of correlations between these respective characteristics of EPCs with clinical vascular abnormalities of the disease (retinopathy assessed by angiography, nephropathy, leg ulcers) and severity of vaso-occlusive crisis assessed by number and length of hospitalizations during the previous year and during the study.

.

 Sickle Cell Disease and Endothelial Progenitor Cells (EPCs)@highlight

Sickle Cell Disease (SCD) is the most prevalent genetic disease of haemoglobin.

The underlying abnormality in the red blood cell (RBC) of SCD is the presence of abnormal sickle cell hemoglobin (HbS), which, when deoxygenated, becomes relatively insoluble, forms aggregates with other hemoglobin molecules within the RBC and causes rigid deformation of the cell.

 Acute pain vaso-occlusive crisis, strokes and acute chest syndrome are the main acute complications, sometimes life-threatening, often leading to organic and functional squeal.

 Although the common SS form of SCD is a unique gene disorder, the range of the clinical severity is remarkably wide and striking, suggesting that clinical polymorphism is due to modifier genes and environmental factors.

Most of the research efforts have been focused on the biology of haemoglobin and of the red cells.

 Meanwhile, the complex pathophysiology of SCD is undoubtedly influenced by the many physiologic functions of the vascular wall.

 In line with this hypothesis are several reports of increased circulating levels of endothelium-derived surface molecules in SCD patients suggesting marked endothelial stress in SCD.

 Similarly, other processes that involve the endothelium, such as leukocyte adhesion and activation, may play a role in vascular occlusion.

 This accumulation of data raises the unanswered question of the mechanisms of endothelium maintenance and regeneration in SCD.

 Through these mechanisms, it is likely that function or dysfunction of the vascular endothelium contributes to the overall vascular pathobiology of this disease, which includes recurrent vaso-occlusions, stroke, leg ulcers, chronic organ ischemic damages, and neovascularizing retinopathy that affect nearly one-half (48%) of the surviving patients by the fifth decade.

Thus, our groups have combined their respective clinical and biological expertises to test the hypothesis that SCD is a condition of specific endothelial stress and dysfunction upon chronic and Paracystic abnormal interactions with circulating cells and abnormal oxygen delivery to tissues.

 Specifically, we hypothesize that chronic endothelial stress with detachment of activated endothelial cells require increases mobilisation of the Endothelial Progenitor Cells (EPCs) that maintain endothelial homeostasis to avoid major thromboembolic events and vasospasm.

 Inappropriate mobilisation or maturation of the EPCs in SCD may participate to the severity of the disease.

