(fifthQuint)Effect of the Nursing Intervention "Spiritual Support".

 People who attend the study sessions will participate in sessions of relaxation or of spiritual support depending on the group in which they were selected.

 One way to see if there was influence of these activities for the person is measuring some factors such as heart rate, oxygen saturation and blood pressure.

 The interventions will be conducted by the researcher and the data will be collected by a research assistant.

 Before being accepted to participate in the study each participant will be evaluated if he/she meets the needs of the research (day 1); thus it will be observed if she has or not no physical condition to perform normal activities of daily life (Eastern Cooperative Oncology Group - ECOG/Scale Zubrod) like this and your cognitive ability ((Mini-Mental State Examination MMSE/Brucki et al.

 2003); if the patient is performing another type of complementary therapy will be considered his/her temporary interruption during the study period (Sheet inclusion and monitoring).

 After this assessment, women who can participate in the research will answer questions about their identification (Identification Card of the study participants).

 They will answer five questions about spirituality (Pinto; Pais-Ribeiro, 2007).

On the day 2, 3 and 4, during relaxation or spiritual support,the study participants should allow being recorded heart rate, oxygen saturation and blood pressure (ANOVA); this will be done by means of a sensor (or electrode) as those used for ECG and results will appear on a monitor (monitor BM5).

 The sessions of relaxation or of spiritual support will be scheduled in three consecutive meetings in the same week, during the activities of the Teaching, Research and Rehabilitation Center for Mastectomized Women (REMA) of the University of Sao Paulo at Ribeirao Preto College of Nursing (EERP-USP).

 The questionnaires also will be made at the end of the study (day 4), after sessions of relaxation or spiritual support to see if there was any change in the two stages and between the two groups (ANOVA).

 At the end they will give a score from 0 to 10, or give their opinion on the experience of the meetings (Experience Rating Scale).

 Women who are selected to the sessions of relaxation may perform the activity of spiritual support in future schedules, if they want.

 It is necessary to participate of the selected activity, i.

e.

, relaxation or spiritual support, and they cannot switch groups during the research.

 The research ends in 2014 jun.

.

 Effect of the Nursing Intervention "Spiritual Support"@highlight

Condition: patients with breast cancer.

 Intervention: spiritual support (relaxation + image guided + meditation) or relaxation in three consecutive meetings (day 2, 3 and 4), three days of intervention in the same week.

 The first day the participants will be evaluated if she meets the needs of the research and will answer questions about their indentification and spirituality.

 Type of study: intervention Study design: randomized controlled trial Masking: blind study.

 Randomization: sequence generated by SPSS (Statistical Package for the Social Sciences) version 15, organized in sealed envelopes by another qualified professional.

 The research ends in 2014 jun.

