(secondQuint)A Pilot Trial of Combined Exercise and Education in Rural Community-Dwelling Individuals With Chronic Low Back Pain.

 This study will determine whether a designed patient education (PE) program consistent with the current guidelines combined with supervised exercise training emphasizing motor control exercise (MCE) approach will be feasible and acceptable in reducing pain intensity and functional disability in rural community-dwelling individuals with CLBP following 6-weeks of therapeutic session.

 Participants will be recruited and assigned to one of three intervention groups that include combined MCE and PE group, MCE group and PE group using simple random technique based on an electronic randomization table generated by a computer software program.

 Blinded assessment of all clinical outcomes will be performed at baseline and 6 weeks after randomization.

 Primary outcomes include pain intensity and functional disability while secondary outcomes include treatment satisfaction.

 Data will be analysed using descriptive statistics, paired t-test, and ANOVA.

 All statistical analyses will be performed on SPSS (version 24.

00) at alpha level of 0.

05.

.

 A Pilot Trial of Combined Exercise and Education in Rural Community-Dwelling Individuals With Chronic Low Back Pain@highlight

The main purpose of this pilot single blind randomised controlled trial is to assess the feasibility and acceptability of motor control exercise and patient education on pain and functional disability in rural Nigerian community-dwelling individuals with chronic low back pain (CLBP).

