(fifthQuint)Reperfusion Injury After Stroke Study.

 Study design: This is an observational hospital-based study that will include 140 patients with ischemic stroke in the anterior circulation within 12 hours from last seen well, treated either with intravenous thrombolysis or endovascular thrombectomy.

 Included patients have National Institutes of Health Stroke Scale (NIHSS) 7.

 Both circulating biomarkers sampling and CT Perfusion will be performed before acute interventions.

 Clinical/functional and imaging assessments will be repeated 24 hours after interventions and at 3 months after stroke.

 Work Methodology: Stroke severity will be measured using the NIHSS, post-stroke disability by the modified Rankin Scale (mRS) administered at 3 months by visit or phone interview.

 Investigators will rate hemorrhagic transformation (HT) grade using the European Cooperative Acute Stroke Study (ECASS II) criteria and CE according to the Safe Implementation of Thrombolysis in Stroke-Monitoring Study (SITS-MOST) protocol.

 Cerebral imaging will include baseline plain CT, CT angiography and CT perfusion at baseline.

 CT will be repeated at 24 h, and at any time when clinical deterioration will be observed.

 Collection of imaging data will be blinded to both clinical and laboratory data.

 Baseline and follow up CT scans will be assessed by three stroke physicians (FA, BP, VP) for presence of early ischemic signs (Alberta Stroke Programme Early CT score, hyperdensity of middle cerebral artery), presence and severity of small vessel disease markers (white matter changes, preexisting lacunar infarcts, brain atrophy), presence and grading of HT, when present.

 Perfusion maps will be generated for each patient with a deconvolution-based delay-insensitive algorithm.

 For permeability calculation, an adiabatic approximation of distributed parameter analysis will be used.

 Permeability maps will be generated by a dedicated software.

 Recanalization rate will be assessed at 24 hours with either CT angiography, Magnetic Resonance angiography or transcranial doppler.

 In case of effective recanalization (Thrombolysis In Cerebral Infarction scale=2b/3) at the end of endovascular procedure and clinical improvement, recanalization will not be reassessed at 24 hours.

 Laboratory protocol: Blood will be collected in tubes with anticoagulant, as well as in tubes without anticoagulant, before starting and 24 h after thrombolysis.

 Tubes will be centrifuged at room temperature at 1500 * g for 15 min, and the supernatants will be stored in aliquots at -80C.

 Statistical analysis: Pearson 2 will be used to test for significance while comparing categorical variables and ANOVA test for numeric variables.

 To analyze differences in biomarkers levels between baseline and 24 h, a non-parametric Mann-Whitney U test will be used because of relatively large statistical variations.

 As a main explanatory variable, we will use single patient's baseline levels and relative pre- and post-thrombolysis variation ( median value) of Metalloproteinases(MMP) 2-3-9 and Tissue Inhibitors of Metalloproteinases (TIMP)1-2 levels, calculated according to the formula: (24-hour post-thrombolysis MMP or TIMP-pre-thrombolysis MMP or TIMP)/pre-thrombolysis MMP or TIMP.

 Baseline levels and values will be analyzed in relation to demographic and clinical features and across subgroups of patients with different outcomes.

 The net effect of each biomarker in study (baseline, 24 h, and values) on outcomes will be also estimated by both logistic regression and ordinal models, including potentially confounding covariates.

 Novel candidates that will emerge over the course of the study will be considered for analysis In case of skewed distribution of biomarker values, authors will consider the possibility of log-transformation of data.

 Milestones: Phase 1 (6 months): a) Project protocol establishment; b) Dedicated database for data collection construction; c) CTP protocol determination; d) Training on recruiting staff Phase 2 (36 months): a) Baseline patients cohort enrollment; b) Imaging data collection c) Circulating biomarker collection; d) Follow-up assessments (3 months after enrolment) Phase 3 (6 months): a) Post-processing of neuroimaging acquired at baseline ; b) Data completeness and consistency control; c) Data analysis; d) Dissemination of results.

 Reperfusion Injury After Stroke Study@highlight

Background: stroke is a major cause of death and disability.

 Intravenous thrombolysis and mechanical thrombectomy are able to re-open occluded vessels and save the ischemic tissue from death.

 However, recanalization of the occluded vessel may trigger activation of detrimental molecular pathways and exacerbate blood brain barrier (BBB) disruption, eventually determining hemorrhagic transformation (HT) or cerebral edema (CE), causing the so-called "reperfusion injury".

 There is increasing evidence that a number of factors measurable as circulating biomarkers, particularly metalloproteinases (MMP), contribute to reperfusion brain injury.

 Preliminary data show that BBB disruption can be traced in vivo by Computed Tomography Perfusion (CTP) imaging.

 The aim of this study is to evaluate the effects of circulating and imaging biomarkers in relation to reperfusion injury.

 Methods: consecutive patients presenting with acute ischemic stroke in the anterior circulation territory, scoring7 on NIHSS, candidates to intravenous thrombolysis or to endovascular treatment, will be enrolled in one hospital centre.

 Circulating levels of pro-, anti-inflammatory, immunomodulatory factors, metalloproteinases and their inductors/inhibitors, factors of endothelial dysfunction and fibrin resistance to lysis will be measured in blood samples taken from each patients pre-thrombolysis and 24 hours after thrombolysis.

 Biomarker levels will be studied in relation to CTP measures of BBB permeability and in relation to imaging signs of reperfusion injury after acute interventions, such as hemorrhagic transformation and cerebral edema.

 Results: enrollment started on October 2015.

 As of January 2017, 70 patients have been included.

 Results are expected by the end of 2018 with an estimated sample size of 140 patients.

 Using a definite protocol, a prospective collection of data, and an adequate number of patients assuring statistically powered data, this study will integrate clinical information with imaging and biological factors involved in reperfusion injury after cerebral ischemia.

