(fifthQuint)Pre-Prostatectomy Celecoxib or Placebo.

 PRIMARY OBJECTIVE I.

 To determine if COX-2 inhibition with celecoxib significantly increases apoptosis in human adenocarcinoma of the prostate.

 SECONDARY OBJECTIVES I.

 To determine if COX-2 inhibition with celecoxib reduces levels of Prostaglandin E2 and androgen receptor in fresh tumor tissue collected at prostatectomy II.

 To collect pre- and postoperative serum Prostate Specific Antigen (PSA) for exploratory analyses III.

 To determine the effect of celecoxib on adverse effects, perioperative surgical complications and post surgery analgesic use.

 Pre-Prostatectomy Celecoxib or Placebo@highlight

This study will seek to determine if the downstream effects of cyclooxygenase-2 (COX-2) inhibition suggested by preclinical systems occur in human prostate cancer.

 To answer this question, men who have chosen prostatectomy will be randomly assigned to preoperative treatment with celecoxib or placebo for four weeks.

 Carefully collected tumor, premalignant, and benign prostate tissue will then be examined for apoptosis, androgen receptor and prostaglandin E2 levels.

 Tumor COX-2 expression will be correlated with observed treatment effects.

 The data generated by this study will serve as a foundation for the development of COX-2 targeted therapies for prostate cancer, will provide preliminary evidence for larger scale clinical trials aimed at treatment and prevention of prostate cancer, and will validate current preclinical models used to study COX-2 in prostate cancer.

