(fifthQuint)A Multicenter, Randomized, Placebo-Controlled, Double-Blind Trial to Evaluate the Safety and Immunogenicity of an HIV-1 Pseudovirion Vaccine.

 The pseudovirions are virus-like particles generated by in vitro production of HIV-1 viral proteins which are capable of assembly into particles.

 The presence of gag gene products in addition to envelope glycoprotein should assist in humoral and cellular immunologic responses to internal HIV-1 viral proteins.

 The pseudovirion vaccine has been tested in preclinical trials in mice, guinea pigs, rabbits, and nonhuman primates with good safety and immunogenicity profile.

 A total of 78 volunteers will be recruited and randomly assigned to receive pseudovirion vaccine and/or the placebo/adjuvant.

 All volunteers will receive injections intramuscularly at 0, 1, 3, 6, and 12 months.

 Group I (30 volunteers): pseudovirion vaccine w/adjuvant or w/o adjuvant.

 Group II (30 volunteers): pseudovirion vaccine w/adjuvant or w/o adjuvant.

 Group III (18 volunteers): adjuvant (QS21 or alum) or saline placebo.

 NOTE: Group I will receive appropriate adjuvant or saline placebo at Month 3 without pseudovirion vaccine.

.

 A Multicenter, Randomized, Placebo-Controlled, Double-Blind Trial to Evaluate the Safety and Immunogenicity of an HIV-1 Pseudovirion Vaccine@highlight

The purpose of this trial is to determine the safety and immunogenicity of an HIV-1 pseudovirion vaccine given at one antigen dose alone and in combination with each of two different adjuvants using two immunization schedules.

 The pseudovirions are virus-like particles generated by in vitro production of HIV-1 viral proteins which are capable of assembly into particles.

 The presence of gag gene products in addition to envelope glycoprotein should assist in humoral and cellular immunologic responses to internal HIV-1 viral proteins.

 The pseudovirion vaccine has been tested in preclinical trials in mice, guinea pigs, rabbits, and nonhuman primates with good safety and immunogenicity profile.

