(fifthQuint)Infectious Outcomes Following Pancreas Transplantation.

 The objectives of the study are: 1.

 To determine what is the frequency of infectious complications following pancreas transplantation 2.

 Characterize the clinical and microbiological aspects of the infectious complications following pancreas transplantation 3.

 Identify predictors for infection following pancreas transplantation 4.

 Determine the frequency of graft loss and associated mortality of infectious complications following pancreas transplantation.

 Infectious Outcomes Following Pancreas Transplantation@highlight

The proposed protocol aims to characterize the infectious episodes in pancreas transplant recipients under the current medical care.

 Knowing these patients infectious risks, the types of infections that commonly affect them and the morbidity and mortality associated with it will provide valuable information in the evaluation of the safety and efficacy of the current practices.

 The information generated by this study will also serve as the basis for development of strategies targeting prophylaxis of infectious episodes.

