(fifthQuint)Critical Thinking in Nursing Students.

 In Brazil there are few studies produced about Critical Thinking (CT), and the field of Brazilian nursing are unknown type of intervention research to assess / provisions initially measure and skills development / PC skills.

 Thus, the research question to be answered is: Students undergo an educational intervention focused on first aid care based on the Problem Based Learning (PBL) and guided by Active Teaching Model for Critical Thinking (MEAPC), have better results for PC skills and provisions compared to students learning the same content from PBL without MEAPC? * STUDY OBJECTIVES General Purpose: Create, implement and evaluate an educational intervention for nursing students focusing on first aid, to develop skills and PC provisions, based on Problem Based Learning (PBL) and guided by Active Teaching Model for Critical Thinking (MEAPC) .

 Specific Objectives: - Create an educational intervention focusing on first aid, to develop skills and PC provisions, through the PBL, guided by MEAPC (experimental group) and with PBL and without MEAPC (control group); - Apply the educational intervention focusing on first aid for the development of skills and PC provisions, through the PBL, guided by MEAPC (experimental group) and the PBL and without MEAPC (control group); - Evaluate the experimental group and control (before and immediately after the intervention) PC skills and dispositions, respectively, through the test California Critical Thinking Disposition Inventory (CCTDI) and California Critical Thinking Skills Test (CCTST); - Compare possible differences between the two groups of students (experiment and control) in relation to age and sex; - Evaluate the effectiveness of MEAPC associated with PBL, comparing the performance of the experimental group and control; - Assess the educational intervention through knowledge of students using tests ten true and false statements (T or F test) applied before and immediately after the intervention.

 STUDY ASSUMPTIONS This study will be developed based on five assumptions, explained below: - Students who participate in the educational intervention focused on first aid care, based on the PBL-driven MEAPC will get better results in the test California Critical Thinking Dispositions Inventory (CCTID) and test California Critical Thinking Skills Test (CCTST), which students attending the educational intervention aimed at answering first aid, based on the PBL, but not being guided by MEAPC; - Older students (22 and older) will get better results in the tests California Critical Thinking Dispositions Inventory (CCTID) and California Critical Thinking Skills Test (CCTST) than younger students (under 22 years) in the experiment and control groups; - There will be no significant differences regarding gender in relation to tests California Critical Thinking Dispositions Inventory (CCTID) and California Critical Thinking Skills Test (CCTST) compared the experimental and control groups; - The evaluation of educational intervention through knowledge of students using true and false statements test (V or F) applied before and immediately after the intervention, developed quantitative improvement in results.

.

 Critical Thinking in Nursing Students@highlight

Considering the need for an intervention in the context of the Brazilian nursing education, in order to develop the skills and dispositions for critical thinking (CT), this study aims to fill this gap through a first aid course, comparing a group control and an experimental group.

 In this study will be used two tests, California Critical Thinking Dispositions Inventory (CCTID) to review arrangements for the CT, and California Critical Thinking Skills Test (CCTST) to evaluate CT skills, both marketed (Facione N, Facione PA, 2009 , 2011).

 Therefore, in order to facilitate the assimilation of PC skills during the course, we prepared the model of Active Teaching for Critical Thinking (MEAPC): characterized by a teaching method proposed by the author of this work, who understands the educational activity active and intentional as mobilizing higher mental processes fundamental to the development of the CT.

