(fifthQuint)Acute Kidney Injury Standardized Clinical Assessment and Management Plan for Renal Replacement Initiation.

 Background: Acute Kidney Injury (AKI) is common among critically ill patients and is associated with substantial morbidity and mortality.

 Severe AKI requiring renal replacement therapy (RRT) is associated with in-hospital mortality rates exceeding 40%.

 The investigators designed and implemented an AKI Standardized Clinical Assessment and Management Plan (SCAMP), a decision-making algorithm to assist front-line nephrologists caring for patients with AKI.

 The investigators piloted the implementation of the AKI SCAMP in the medical intensive care unit at Brigham and Women's Hospital prospectively over the course of 1-year, and illustrated that patients whose nephrologists adhered to the SCAMP recommendations had lower in-hospital mortality.

 The investigators have a publication in press in the Clinical Journal of the American Society of Nephrology detailing our findings (Mendu et al.

 CJASN January 2017).

 Aims: The primary aim of this study is to expand the prospective implementation of the AKI SCAMP to multiple intensive care units (ICUs) at Brigham and Women's Hospital in an interrupted time series study (nephrologists will be asked to complete the AKI SCAMP alternate months).

 The investigators aim to test the hypothesis generated by our pilot study, that the utilization of an AKI SCAMP by providers in a critical care setting can reduce in-hospital mortality.

 Expanding to multiple ICUs and introducing a time series design will mitigate the limitations of our pilot data, such as a small sample size and confounding by disease severity.

 Design: The investigators seek to conduct a prospective interrupted time series study of the implementation of an AKI SCAMP utilized by nephrologists in intensive care units during the time period of 1 year to determine if utilization of the AKI SCAMP reduces in-hospital mortality.

.

 Acute Kidney Injury Standardized Clinical Assessment and Management Plan for Renal Replacement Initiation@highlight

This study is of a clinical decision support tool for clinicians taking care of patients with severe acute kidney injury in the intensive care unit.

 Nephrologists will be given a standardized clinical assessment and management plan (SCAMP), which is a tool to assist clinicians in decision making on the need for renal replacement therapy (Mendu et al.

, CJASN 2017).

 In alternating months, nephrologists will be given the SCAMP vs.

 another simplified form.

 The goal is to test whether patients whose clinicians are asked to fill out the SCAMP have improved outcomes compared to the control group.

 The investigators are also collecting information about provider adherence to the SCAMP and deviations from the SCAMP recommendations to understand clinical decision making related to renal replacement.

