(fifthQuint)Non-adherence and Polypharmacy in Elderly Patients.

 The investigators intend to include all patients > 65 years old, in dialysis treatment (hemodialysis and peritoneal dialysis), as well as patients with CKD stage 5.

 The recruitment will be done as follows: The patients will be screened according to inclusion criteria.

 Afterwards each patient will be invited to a first meeting that explains the aim of the study, giving the opportunity for discussion and consideration, and presenting the consent information.

 After giving the consent the patient will be invited to a second meeting with blood tests, data registration, medication registration, undergoing MMS and handing over the questionnaires forms.

 Randomization: After the initial assessment and compliance with the eligibility criteria, participants will be randomized into an intervention group (medication list will be evaluated by STOPP/START criteria) and a control group (medication list will not be evaluated by STOPP/START criteria).

 Randomization numbers will be generated by a random number generator.

 A series of numbered, sealed, opaque envelopes will be used to ensure confidentiality.

 Each envelope will contain a card with information about the group allocation.

 The group allocation is concealed from the researcher and patients at baseline registration.

 Each patients will get questionnaires for: Quality of life using Kidney Disease Quality of Life - Short form 36 (KDQOL-Short form 36 ) and EuroQoL-3D (EQ-3D), beliefs about medicine, Hospital Anxiety and Depression Scale (HADS), Morisky medication adherence scale and visual adherence scale (VAS), sleeping related questionnaires (Epworth, Berlin, Pittsburgh).

 A Mini Mental Status (MMS) test will be done regarding cognitive function.

 Each patients will get the opportunity to have a polysomnograph for one night.

 With STOPP/START criteria the medication list will be evaluated for the patients who are randomized in the intervention group.

.

 Non-adherence and Polypharmacy in Elderly Patients@highlight

The study aims to investigate adherence and polypharmacy in elderly patients with chronic kidney disease (CKD) and End Stage Renal Disease (ESRD).

 The investigators look into possible factors or predictors that may affect adherence and reduce polypharmacy.

 Factors could be: quality of life, anxiety and depression, beliefs about medicine and cognitive impairment.

 The investigators are planning an intervention with the screening tool Screening Tool of Older Person's potentially inappropriate Prescription/Screening tool to Alert to Right Treatment (STOPP/START ) criteria to evaluate medication lists of the participating patients.

