(fifthQuint)Family Myopia Study.

 Myopia or nearsightedness, a condition that results in the inability to see distant objects clearly, affects one in four Americans and is the most common eye disorder in the world with an enormous public health and economic impact.

 Depending on epidemiologic definition, 3-19% of acquired blindness has been ascribed to myopia.

 Evidence exists that myopia is a complex disorder with a significant genetic component as well as potential environmental influences.

 Implicating genetic factors, Sorsby et al.

 found that the trait correlation for monozygotic twins was nearly twice that for dizygotic twins and zero for control pairs.

 A study, by Chen et al.

, of Chinese twin pairs found a higher concordance rate of myopia (92.

2%) for monozygotic twins with concordant close-work habits, or differences of less than one hour per day spent studying or reading, as compared to monozygotic twins with discordant close-work habits (79.

3%).

 The two studies suggest additive interaction between zygosity and close-work habits.

 Since there is a tendency of myopia to cluster in families, studying families with myopia opens the possibility to identify any gene(s) responsible for the pathogenesis of myopia.

 These genes could provide molecular tools for investigation of inherited myopia and may also provide a starting point for elucidating mechanisms for the influence of near work on the progression of myopia.

 The goal of this proposal is to identify regions of the human genome that contain the genes responsible for non-syndromic myopia utilizing pedigrees identified by the Myopia Family Study and genotypes generated by Dr.

 Dwight Stambolian's laboratory at the University of Pennsylvania as well as by the Center for Inherited Disease Research.

 Pedigree collection is ongoing in several geographic regions including Lakewood, NJ, for the collection of Orthodox Jewish families, Lancaster County, PA for the collection of Amish families, and Philadelphia, for recruitment of families of African American or Chinese American background.

 Pedigrees of Caucasian descent have also been collected in Philadelphia.

 All data collection is under the direction of Dr.

 Stambolian and funded by his grant from the NEI; no NHGRI funds are being used for data collection, and NHGRI investigators do not have any contact with study subjects.

 Because this disorder is complex and has a high likelihood of being caused by multiple loci, multiple parametric and non-parametric methods of analysis will be employed.

 Heterogeneity will be taken into account during these analyses, as will environmental covariates, such as the effect of near work, when possible.

.

 Family Myopia Study@highlight

This study will try to identify the gene or genes responsible for myopia (nearsightedness) and to examine the relationship between myopia and near work.

 Myopia is the most common eye disorder in the world, affecting one in four Americans.

 Several studies indicate that myopia is inherited.

 The condition tends to cluster in families, so that studying families with this condition may facilitate finding the exact cause.

 Caucasian Americans and African Americans with myopia who are in general good health may be eligible for this study.

 People with a family history of myopia through several generations along one parent s side only, and in which more than one sibling has myopia are preferred.

 People who have severe diseases that involve myopia, such as Stickler s or Marfan syndromes, retinitis pigmentosa or diabetic retinopathy may not participate.

 Participants will undergo the following tests and procedures: - Eye examination, including refraction - Blood draw for genetic studies and possibly establishment of cell lines (collection of cells grown in the laboratory from an original tissue specimen) for future research - Myopia Family Study Questionnaire and personal medical information questionnaire to provide information about other medical conditions that may influence the development of myopia; the vision status of their spouse and children, parents and siblings, and spouse s parents and siblings - Risk Factor Questionnaire (for Jewish Orthodox community only) to assess the amount of near work activity done in childhood