(fifthQuint)Effect of a Self-adhering Material in Dental Hypersensitivity.

 Participants The study was designed as a split-mouth randomized clinical trial.

 The protocol and informed consent forms were approved by the ethics committee at the University of Sassari (n 1000/CE).

 To participate in the study, all the subjects were carefully informed about the study's purpose, risks and benefits.

 The study inclusion criteria were the following: - Generally good health despite the seriousness of their illness; - A clinical reduction of salivary flow; - The presence of two or three teeth which were hypersensitive to stimulation with a blast of air.

 In addition, patients were considered suitable for the study if they had sensitive teeth showing abrasion, erosion or recession with the exposure of the cervical dentine.

 The study exclusion criteria were: - teeth with subjective or objective evidence of carious lesions, pulpitis, restorations, premature contact, cracked enamel, active periapical infection or that had received periodontal surgery or root-planning up to 6 months prior to the investigation; - patients who had received professional desensitizing therapy during the previous 3 months; - patients who had used desensitizing toothpaste in the last 6 weeks.

 Patients were also excluded if they were under significant medication that could have interfered with pain perception (e.

g.

, antidepressants, anti-inflammatory drugs, sedatives, and muscle relaxants).

 Clinical Procedure Saliva collection All salivary assessments were performed in the absence of acute sialadenitis.

 All assessments were performed by the same observer.

 The flow rate was determined in every person according to the method described by Sreebny.

 Saliva was collected in a standardised manner.

 Patients were instructed not to eat, drink, or smoke for 90 minutes before the sialometric assessment.

 All assessments were performed at a fixed time of the day, between 10 am and 1 pm, in order to minimise fluctuations related to a circadian rhythm of salivary secretion and composition.

 The whole saliva sample was collected in pre-weighed plastic tubes using electronic scales.

 Unstimulated salivary secretions were collected for 5 min with the patient seated in an upright position, with the head tilted forward .

 When possible the tongue, cheek and lip movements were limited during the procedure.

 At the end of the collection period the patient had to expectorate saliva into the test-tube.

 Stimulated whole saliva samples were collected by asking patients to chew a small block of paraffin wax or chewing gum.

 All the saliva secreted for 5 min was then collected in the test-tube.

 Measuring vessels were weighed after each collection using an electronic scales, and salivary flow rate was expressed in ml/min, which is nearly equivalent to g/min (31).

 A secretion rate cent (VF) (Kerr Corporation, Orange, CA, USA), a self-adhering composite; Universal Dentin Sealant (UDS) (Ultradent Products Inc.

, South Jordan, UT, USA), a biocompatible, non-polymerizable, high molecular weight resin sealant in alcohol solvent; Clearfil Protect Bond (CPB), (Kuraray Noritake Dental, Osaka, Japan) a methacrylate-based resin, self-etching adhesive system, and Flor-Opal(R) Varnish (FOV), (Ultradent Products Inc.

, South Jordan, UT, USA), a fluoride-based varnish.

 In view of the treatment with the desensitizing agents, teeth were randomly assigned into four groups (N = per group).

.

 Effect of a Self-adhering Material in Dental Hypersensitivity@highlight

Aim: To compare the desensitizing capacity of Vertise Flow cent (VF), a new self adhering material, in the treatment of dentine hypersensitivity (DH) in patients who are xerostomic due to radiotherapy for head and neck cancer.

 Methods: A total of 17 patients were selected for the study.

 The study was conducted as a split-mouth randomized clinical trial comparing: 1) VF 2) Universal Dentin Sealant (UDS), 3) Clearfil Protect Bond (CPB) and 4) Flor-Opal(R) Varnish (FOV).

 Basal and stimulated salivary flow was recorded for each patient according to the method described by Sreebny.

 The pain experience was generated by a cold stimulus directly to a sensitive tooth surface and assessed using the Visual Analogue Scale (VAS).

 The response was recorded before the application of the materials (PRE-1), immediately after (POST-1), at 1-week (POST-2), 4-weeks (POST-3) and 12-week controls (POST-4).

