(fifthQuint)Maintenance of an Antiaggregation by Kardegic 75 While a Lithotripsy Session on a Kidney Stone is Perfomed.

 Comparative Unicentric Prospective Study.

 Before the ECL: Patients will be recruited during the urology consultation prior to the lithotripsy for calculations Kidneys (JJ probe in place or not) using an uninjected abdominal-pelvic or ultrasound scanner Renal coupled to a AUSP (urinary tree without preparation).

 ECL is an Unbody method that allows the calculation to be fragmented using shock waves Generated by a lithotripter.

 It will be given to them, after explanation of this method by the doctor during the Consultation, a AFU information sheet on the LEC explaining its steps, possible complications, its follow-up.

 After checking the inclusion and non-inclusion criteria, patients will be programmed to lithotripsy extra body without prior stop of KARDEGIC 75.

 At the LEC session: Evaluation of blood pressure before the session and at the end.

 Medical history and treatment will be notified in the patient file Verification of blood balance (coagulation, renal function) and urinary (BU and ECBU) Evaluation of pain by analog visual scale (AVS) before and during the session.

 Notification of possible symptoms (adverse reactions = AR) in the medical file.

 Prescription of analgesics as well as blood balance and revaluation scanner at D15 Taking a post-ECL appointment with the reference urologist at D23 (+-2days) After the ECL session: 3-week post-ECL Consultation: Pain Assessment (AVS) Evaluation of the effectiveness of the ECL (stone clearance) Reading of the scanner performed at D15 in search of a hematoma "(the scanner will also be replayed from systematically by the prescriber or a urologist of the service looking for a hematoma and the level of efficacy of the ECL + control of the blood balance in search of a inflammatory/infectious/anemia/renal function Chronology of the essay: Duration of study estimated at: 3 years Start date of study (first patient included): 09/2017 End Date (end of follow-up of the last patient of the study): 09/2020 Total duration of participation in the study for the patient: 5 to 6 weeks The end-of-study date shall be transmitted to the competent authority and the MPC within 90 days.

 If the study is to stop prematurely, the information will be transmitted within a period of 15 days The competent authority and the MPC.

 Main judgement criterion: Proportion of patients with renal hematoma when performing of lithotripsy for renal lithiasis, on a 15-day scanner.

 Number of topics: 300 based on a 4-step sequential plan of Fleming type Inclusion criteria: Patients over 18 years of age benefiting from the social security scheme Patients with at least one renal lithiasis requiring treatment with lithotripsy Non-inclusion criteria: KARDEGIC 75mg can not be stopped (recent angioplasty.

.

.

) Coagulation disorder known or discovered on the pre-therapeutic balance sheet Associated anticoagulant therapy.

 Presence of another contraindications to the ECL.

 Conduct of the study: Study carried out in current practice at the CHU of Clermont Ferrand in the Department of Urology.

 The patient will be seen in consultation by the urologist who shall prescribe the Lithotripsy sessions, inform the of the session and will provide him with a AFU information sheet concerning the stages of the session, and prescribe a blood test to be presented to the lithotriptor on the day of the examination.

 Not additional accommodation to plan.

 The patient will return 3 weeks after the ECL session for his evaluation with the urologist.

 He will have previously completed a blood check and a 15-day scan of the lithotripsy session (instead of about 3 weeks usually).

 Benefits and risks of this study: Simplify patient management under KARDEGIC 75.

 Decrease in cardiovascular risk by maintaining the KARDEGIC 75.

 Increase of the risk of post-ECL hematoma.

 Maintenance of an Antiaggregation by Kardegic 75 While a Lithotripsy Session on a Kidney Stone is Perfomed.

 Comparative Unicentric Prospective Study@highlight

Background/Rationale for the study: Lithiasis pathology is increasingly common because of the change in our lifestyle and our food.

 Thus, we hold a prevalence for urinary lithiasis 10% in France currently including 13% of the male population and 6% of the female population.

 The formation of urinary lithiasis is the result of a complex mechanism involving factors anatomical and infectious metabolics.

 They are classified according to their size, topography and composition.

 The treatment of urinary lithiasis has changed dramatically in recent years.

 The recommendations of the French Urology Association (AFU) for the management of kidney stones and ureteral of the adult of 2004 give a certain place to the treatment by lithotripsy (ECL).

 The ELC is indicated for the first purpose for lithiasis ureteral or renal lithiasis of less than 20 mm, whether or not associated with the setting up of a JJ probe.

 For kidney stones of more than 20 mm or complex or Coralliformes, the lithotripsy can be associated with treatment with percutaneous nephrolithotomy.

 In addition, the ECL is indicated in case of residual cholelithiasis 3 months after a first treatment whatsoever.

 It is found, as the main complication of the LEC, a risk of the appearance of Hematomas under capsular, peri-renal and intra-parenchymatous.

 Its prevalence is estimated to be between 6.

2% and 13% according to studies.

 KARDEGIC 75, antiplatelet (PAA) is the lowest dosage of aspirin in the adult.

 The AMM of KARDEGIC recognises its indication in secondary prevention after a first myocardial or cerebral ischemic attack related to atherosclerosis.

 It entrains a reduction mortality and morbidity of cardiovascular causes.

 Kardegic is currently being stopped 5 to 7 days before the LEC.

 The interest of maintaining the KARDEGIC 75 is: - A simplification of the management of patients under KARDEGIC 75 (No modification of Treatment to be implemented) - Decreased cardiovascular risk (treatment maintained) Main objective: Evaluation of the proportion of renal hematoma during the production of Lithotripsy for renal lithiasis, on a 15-day scan, in patients under KARDEGIC 75mg not stopped Secondary objectives: Evaluation of the efficacy of treatment with lithotripsy (Stone free, fragments Minimal residuals) Evaluation of the proportion of hematuria macroscopic post lithotripsy in Patients under KARDEGIC 75 not stopped.

 Evaluate the rate of post-LEC complications requiring treatment, Analgesic, obstructive pyelonephritis.

 Evaluate post-LEC pain due to hematoma or lithiasis migration Evaluation of the evolution of renal function post session of Lithotripsy in the patients under KARDEGIC 75 not stopped.

 Type of Study: Interventional study, prospective, mono centric, single-arm