(fifthQuint)Mitochondrial Dysfunction in the Pathophysiology and Treatment of Bipolar Disorder.

 Bipolar affective disorder is a common, severe, chronic and often life-threatening illness.

 The depressive phase contributes to the majority of morbidity and mortality in this illness.

 Impairments in physical and social functioning resulting from depression are often as severe as other chronic medical illnesses.

 Few of the treatments in use have resulted from an understanding of the pathophysiology of bipolar disorder.

 Undoubtedly, a greater understanding of the pathophysiology of bipolar disorder will lead to improved treatments.

 Current theories of depression suggest that mood disorders are associated with impairments of cellular resilience and structural plasticity possibly a result of abnormal cellular energy metabolism.

 Studies with Magnetic Resonance Spectroscopy (MRS) in bipolar subjects show reduced brain intracellular pH and reduced ATP.

 Cellular energy generated by mitochondrial oxidative phosphorylation from glucose via the electron transport chain is stored as ATP, which provide neurons and glia with energy required to maintain their function.

 Mitochondrial dysfunction and its inability to compensate for increase in ATP demand might lead to impaired cellular resilience believed to be involved in the pathophysiology of bipolar disorder.

 Abnormal regulation of nuclear genes coding for mitochondrial proteins in the hippocampus of bipolar subjects provides further evidence of mitochondrial dysfunction in bipolar disorder.

 Coenzyme Q10 (CoQ10) is an essential cofactor in the mitochondrial electron transport chain necessary for cellular energy generation.

 Exogenous administration of CoQ10 attenuates ATP depletion and has anti-oxidant properties.

 In light of the above evidence, we hypothesize that bipolar disorder is associated with mitochondrial dysfunction as evidenced by impaired brain energy metabolism and that administration of CoQ10, a mitochondrial enhancer, will restore mitochondrial function.

 To accomplish these objectives, we will compare mitochondrial functions in bipolar depressed subjects to 26 healthy controls matched for age, gender and BMI.

 Measures of mitochondrial function will include brain lactate levels (a product of anaerobic glycolysis) with H+ MRS, 2) assays of mitochondrial function in cultured fibroblasts and platelets, and 3) gene expression of mitochondrial and nuclear genes using a cDNA Microarray.

 Further, subjects with bipolar depression, ages 18 to 65 will be randomized to either CoQ10 (300-1200 mg/day) or placebo in a double-blind placebo controlled trial for a period of 8 weeks.

 Measures of mitochondrial function will be compared between subjects randomized to placebo or CoQ10 at baseline and at the end of the 8-week trial.

.

 Mitochondrial Dysfunction in the Pathophysiology and Treatment of Bipolar Disorder@highlight

This study will examine whether mitochondrial function is impaired in patients with bipolar disorder.

 Mitrochondria are small organelles inside the cell that are responsible for energy production.

 Recent studies in animals and humans suggest that abnormalities of mitrochondria may be involved in bipolar depression.

 The study will also examine whether the food supplement Coenzyme Q10 (CoQ10) improves mitochondrial function and symptoms such as depressed mood, low energy, anxiety or slowness in thinking and movements in bipolar patients.

 CoQ10 has been used to increase cell energy production and as an antioxidant.

 It has had some benefit in patients with Parkinson's disease and migraine and in prolonging survival in patients with cancer and heart failure.

 Patients 18-65 years of age with bipolar disorder who are currently in a depressive episode of at least 4 weeks duration may be eligible for this study.

 The study has four phases, as follows: Phase I: Medication Withdrawal Patients taper off all psychotropic medications, usually over 1 to 2 weeks.

 Phase II: Baseline Evaluation After being off all medication for about 2 weeks, patients undergo the following procedures: - Magnetic resonance imaging (MRI) and magnetic resonance spectroscopy (MRS).

 The two procedures are performed in an MRI scanner.

 Both tests use a strong magnetic field and radio waves to obtain images that provide information on brain anatomy and chemistry.

 - Blood tests to assess mitochondrial function isolated from blood cells.

 - Skin biopsy for tests of mitochondria.

 A small sample of skin tissue 5 x 5 millimeters is surgically removed.

 Phase III: Administration of CoQ10 or Placebo Participants are randomly assigned to take either CoQ10 or placebo (an inactive look-alike substance) twice a day by mouth.

 While taking the study medication, patients have the following procedures periodically: - Rating scales for anxiety and depression and adverse events.

 - Check of vital signs.

 - Blood and urine sample collections.

 Phase IV: Study Completion At the end of the 8 weeks of treatment, patients have a physical examination and electrocardiogram, and the procedures in phase II are repeated.

 Participants may then receive short-term treatment (up to 12 weeks) with medications for bipolar depression, followed by referred to a community physician for long-term treatment.

