(fifthQuint)The Study of Mindfulness Based Cognitive Therapy and Obsessive-Compulsive Disorder.

 The qualitative research will use grounded theory path to interview therapists and patients for 60 minutes in the baseline, after 5 weeks treatments and after the 10 weeks treatments.

 The subjective experience of the therapists and patients in two pilot MBCT groups will be described and explained.

 And the entire process of treatments will be participatory observed.

 In the second part of the study, all patients will take blood test and functional magnetic resonance imaging (fMRI) scan in the baseline and after 10 weeks, to gather data in genetics and imaging features, which can help the study to discover biological indicators of the curative effect.

 And after the patients and their custodians signed the consent form, all of participants will be blindly assigned to three groups by a predetermined random table which is generated by Microsoft Excel 2010 for ensuring randomly fair distribution across conditions.

 The investigators will not decode these numbers until the intervention group is assigned.

 As the research tools, a range of self-rating scales, other-rating scales and behavioral and physiological measures will be mainly applied to assess clinical symptoms of participants at baseline (week 0), mid-treatment (week 4), at the end of acute treatment (week 10), and during the maintenance phase (week 14, 22 and 34).

 After 10 sessions, all the participants including the non-responders and the responders (ie, decrease in Yale-Brown Obsessive Compulsive Scale [YBOCS] scores 25%) will enter the maintenance phase for 6 months.

 The participants in MBCT group will continue MBCT treatments at home.

 The participants in drug therapy group will continue on their treatment program without changing the type and dosage of medication they have been using.

 By comparing clinical symptoms, such as obsessive and compulsive symptoms, anxiety, depression, quality of life and other clinical symptoms and behavior, the study will describe the short-term and long-term effects of MBCT in patients with DSM-IV obsessive-compulsive disorder (OCD).

.

 The Study of Mindfulness Based Cognitive Therapy and Obsessive-Compulsive Disorder@highlight

The primary objective of the study is to evaluate the clinical curative effect of MBCT to reduce obsessive and compulsive symptoms.

 Moreover, the investigators will also explore a MBCT manual for Chinese patients with OCD, which can be widely applied to the clinical practice.

 There are two parts of the study.

 The first part is a qualitative research with two pilot MBCT groups.

 The second part of this study is a single-blind randomized controlled trial with three study arms: one - third of participants receive group mindfulness-based cognitive therapy led by trained MBCT psychotherapists or psychiatrists in addition to medication, one - third of participants receive group psycho-education program and one - third of participants receive drug therapy as usual.

 All participants have 10 sessions intervention and assessments.

