(fifthQuint)Improving Oral Health Function With Implant Supported Partial Dentures.

 In the past few decades there has been predictions regarding the level of edentulism, and the need for prosthetic rehabilitation of the population.

 Although studies estimate a decline in the percentage of edentulism, and a decreased need for removable prostheses, this is predicted to be offset by a projected 79% increase in the population that is 55 years or older, the number of individuals with existing prostheses needing new prostheses and maintenance, and the professional and public health responsibility to serve this population regardless to the level of edentulism.

 In spite of these demographic predictions, the need for prosthodontics services, both fixed dental prostheses and removable dental prostheses will continue to an oral health concern, in part due to the an aging population that retains more of their teeth resulting in partial edentulism.

 Prosthetic rehabilitation should not only replace missing teeth, but it should restore oral function and have a positive impact on Oral-Health-Related Quality of Life (OHRQoL) of our patients.

 As the population continues to age worldwide, and the U.

S.

 specifically, it will become increasingly important to improve the OHRQoL for the segment of our population possessing removable prostheses with high stability, and highly retentive prosthetic services.

 Traditionally, both complete and partial removable dentures lack retention and stability, and one recommendation to improve the function has been to utilize dental implants to retain and stabilize the prosthesis.

 Although, several investigations have evaluated the OHRQoL patients wearing removable the preponderate emphasis of these studies has been on complete denture patients.

 In addition, OHRQoL studies are generated by patient self-reports, and limited evaluation of actual oral function has been compared to the patient self-reported function.

 This study will use the OHIP to evaluate the OHRQoL of patients with distal extension partial dentures, as well as, actually measure the patients chewing ability.

 This prospective cohort study is designed to gather preliminary data on the improvement of patient satisfaction and oral function for individuals wearing distal extension partial dentures that are supported by smaller length dental implants.

 Thirty healthy male and female participants aged 18 to 65 will be treated at the University of Minnesota Dental School, in the Clinical Research Center.

 A lower partial denture will be fabricated using routine prosthodontic techniques.

 The participants will receive a 7 mm X 3.

75 mm or a 8.

5 mm X 4.

1 mm tapered implant, A Locator Abutment will be used to connect the denture to the implant to improve the retention and stability of the partial denture.

 The chewing ability and chewing pattern will be evaluated with a jaw-tracking device and the masticatory muscle activity will be evaluated with surface Electromyography (EMG).

 OHRQoL, chewing function, and patient satisfaction will be measured at the 1, 2, 6, and 12-month recall appointments.

.

 Improving Oral Health Function With Implant Supported Partial Dentures@highlight

Distal extension Partial Removable Dental Prostheses (PRDPs) are less stable than tooth supported PRDPs due to progressive resorption of the alveolar ridge, which alters the retention and support generated by alveolar bone height.

 In addition, long-term wearers suffer with progressive alveolar ridge resorption that contributes to greater instability.

 The loss of stability and retention under the PRDP can lead to difficulties during mastication and swallowing, because of movement of the partial denture.

 These difficulties force patients to self-select food substances that are softer and easier to chew and possibly create changes in social eating.

 Therefore, having a partial denture that is poorly retentive will impact their oral health related quality of life Oral Health Related Quality of Life (OHRQoL).

 The placement of a dental implant into the edentulous area will transform a conventional PRDP into an Implant Supported PRDP, which will improve the functional capacity of partial denture wearers, especially their ability to comminute harder food substances such as fruits and nuts.

 The purpose of this study is to quantitatively measure the functional differences of patients wearing conventional PRDP with patients wearing implant supported PRDPs and Oral Health Impact of patients wearing implant supported PRDPs.

 The hypothesis is that patient wearing implant supported PRDPs will have greater functional capacity than patients wearing conventional PRDPs.

