(fifthQuint)Evaluate Bundling of Nutrition Interventions.

 Research Design and Methods The investigators propose a community-based cluster randomized trial (CRCT) to evaluate the effectiveness of different combinations of 5 selected prenatal and post-natal nutrition-specific interventions in improving mean HAZ scores among 24 months old children.

 The interventions to be tested in different combinations are-: 1.

 Prenatal nutrition-specific counselling 2.

 Prenatal nutrition supplementation 3.

 Intensive counselling of exclusive breast-feeding during postnatal first six months 4.

 Supplementation of complementary food during 6-23 months with continued breastfeeding 5.

 Complementary feeding counselling.

 The three counselling interventions (Behaviour change communication, BCC) will be universal in all intervention arms and the two types of supplementation will be provided in different combinations explained elsewhere.

 This design will allow testing for synergy, and help to determine the effect size of selected individual interventions, such as evaluating how much effect prenatal or complementary food supplementation would have on improving the length-for-age z score (LAZ).

 The cohort of pregnant women and their children from that pregnancy will be followed-up over 32 months of the intervention period.

 Sample Size Calculation Power-based sample size estimation procedure was adopted.

 Assumptions used in sample size calculation include: - Mean HAZ for 18-23 month old children in comparison arm is -2.

0 with standard deviation 1 (BDHS 2011) - Expected effect size of 0.

4 shift in mean HAZ score in intervention arms compared to comparison.

 - 80% power, 5% alpha, ratio between 4 intervention and 1 comparison arms is 1:1:1:1:1.

 - Intra-cluster correlation coefficient is 0.

06 (BDHS 2011).

 - Non response and lost-to-follow up 30% Using SATA clustersampsi command, sample size per study arm is calculated as 175 children of 18-24 months age.

 7 children in each of 25 clusters (~2000 population each) would be followed up from ~125 days of gestational age to postnatal 24 months.

 The sample size in comparison arm will be doubled for analysing some secondary indicators.

 Study setting The study will be conducted in the Habiganj district, Sylhet division for the reported highest stunting prevalence in Bangladesh.

 The investigators will select 12 Unions (population ~300,000) randomly from two adjacent sub-districts.

 Each Union would be divided into clusters, each cluster comprising of ~450 households or ~2000 population.

 In selected 125 study clusters, 10 and 20 pregnant women in each intervention and comparison cluster would be enrolled, respectively, and enrolment would be closed accordingly.

 Considering estimated live births per year at 21/1000 population, expected number of 24 months old children from each cluster by study completion would be 7, after adjusting for 4.

5% mortality in postnatal two years and 30% drop-out.

 Thus, 25 clusters per study arm would yield 175 and 350 children per intervention comparison arms, respectively, reaching their second birthday, the required number of samples for the trial.

 Treatment assignment The investigators will randomly select 5 clusters or multiples of 5 clusters per union, 125 clusters in total, by a computer assisted programme.

 In each union, the selected clusters will be evenly allocated to the 5 study arms, specified by a random allocation sequence generated by a computer assisted programme.

 Recruitment of participants Pregnant women in the study area would be listed through a door-to-door surveillance conducted fortnightly.

 From them, those within 125 gestational age would be voluntarily enrolled into the study upon confirmation by pregnancy strip tests.

 Post-enrolment study procedure: After enrolment, two teams would be active: 1) The intervention team in intervention arms (arms 1, 2, 3 and 4); and 2) The assessment team in all 5 arms.

 Both teams would be supervised and monitored by two layers of field supervisors.

 1.

 The intervention team Interventions will be implemented by a trained team of Community Health Workers (CHWs), supervised by Field Supervisors (FSs), all locally recruited.

 After staff recruitment, the CHWs and the FSs would be trained by master trainers of nutrition-specific BCC, with rigorous field practices, before formally commencing to deliver intervention.

 2.

 The assessment team An independent team of data collectors (DCs) will be recruited locally and trained by the central team for data collection.

 The enrolment DC team will collect baseline and follow up data.

 Project Management Information System (MIS) A comprehensive automated project MIS will be developed through web linked tablet-PC-based pregnancy enrolment, data collection and intervention delivery format.

 The android-based customised platform will direct the CHWs and enrolment DCs of their intervention and data collection visit schedules, respectively, and will also contain the BCC modules and the questionnaires as required.

 Data collection All data collection tools are adopted from standard validated structured questionnaire, especially from BDHS.

 Key indicators to be reported and tools to be used are showed in table 2.

 1.

 Baseline characteristics: Demographic, Socio-economic, reproductive information and household food security of participant women will be collected with a structured questionnaire during enrolment into the trial.

 2.

 Nutritional intake of pregnant and lactating women: Nutritional intake (energy and protein) of mothers will be assessed by an open 24-hour recall form at enrolment, 6th and 9th months of pregnancy and 3rd, 12th, 18th months of lactation period.

 3.

 Nutritional status of pregnant and lactating women: Anthropometric measurements will be collected to assess initial nutritional status and subsequent weight gain during pregnancy.

 Weight, height and MUAC of pregnant women will be measured at enrolment, with weight and MUAC measured again at 6th and 8th month of pregnancy, and postnatal follow-up visits.

 Weight will be measured using an electronic weighing scale of Tanita with a precision of 10 gm.

 Surgical and medical product (NSW, Australia) height measuring scale will be used for measuring height of pregnant women.

 MUAC would be measured with a standardised MUAC tape for adults.

 4.

 Nutritional intake of children: Nutritional intake and feeding practice of infants will be measured on the 7th day of birth, then 3, 6, 12, 18 and 24 months of age.

 WHO-recommended IYCF indicators would be addressed, i.

e.

 early initiation of breastfeeding, pre-lacteal feeding, exclusive breastfeeding, breastfeeding and complementary feeding practices at 6, 12, 18 and 24 months of age of the children.

 24-hour and 7-day dietary recall would assess the information.

 5.

 Anthropometric measurements of children: Birth weight will be collected within 24 hours of live birth, measured using an electronic weighing scale preferably SECA (Hamburg, Germany) with a precision on 10g.

 Length of newborns will be measured using locally made collapsible length boards with 1mm precision.

 These measurements will continue on 3, 6, 12, 18 and 24 months of birth.

 6.

 Supplement compliance: The compliance form is a structured questionnaire on respondents' attitude and practice towards the ante-natal and complementary food supplements provided to them.

 All measurement equipment would be calibrated before each use.

.

 Evaluate Bundling of Nutrition Interventions@highlight

Background: 1.

 Burden: The prevalence of stunting among the under-five children in Bangladesh was >55% in 1997, which reduced to 41.

9% in 2011.

 This reduction took 14 years to achieve with existing interventions, and till today Bangladesh remains among the countries with the highest stunting prevalence.

 2.

 Knowledge gap: In the Lancet series on Maternal and Child Nutrition, Bhutta et al (2013) modelled the effect of 10 direct interventions on lives saved and economic costs in 34 countries which contains 90% of the children with stunted growth.

 Their findings suggested that at 90% coverage, these interventions could cut down under-5 year mortality by 15% and avert one-fifth of stunting.

 The total additional annual cost was estimated at $9.

6 billion.

 There is a dearth of primary research, however, to determine a feasible, effective bundle of interventions for developing countries.

 3.

 Relevance: This study will review and test different sets of nutrition-specific intervention bundles in a cohort of pregnant women and the subsequent impact on the length-for-age Z score (LAZ) of their offspring from that pregnancy.

 Hypothesis: Five selected nutrition-specific interventions implemented during early pregnancy and during first two years of child's life in different bundles will cause a shift of 0.

4 in mean HAZ score among children at 24 months of age compared to those in comparison arm.

 Methods: The investigators propose a community-based randomized trial (CRCT) to evaluate the effectiveness of different combinations of the five selected nutrition-specific interventions and identify the best combination for improving childhood HAZ.

 Selected interventions include prenatal nutrition supplementation; intensive counselling on prenatal nutrition, exclusive breastfeeding and timely complementary feeding; and complementary food supplementation during 6-23 months.

 The proposed study area is Habiganj district, Sylhet division.

 125 clusters (each ~2000 population or ~450 households) will be selected from 12 homogenous unions in 2 adjacent sub-districts.

 The clusters will then be randomly assigned to any one of the 5 study arms.

 Data would be collected at baseline and followed up, including on nutritional intake and anthropometric measurements of mothers and offspring.

 Primary outcome measure/variable would be mean HAZ of offspring at 24 months.

 Secondary outcome variables include nutritional intake during pregnancy, maternal weight gain, exclusive breast feeding up-to 6 months, and birth weight.

 Implications: The investigators expect that the results will serve to inform and shape future health policy decisions related to promotion of maternal and child health.

