(fifthQuint)Wilm's Tumor 1 Protein Vaccine to Treat Cancers of the Blood.

 Background: - Efforts to incorporate anti-tumor immunotherapy at stages of minimal residual disease (MRD) burden are limited by profound host immune depletion associated with standard anti-cancer therapies.

 - Allogeneic blood and marrow stem cell transplantation (SCT) can be curative for a number of hematologic malignancies.

 Part of the success of this approach is an allogeneic immunologic reaction that has been demonstrated to play a role in the eradication of residual malignant disease after transplant in certain cancers (the so called graft-versus-leukemia, GVL, or graft-versus-tumor, GVT, effect).

 Nonetheless, relapse remains the primary cause of treatment failure after allogeneic SCT.

 - The Wilm's tumor 1 (WT1) gene product is a tumor-associated antigen that represents a potential target for immunotherapy in a wide array of cancers.

 WT1 is expressed in most cases of acute leukemia and in many cases of chronic myelogenous leukemia and myelodysplastic syndromes.

 Importantly, WT1 has limited expression in normal tissues beyond embryogenesis.

 This trial represents an attempt to incorporate antigen-specific immunotherapy in the setting of allogeneic adoptive cell transfer.

 Objectives: - To determine the safety, toxicity, and feasibility of donor-derived dendritic cell vaccination and donor lymphocyte infusion (DLI) after allogeneic SCT.

 - To determine the frequency and severity of graft-vs.

-host disease (GVHD) in patients treated with peptide-loaded donor-derived dendritic cell vaccination and donor lymphocyte infusion (DLI).

 - To evaluate whether immunologic responses to WT1-specific peptides can be generated by peptide-loaded donor-derived dendritic cell vaccination and DLI after allogeneic SCT.

 - To evaluate whether clinical responses to WT1-specific peptides can be generated by peptide-loaded donor-derived dendritic cell vaccination and DLI after allogeneic SCT.

 - To evaluate whether immunologic and/or clinical responses may be associated with the degree of WT1 expression by malignant cells or pre-existing donor anti-WT1 immunity.

 Eligibility: - HLA-A2 plus patients may be enrolled on this trial if they have relapsed or residual disease following allogeneic SCT for a WT1 expressing hematologic malignancy.

 - Donors from the previous SCT, related or unrelated, must be 5- or 6- antigen genotypic HLA-matched (single HLA-A or B locus mismatch allowed) and HLAA2 plus.

 Design: - This is a pilot study, the primary aim of which is to assess safety and feasibility of this novel vaccine strategy aimed to enhance the GVL effect after allogeneic SCT.

 - Donor-derived dendritic cells prepared from peripheral blood monocytes will be loaded with a combination of three WT1-derived peptides.

 These peptides are each comprised of one WT1-derived oligomeric epitope known to bind to HLA-A2 and an 11-mer protein transduction epitope known to enhance peptide loading and antigen presentation.

 - Patients will receive donor-derived dendritic cell vaccines every 14 days for 6 doses.

 Donor leukocyte infusions (DLI) will also be administered with the vaccine.

 - Study endpoints will include toxicity, feasibility, antigen-specific immunity, and disease response.

 - This is an exploratory pilot trial.

 Up to 12 patients will be treated.

 - Stopping rules will take effect if excessive toxicity (e.

g.

, GVHD) or inability to generate vaccines are observed.

.

 Wilm's Tumor 1 Protein Vaccine to Treat Cancers of the Blood@highlight

Background: - Most patients with acute lymphoblastic leukemia (ALL) and many patients with acute myelogenous leukemia (AML), chronic myelogenous leukemia (CML) and non-Hodgkin's lymphoma (NHL) have a protein called Wilm's Tumor 1 (WT1) in their cancer cells.

 This protein is thought to be able to influence the growth of these cancers.

 - A vaccine made with the WT1 protein may boost the immune system to help fight these cancers in patients whose cancer cells contain the protein.

 Objectives: - To determine the safety, effectiveness and side effects of giving the WT1 vaccine and donor white blood cells to patients with AML, ALL, CML or NHL who have previously received standard treatment and undergone stem cell transplantation.

 - To determine the immune response to the WT1 vaccine and donor white blood cells in these patients and to determine if the response is related to the amount of WT1 protein in the patient's cancer cells.

 Eligibility: - Patients between 1 and 75 years of age with the blood antigen human leukocyte antigen (HLA-A2) and the WT1 cancer protein who have persistent or recurrent blood cancers after stem cell transplantation.

 - The prior stem cell transplant donor must be willing to provide additional cells, which will be used to prepare the cellular vaccines and for donor lymphocyte (white blood cell) infusions.

 Design: - Patients are given the WT1 vaccine every 2 weeks for 6 weeks (weeks 0, 2, 4, 6, 8, 10).

 Each vaccination consists of two injections in the upper arm or thigh.

 - On weeks 0, 4 and 8, patients also receive white blood cells from a donor to enhance the immune response.

 The cells are also given as a 15- to 30-minute infusion through a vein about 1 hour after the vaccine injection.

 Donor infusions are given only to patients with mild or no graft-vs-host disease resulting from their prior stem cell transplantation.

 - Periodic physical examinations, blood and urine tests, scans to evaluate disease and other tests as needed are done for 12 months after enrollment in the study.

