(fifthQuint)Exploring the Health Benefits Associated With Daily Pulse Consumption in Individuals With Peripheral Arterial Disease.

 Objectives: - Correlate serum adiponectin levels with daily intake of pulses in individuals with peripheral arterial disease - Monitor changes in arterial stiffness and endothelial dysfunction in individuals with early stage cardiovascular disease - Determine the tolerability of daily consumption of pulses in the targeted population - Identify changes in the expression profile of white blood cells.

 Study Duration: 12 months Study Design: - This is a single site, open registration, dietary proof of concept, food substance study designed to explore the health benefits associated with daily pulse consumption in individuals with arterial disease - Each subject will undergo a 7-day adaptation period consisting of a consumption of 1/4 cup of pulses per serving daily, followed by a minimum of 1/2 cup of pulses per serving daily - Total duration of subject participation is 8 weeks; - Subjects will be asked to attend 3 in-person clinic visits over the duration of their participation in the study for screening, registration/baseline and end of study assessments - Telephone follow-up to subjects will occur at weeks 1,2,4, and 6 - Both clinical assessment and subject-based data will be collected at various points of the study schedule - Subjects will be asked to complete a food frequency questionnaire at the outset, maintain a 3-day food record at two separate occasions, and undergo a brief semi-structured interview during the telephone follow-up assessments of the study Assessments: 1.

 Screening Visit: Informed consent; inclusion/exclusion criteria assessment; medical history; physical exam; food frequency questionnaire; 3-day food record 2.

 Registration/Baseline: Registration; assess for changes to medical history (including medication profile) and physical condition; urine sample; fasting blood sample; assessment of arterial stiffness and ankle-brachial index; begin adaptation period (7 days)with food items containing 1/4 c of pulses per serving 3.

 Visits 1,2,4 & 6: Telephone follow-up to assess adverse events and tolerability with semi-structured subject interview; distribution (weekly) of food items containing a minimum of 1/2 cup pulses per serving; 3-day food record repeated at week 6 4.

 Visit 8 (final): Assess for adverse events and changes to medical history and physical exam; urine sample; fasting blood sample collection; assessment of arterial stiffness and and ankle-brachial index Outcomes: - Descriptive analysis of clinical data: Demographics, medical history, physical findings, concomitant medications and adverse events - Identification of changes in endothelial function (determined by measuring pulse wave velocity (PWV), ankle-brachial index, soluble adhesion molecule levels and coagulation status) in response to dietary modification - Correlation of serum adiponectin levels, including adiponectin multimers and truncated form (globular adiponectin) with endothelial function - Correlation of changes in endothelial cell function with serum isoflavone levels - Qualitative analysis of data collected from semi-structured subject interviews to assess parameters associated with tolerability of diet and to identify favoured recipes - Profile cohort using 55,000 gene microarray to identify potential biomarkers and changes in gene expression (phenotype mapping) induced by diet - Use microarrays to examine gene methylation and single nucleotide polymorphisms (SNP) in DNA samples to determine if changes in expression profile are due to epigenetic modification (global) or allelic (individual) variation in the study cohort in response to a pulse-enriched diet - Serum and urinary eicosanoids will be analyzed by a multi-step procedure utilizing liquid chromatography, derivitization steps, thin-layer chromatography and gas chromatography-mass spectrometry - Serum will also be analyzed for fatty acid composition using thin-layer chromatography and gas chromatography.

 Exploring the Health Benefits Associated With Daily Pulse Consumption in Individuals With Peripheral Arterial Disease@highlight

This is a single site, open registration, dietary proof of concept, food substance study designed to explore the health benefits associated with daily pulse consumption in individuals with peripheral arterial disease.

 The investigators hypothesis that a diet containing at least one serving of pulse crops (dried beans, peas, lentil, chickpeas) per day provides flavonoid compounds that improve cardiovascular health by increasing the levels of serum adiponectin is based on evidence from the literature that indicates flavonoids present in these foods are capable of improving arterial stiffness and reducing hypercholesterolemia.

