(secondQuint)Prospective Observational Study of 1st and 2nd Line Vectibix Use in RAS-wt mCRC Pts to Evaluate Pattern of Use and ORR.

 This is a single-arm, multi-center, prospective, observational, descriptive, noninterventional study in patients with mCRC in Greece who receive Vectibix(R)in 1st or 2nd line according to approved indication.

 The aim of the study is to obtain a clear understanding of the current practices concerning real-life treatment of mCRC patients with Vectibix(R) in first-line in combination with chemotherapy or second-line in combination with chemotherapy in Greece.

 This setting will also provide the opportunity to observe in a non-selected patient population with RAS WT mCRC the real-life habits of mCRC treatment, and in particular the duration and the outcomes of Vectibix(R) treatment.

 The data generated by this study may be used for reimbursement purposes, as it becomes an increasingly common need in Greece to provide locally generated data for use of drugs in the real-life setting to regulatory agencies and/or payors.

 Furthermore, this study could address the existing data gap in the treatment of anti-EGFR therapy beyond progression in the real-life setting.

 Primary Objective(s): To describe the pattern of use of Vectibix(R) in combination with chemotherapy in 1st line or in 2nd line mCRC treatments as per approved Vectibix(R) indication.

 Secondary Objective(s): To investigate the rate of objective response (ORR, defined as either a Complete Response or a Partial Response) and the rate of stable disease as best response in 1st line or in 2nd line chemotherapy regimens of mCRC including Vectibix(R).

.

 Prospective Observational Study of 1st and 2nd Line Vectibix Use in RAS-wt mCRC Pts to Evaluate Pattern of Use and ORR@highlight

The study will shed additional light on the impact of Vectibix(R) under the current, standard clinical conditions of mCRC treatment in Greece.

 It will provide data on the duration and the outcomes of Vectibix(R) treatment in real-life setting.

