(secondQuint)Full Mouth Disinfection and Antibiotics for Periodontitis in High or Moderate Disease Activity Rheumatoid Arthritis.

 Rheumatoid arthritis (RA) is a currently incurable disease of unknown origin characterized by joint inflammation and the breakdown of immune tolerance to a variety of antigens, including citrullinated peptides generated by peptidyl-arginine-deiminases (PAD's).

 Porphyromonas gingivalis (P.

 g.

) derived PAD enzyme (PPAD) citrullinates preferentially C-terminal arginine residues, which may be generated by P.

g.

 derived gingipain protein (Rgpb) cleavage, but several of the originated peptide sequences from enolase, collagen, vimentin or fibrinogen may be cross-reactant to citrullinated RA candidate autoantigens.

 Antigen-specific autoantibodies in RA may be present years before clinical disease onset of arthritis, and their precise role in the initiation or perpetuation of the characteristic articular immune processes is currently unclear.

 The situation for autoantibodies was in similar poorly understood for decades until an unanticipated reduction of RA disease activity could be achieved by therapeutic B cell depletion using anti-CD20 therapy.

 While anti-CD20 therapy may affect the regeneration of autoantibody producing cells, the investigators aim in the present study to reduce potential oral trigger mechanisms or antigens for cross-reactant autoreactive B cell or plasma cell populations.

 The study follows the concept of improved RA disease activity by minimization of any inflammatory stimuli associated with periodontitis, e.

g.

 by any underlying microbial colonization, the amount of microbial foreign antigens, achieved by standard oral hygienic means, full mouth disinfection plus adjuvant short term antibiotic therapy in established periodontitis.

.

 Full Mouth Disinfection and Antibiotics for Periodontitis in High or Moderate Disease Activity Rheumatoid Arthritis@highlight

The purpose of this study is to determine whether full mouth disinfection in combination with one week antibiotic amoxicillin plus metronidazole antibiotic therapy is improving periodontitis and disease activity of rheumatoid arthritis.

