(fifthQuint)Is Pressurized Irrigation an Effective Alternative to Swabbing for Wound Cleansing?.

 - Registration/ randomization procedure: Once patients are identified as potential participants at their outpatient clinic visit, the research nurse will initiate the enrolment process by explaining the objectives of the proposed study to the patient.

 Informed consents are obtained for eligible subjects.

 A thorough assessment and measurement of the wound will be done by another research nurse.

 Participants are asked to complete the first questionnaire.

 Participants are then randomized to either intervention or control group.

 Randomization will be done by a randomization list generated by a statistician using a simple randomization method and programmed in a designated computer.

 - Schema of intervention delivery and data collection: The wounds of participants in control group and study group will be cleansed following to the allocated method until the wounds are completely healed or for six weeks if the wounds have not yet healed.

 Wound-care specialists and microbiologists will be consulted throughout the study for technical advice, particularly on information not readily available in the literature.

 Decisions relating to the time period needed to detect wound infection and healing, as well as the investigations required to detect wound infection, are made in consultation with this group.

 The first research nurse will undertake wound cleansing for experimental group.

 Wound cleansing in control group is done as usual by the staff nurses in the four designated clinics, who will attend an education programme which explains the details of the study, the procedures to be followed, and the patient documentation.

 The first research nurse and the clinic nurse who undertakes dressing change are responsible for the ongoing assessment of the wound during cleansing and recording the information on the volume of solution and amount of cleansing materials used, frequency of dressing changes and the type of dressing applied at each visit.

 Participants are instructed to report any signs of infection to the first research nurse and the clinic nurse or physician.

 The second research nurse who is blinded to the wound cleansing method will undertake data collection and wound assessment for all subjects at enrollment and upon healing of the wound or at the end of six-week period if the wounds have not yet healed.

 Wounds that have not healed at the end of the six-week period will be reassessed and data relating to the wound characteristics are recorded.

 - Criteria for study discontinuation: Participants may be discontinued from the study and assessments at any time.

 Criteria of premature withdrawal from trial include 1) Voluntary discontinuation by the participants without prejudice to further care; 2) Participants lost to follow up.

 For withdrawal from trial treatment: 1) Any surgical intervention to the wounds as required; 2) Safety reasons as judged by investigator; 3) Severe non compliance to the protocol as judged by the investigator, these patients will be followed to trial completion.

 Investigators should document the reasons for withdrawal in patient notes.

 The decision of withdrawal would not affect further wound care management.

 - Statistical analysis: The time to wound-healing is analyzed using Cox regression analysis.

 An intent-to-treat principle will be applied in the analysis.

 Patients' time-to-wound-healing are censored at the time of consent withdrawal, dead or lost to follow up.

 The difference between the two arms is assessed using Cox model.

 Repeated measures ANOVA is performed to compare the effects of intervention (vs.

 control) and time (6 week post randomization) on mean wound size change.

 The differences in wound symptoms and patient's satisfaction and comfort to cleansing method are analyzed using Wilcoxon Rank Sum Test.

 Chi-square test is used to test difference in the infection incidence and the proportion of wounds completely healed during follow up between the two groups.

 Prognostic factors are assessed and adjusted using a Cox proportional hazard regression model.

 These variables are: age, body mass index (calculated from participants' height and weight), wound characteristics (location, types, wound size), wound status (assessed by Wound Status Assessment score), smoking, presence of underlying disease, concomitant medication and mental status (assessed by AMT).

 - Recruitment schedule: For the purpose of easy operation and avoiding too many patients accumulated at the same time, recruitment will be done separately in 10 cycles.

 The first research nurse need to perform wound dressing in experimental group for 2 patients per hour, thus 12-13 patients a day.

 It will be stopped as soon as 26 patients are recruited in the first week of each cycle so as to facilitate spreading the attending time of patients in the coming 6-week wound cleansing visits, therefore they do not need to wait long.

 That means it takes 2 months to accomplish recruitment plus 6 weeks wound cleansing and data collection for 24-26 subjects, therefore 20 months is required for 244 subjects.

 It is envisaged that the study will take 24 months.

.

 Is Pressurized Irrigation an Effective Alternative to Swabbing for Wound Cleansing?@highlight

The study is to examine the effectiveness of cleansing wound with pressurized irrigation method compared with conventional practice of swabbing on the wound healing and infection of acute and chronic wound, and to evaluate the patient's physical symptoms related to wound, patient's satisfaction to cleansing method, and cost of materials used between the two groups.

 Patients with acute or chronic non-sutured wounds as well as being eligible to exclusion criteria will be recruited and randomly assigned to be cleansed using either: pressurized irrigation method (experimental group) or swabbing method (control group).

 244 patients will be recruited in the study.

 This will take place in four community health centres run by the Hospital Authority in Hong Kong.

 The wounds of participants will be cleansed using the assigned method for a six week period.

 The clinic staff nurse is responsible for the ongoing assessment of the wound.

 Wound assessment will be undertaken at enrolment and upon healing of the wound or at the end of six-week period if the wounds have not healed.

 Demographic data and information related to the wound -wound size +/- wound volume, wound culture swab, and symptoms -wound discomfort, pain and odour will be collected at enrolment.

 Information related to the wound and subjective measures of patient satisfaction -feeling of cleanliness, liking, and of staff satisfaction -feeling user-friendliness, accessibility, cleanliness, liking to the cleansing method using VAS will be assessed at completion of treatment.

 A list of cost measurements for the wound cleansing would also be captured.

