(fifthQuint)Using Networks, Informatics, Technology, and Education in Care for People With Diabetes.

 The problem: The quality of diabetes care is highly variable, with some patients receiving sub-optimal care.

 Best practice is ideally described by research findings.

 Most providers are not aware of research findings.

 Traditional continuing medical education (CME) and dissemination of practice guidelines have failed to reduce variation around best practice.

 A proposed solution: We hypothesize that practitioners that receive evidence-based information addressing a specific deficiency in their practice, in a timely fashion and at the point-of-care, are more likely to improve the quality of their diabetes care.

 To test this hypothesis we suggest the following randomized controlled trial.

 Randomized trial Participants: Primary care teams Intervention: (UNITED PLANNED CARE MODEL)In the setting of the Planned Care Model, for providers and their teams assigned to this intervention, a Diabetes Electronic Management System will produce individualized performance reports on all health care teams.

 Specific performance gaps will be identified and will trigger two actions: 1) Specific messages will be forwarded to the team addressing a performance gap.

 2) A diabetologist will provide counsel and support specific to these deficiencies.

 (e.

g.

 based on performance reports generated by DEMS, an individual provider who has a patient with a performance gap of an LDL cholesterol> 150 not on medications, would get specific evidence based message about goal LDL cholesterol in patients with diabetes, & support/suggestions from the specialist) Control (USUAL PLANNED CARE) In the setting of the Planned Care Model, providers and their team wills receive periodic information about cardiovascular risk reduction in diabetes but not specific to a patient?s performance gap.

 These teams will have access to the specialists using usual referral channels.

 None of these sources will be responding to these practitioners? performance gaps.

 There will be no proactive support or suggestions from the specialist.

 Outcomes: 1) Processes (.

e.

g.

, frequency of lipid profile measurement); 2) Patient metabolic outcomes (.

e.

g.

, % of patients in the practice with LDL concentrations < 100 mg/dL); 3) Patient-centered outcomes (e.

g.

, % of patients who suffered an atherosclerotic event); 4) CQI process and cost-effectiveness.

 Significance: A.

 Implement a Planned Care model in at least 3 primary care sites in Rochester-Kasson B.

 Pilot and Implement a structured specialty communication links and point of care evidence based messages in support of CME by telecommunication links to include DEMS.

 C.

 Measure patient satisfaction with care delivery D.

 Measure provider and health care team satisfaction with care delivery E.

 Measure metabolic outcomes of patients participating in the project F.

 Measure demographics and other co-morbidities for patients participating in the project G.

 Audit for performance metrics, patients outcomes yearly after intervention and complete statistical assessment in keeping with primary hypotheses of the project H.

 Provision of anonymized patient data in support of the assessment of the outcomes of the study.

 Using Networks, Informatics, Technology, and Education in Care for People With Diabetes@highlight

The costs of diabetes care (in health care dollars & human suffering) in the United States are second only to mental illness.

 Randomized control trials & observational studies have shown that glycemic control is predictive of the onset & severity of complications from diabetes and costs of care.

 In addition, a significant percentage of costs associated with diabetes can be reduced or delayed by appropriate diagnosis, preventive strategies, & management.

 The Planned Care Model (advocated by the Institute for Healthcare Improvement) has shown success in demonstrating improved practice performance and patient outcomes during a limited pilot in our clinical practice.

 We are proposing to generalize the Planned Care Model, to assess the value of planned care for all people with diabetes.

 The Planned Care Model will be implemented at each practice site and will consist of a structured communication schema between the patient and the primary health care team, to improve care for people with diabetes.

 Traditional care will be defined as the traditional system of care for patients prior to their participation in the Planned Care Model.

 It is hypothesized that this Planned Care Model will improve compliance with appropriate care guidelines and improve short and long term health outcomes (metabolic, satisfaction, morbidity, mortality and healthcare utilization).

 In conjunction with this study, providers at each of the practice sites will be randomly assigned to a structured communication with specialty care, referred to as UNITED Planned Care (Use of Networks, Informatics, Telemedicine, and Education in Disease Management).

 This communication schema will only be possible once the assigned provider?s patient is participating in the Planned Care Model.

 The UNITED Planned Care model will include point-of-care evidence based messages and specialty advice determined by performance gaps and outcomes for the patient.

 UNITED Planned Care is hypothesized to have the greatest impact on short & long term health outcomes.

