(fifthQuint)A Randomized Multicenter Clinical Study On the High Vacuum Body Cavity Drainage System Following Open Heart Surgery.

 High vacuum chest drainage was once considered inadvisable because of a possible suction injury to soft tissues, such as the lungs or mediastinum.

 Wakabayashi showed that excessive suction force generated by a high vacuum pressure was related to the surface area of the suction applied to the tissues and not the vacuum pressure itself1&2.

 He postulated that suction injury to the lung would not occur if the suction force of a chest tube is below the capillary blood pressure of 30 - 35 torr2.

 Based on this theory, Wakabayashi developed a double-lumen chest drainage tube3 (Trade name NO-NUMO cent ) and its clinical use was approved by FDA4 in 2002.

 A prototype 7-5Fr double-lumen chest tube was successfully tested in laboratory animals and three patients1&2 and the safety of high vacuum chest drainage was proven in a large number of patients undergoing uncomplicated thoracoscopic surgeries2.

 The unique design of the new drainage tube is the small diameter double lumen tube with hundreds of tiny holes that allows rapid drainage without damaging effects of high suction over a limited surface area.

 High vacuum suction is available on wall units already in place in the OR and ICU beds.

 To adopt this system for clinical use, a high vacuum gauge was needed (most don't go beyond 200 torr) to monitor suction, and a high pressure battery powered vacuum pump for transport was necessary, so that drainage was maintained and blood clotting in the tube avoided during the period of prolonged transport from the OR and the setup in the ICU.

 Several brands of portable vacuum pumps on the market were evaluated before concluding that the Vario cent pump (Medela(R) Inc.

) was superior.

 The maximal vacuum pressure that Vario pump can generate is 630 torr or 84 kPa which is equivalent to -857 cmH2O.

 The NO-NUMO cent High Vacuum Body Cavity Drainage System consist of; (1) disposable NO-NUMO cent body cavity drainage tubes, (2) disposable Vario cent fluid management canisters and (3) Vario cent portable vacuum pump.

 We evaluated this new system, using a 13Fr triple-tube set for the mediastinal drainage, a 13Fr single-tube for the left pleural drainage and two 13Fr NO-NUMO tubes for the drainage of the lower extremity subcutaneous wounds following the harvesting of the saphenous veins.

 The tubing was connected to a disposable liner of a Medi-Vac cent (Cardinal Health, Inc.

) suction canisters, which was connected to a Vario pump at 300 torr (= 40 kPa) in patients following open heart surgeries.

.

 A Randomized Multicenter Clinical Study On the High Vacuum Body Cavity Drainage System Following Open Heart Surgery@highlight

The purpose of this study is to compare a new high vacuum pressure chest drainage system (NO-NUMO cent ) with the standard low vacuum pressure drainage system already in use in cardiac surgeries.

 The new system uses smaller diameter drainage tubing to remove blood from the chest after open heart surgery.

 This is less painful to the patient and should help the patient to breathe better after operation.

 Preliminary data suggests that the high vacuum suction is effective and practical, and could actually reduce the amount of chest tube bleeding after surgery without compromising heart function.

 This new high vacuum drainage system was approved by the FDA in 2002.

 Subsequent testing at University of California, Irvine indicated that this unique system may allow the surgeon to predict excessive postoperative bleeding before the patient is transferred out of the operating room, thus adding safety, convenience, and cost effectiveness to their use.

