(fifthQuint)Treating Negative Mental Images and Memories in Social Anxiety.

 Purpose: Building upon extensive prior research by the investigators' expert team, the proposed study will examine the effects of Imaginal Rescripting (IR) as a stand-alone single session intervention for social anxiety disorder (SAD).

 IR is a short but effective cognitive behavioural intervention, which guides patients to change their memories of past socially painful events.

 The purpose of the study is to examine the effects of IR in relation to two comparison conditions and by doing so also provide much-needed experimental evidence in clinical participants to distinguish between competing theories of treatment mechanisms.

 Does IR work by altering the content of the memory or simply by changing its meaning or impact, or both? If modifying memory content is important, does IR improve access to more positive memory details that compete with the original negative ones for activation in subsequent contexts or eradicate elements of the original traumatic memory, perhaps via the disruption of memory reconsolidation? The study will take advantage of the recent development and validation of the Waterloo Images and Memories Interview, which enables researchers to measure the accessibility, subjective appraisals, and narrative content of autobiographical memories (and associated mental images) that participants report experiencing.

 One particularly important outcome generated by the WIMI for the present study involves having trained coders count the number of "episodic" vs.

 "non-episodic" negative and positive autobiographical memory details present in participants' reported narratives over time.

 Research Questions: The effects of IR will be investigated in comparison to Imaginal Exposure (IE) and Supportive Counselling (SC).

 IR targets imagery-based mental representations embedded within patients autobiographical memories.

 In IR, patients progress through 3 distinct phases: (1) Participants "relive" a past negative event in their imagination, (2) are guided to actively change the original memory in their imagination to create more satisfying outcomes, and (3) relive the memory again while incorporating the new information.

 IE involves repeatedly "reliving" the memory from a first-person perspective and actively considering alternative meanings of the memory, but differs from IR in that the original memory itself is never explicitly modified in any way.

 SC provides patients with empathic support and controls for non-specific clinical factors such as therapeutic attention and alliance.

 The research will examine whether IR outperforms these conditions and leads to sustained changes in SAD symptoms, quality of life, and social behaviour.

 The use of IE as a control condition will help to determine whether the therapeutic effects of IR depend on altering the content of the targeted autobiographical memory rather than just its meaning.

 Justification: Only 3 preliminary studies, including one from the investigators' lab, have examined the effects of IR as a stand-alone intervention for SAD.

 These studies found that a single 90-min session of IR produced large improvements in SAD symptoms at post-treatment, but both relied exclusively on self-report measures.

 Moreover, neither study incorporated an active imagery-based control condition against which the specific mechanisms of IR could be experimentally isolated and understood.

 Understanding the mechanisms of IR will help to facilitate the development of effective treatment and relapse prevention strategies for SAD as well as the future dissemination of efficient but potent CBT interventions to patients diagnosed with SAD.

 Objectives: Capitalizing on innovative methodological advancements in the investigators' lab that enable the precise measurement of patients' memory narratives and appraisals over time, the objective is to elucidate how fear memories are represented in the socially anxious mind, how they change during IR, and how impactful and enduring these effects may be.

.

 Treating Negative Mental Images and Memories in Social Anxiety@highlight

The proposed research will study the effects of Imaginal Rescripting (IR) for social anxiety disorder (SAD).

 IR guides patients to change their memories of past socially painful events.

 Initial studies have found that a single session of IR significantly reduces SAD symptoms, however it is not yet clear how or why IR works and whether its effects are long lasting.

 To answer these questions, the investigators will randomly assign adults with SAD to receive either IR, or two other types of brief psychological interventions: Imaginal Exposure and Supportive Counselling.

 Changes in participants' memories, social anxiety symptoms, quality of life, negative beliefs, and social behaviour over the course of a 6-month period will be assessed.

 This study will provide valuable insight into the short- and long-term effects of IR and clarify the mechanisms through which IR works.

 Ultimately, this knowledge will enable the development of more effective treatments and prevention programs for SAD.

