(fifthQuint)Safety, Tolerability and Immunogenicity Induced by the THV01 Treatment in Patients Infected With HIV-1 Clade B and Treated With Highly Active Antiretroviral Therapy (HAART).

.

 This Phase I/II is a randomized, double-blind and placebo controlled study to assess safety, tolerability and immunogenicity of THV01 at three doses in patients infected with the HIV-1 clade B currently on HAART (highly active antiretroviral therapies).

 THV01 involves two intramuscular injections, consisting of the THV01-1 and THV01-2 lentiviral vectors, to be administered intramuscularly eight weeks apart.

 These lentiviral vectors are non-replicative and self-inactivating.

 Both encode the same HIV antigen.

 36 patients will be enrolled.

 They must be HIV-1 (clade B) infected patients, treated by HAART for more than 12 months and with an undetectable viral load.

 Patients will be randomly allocated to one of the groups: - Group 1: patients will receive the THV01-1 and THV01-2 vaccines at 5.

10E+6 TU (transducing unit) or placebo; - Group 2: patients will receive the THV01-1 and THV01-2 vaccines at 5.

10E+7 TU (transducing unit) or placebo; - Group 3: patients will receive the THV01-1 and THV01-2 vaccines at 5.

10E+8 TU (transducing unit) or placebo.

 Hence, twelve patients will be randomized in blocks of 4 in a 3:1 ratio (vaccine:placebo) for each dose.

 Experimental drugs' injection will occur at Week 0 and Week 8.

 HAART will be alleviated for all patients during this "vaccination phase" to enable efficient transduction of the host cells by the lentiviral vectors.

 Initial HAART will be resumed at Week 9.

 Starting on Week 24, HAART will be interrupted.

 Patients will then be monitored on a very stringent rhythm.

 HAART resumption criteria based on the CD4+ T cell counts and the viral load have been implemented to guaranty safety of all enrolled patients.

 Once the last patient has reached his Week 36 visit (or ealier in case of early termination), the statistical analysis will be performed.

 A long-term follow-up of all enrolled patients will be performed for 5 years after the administration of THV01-1.

 During this follow-up, three visits are planned per year, during which blood will be sampled.

 This will provide data on the long-term safety of THV01; on the long-term immune response generated by THV01 and the potential long-term risks/benefits associated with THV01.

.

 Safety, Tolerability and Immunogenicity Induced by the THV01 Treatment in Patients Infected With HIV-1 Clade B and Treated With Highly Active Antiretroviral Therapy (HAART).

@highlight

The objectives of this Phase I/II trial is to evaluate the safety, tolerability and immunogenicity of THV01 compared to placebo in HIV-1 infected patients on HAART (highly active antiretroviral therapies).

 THV01 is composed of two vaccines that derived from the HIV (human immunodeficiency virus): lentiviral vectors.

 They are non-replicative and not infectious.

 They will be injected intramuscularly, eight weeks apart.

 Three doses will be assessed and compared to placebo.

 36 patients will be enrolled.

 Eligible patients must have an undetectable viral load and must be treated by HAART for more than 12 months.

 They will be randomly allocated to one of the study group and will receive the experimental drugs at one of the three doses or a matching placebo.

 Their anti-HIV treatment will be alleviated around each experimental drugs' administration to enable THV01 efficacy.

 HAART will be resumed one week after the second injection.

 15 weeks after resumption, HAART will be interrupted.

 Patients will then be monitored every 2 weeks for CD4+ T cell counts and viral load as well as for thorough assessment of the elicited immune response.

 Stringent anti-HIV treatments resumption criteria have been implemented, based on the CD4+ T cell counts and the viral load.

 Statistical analysis will be performed once the last patient has reached his last visit (week 36 or earlier in case of early termination).

 A long-term follow-up of all enrolled patients will be performed for 5 years post-prime administration.

 This will provide additional data on the safety, on the immune response and the potential long-term risks/benefits associated with THV01.

