(fifthQuint)Phase 1 Novel Live Attenuated Serotype 2 Oral Polio Vaccine Study in IPV Primed Adults.

 Two nOPV2 vaccine candidates have been developed as attenuated serotype 2 polioviruses derived from a modified Sabin 2 infectious cDNA clone.

 nOPV2 Candidate 1 (S2/cre5/S15domV/rec1/hifi3) and nOPV2 Candidate 2 (S2/S15domV/CpG40) were generated by modifying the Sabin-2 RNA sequence to improve phenotypic stability and make the strains less prone to reversion to virulence.

 Due to the withdrawal of Sabin mOPV2 and prohibition of its use from April 2016 onwards, well before the availability of nOPV2 for clinical testing, Phase 4 trials have been conducted with Sabin mOPV2 to provide control data on safety, immunogenicity, against which data for nOPV2 in subsequent Phase I and II studies will be evaluated and compared.

 The Phase 4 trials of Sabin mOPV2 were designed to parallel the expected design of the Phase 1 and 2 nOPV2 studies with respect to overall design, inclusion of similar study cohorts.

 As for these reasons head to head comparison of nOPV2 and mOPV2 is not possible, the overall clinical development plan with the Phase I and II studies was designed taking into consideration the unique situation of OPV2 cessation in April 2016, and the global public health need of a vaccine with lower risk of VAPP and VDPV2 for outbreak response in the post-cessation era.

 This first-in-human (FIH) phase 1 study is designed to evaluate in contained conditions the safety, immunogenicity, shedding and genetic stability of both nOPV2 vaccine candidates in IPV-primed adults before testing in a larger adult and adolescent (> 15 y of age) population, and then in young children and infants.

 The primary objectives of the subsequent Phase 1 and 2 studies will include the general safety, the shedding and genetic stability of the two candidate vaccines, primarily based on comparison with historical data obtained in the Phase 4 studies of Sabin mOPV2.

 The novel vaccine is expected to be eventually e licensed based on 3 criteria: non-inferior safety to the currently licensed mOPV2 of the Sabin strain, non-inferior immunity, less reversion to virulence and less shedding in stool.

 As all comparisons are to be made to the licensed vaccine, a placebo arm was not included in the Phase IV studies or in this study as it does not add value for licensure.

 This Phase 1 study will include 30 IPV-only vaccinated adults to be vaccinated with the study vaccines (15 subjects per candidate vaccine) and followed in contained conditions (28 days) to obtain safety, immunogenicity, shedding and genetic stability data relevant to the decision to advance to future studies with testing in un-contained conditions in adults (OPV- and IPV-primed), adolescent (IPV-primed) and children who have not been exposed to OPV2.

 The study is designed to first obtain safety data from an adult population which is IPV primed, without prior exposure to OPV2, before moving into larger groups of OPV-primed as well as IPV-primed individuals.

 Objectives: The primary objectives of the study are - to assess safety (serious adverse events [SAEs] and severe adverse events [AEs]) of nOPV2 candidate 1 and nOPV2 candidate 2; - to assess viral shedding following nOPV2 candidate 1 and nOPV2 candidate 2 administration in all stool samples.

 Secondary objectives are to assess - safety (any solicited and unsolicited AEs (including SAE and severe AE)), laboratory assessments) of nOPV2 candidate 1 and nOPV2 candidate 2; - immunogenicity (seroprotection rate, seroconversion rate, median antibody titer (post-vaccination)) of nOPV2 candidate 1 and nOPV2 candidate 2; - neurovirulence of shed virus (as measured in animal model(s)) in a subset of stool samples of all subjects.

 Exploratory objectives are - to assess immunogenicity (geometric mean titer [GMT]) of nOPV2 candidate 1 and nOPV2 candidate 2; - to assess the genetic stability, including but not limited to the modified regions of shed virus in a subset of stool samples of all subjects; - to assess viral shedding following nOPV2 candidate 1 or nOPV2 candidate 2 administration in nasopharyngeal swabs of all subjects.

 Overview of Study Design: This will be a single center, blinded study in 30 healthy IPV-only vaccinated adults (age range 18 to 50 years) as follows: - 15 subjects to receive 1 dose of nOPV2 candidate 1 (Group 1); - 15 subjects to receive 1 dose of nOPV2 candidate 2 (Group 2).

 Subjects who will pass screening but for any reason will drop out before vaccination will be defined as screen-failures and will be replaced.

 15 subjects will be evaluated for the 1-dose regimen nOPV2 candidate 1 (Group 1).

 15 subjects will be evaluated for the 1-dose regimen nOPV2 candidate 2 (Group 2).

.

 Phase 1 Novel Live Attenuated Serotype 2 Oral Polio Vaccine Study in IPV Primed Adults@highlight

This first-in-human (FIH) phase 1 study is designed to evaluate in contained conditions the safety, immunogenicity, shedding and genetic stability of both nOPV2 vaccine candidates in IPV-primed adults before testing in a larger adult and adolescent (> 15 y of age) population, and then in young children and infants.

 The primary objectives of the subsequent Phase 1 and 2 studies will include the general safety, the shedding and genetic stability of the two candidate vaccines, primarily based on comparison with historical data obtained in the Phase 4 studies of Sabin mOPV2.

