(fifthQuint)Evaluation of Regional Lung Deposition of Inhaled Saline Using the tPAD Device.

 Purpose: This is an early device characterization study to define the fraction of delivered aerosol generated by a novel nebulizer (tPAD) that deposits in conducting airways.

 Design: Open label, cross-over design, using a standard oral nebulizer (PARI LC Star) as a comparator.

 The order of visits will be randomized.

 Methods: Gamma scintigraphy will be performed following use of each device on separate study visits.

 Primary Outcome: Fraction of inhaled particles that clears over 24 hours.

.

 Evaluation of Regional Lung Deposition of Inhaled Saline Using the tPAD Device@highlight

Purpose: Characterize the depositional attributes of a specialized trans-nasal aerosol delivery device in healthy people using clinical measurements of mucociliary clearance.

 Participants: 10 Healthy non-pregnant volunteers aged 18 to 65 (inclusive) with a body mass index will enrolled.

 Procedures (methods): 7% hypertonic saline (HS) aerosol containing the radio tracer Tc99m-sulfur colloid will be delivered via the tPAD and compared to the well characterized PARI LC Star nebulizer using planar gamma scintigraphy (i.

e.

 particle clearance).

 The fraction of sulfur colloid particles that clear over the ensuing 24 hours with each device will indicate the fraction deposited in conducting airways.

