(thirdQuint)N2 Lung Cancer Project: Neoadjuvant Treatment Followed Surgery Versus Chemoradiation.

 Based on data published by the Intergroup 0139 trial, induction therapy followed by surgery in patients with stage IIIA-N2 NSCLC can increase overall survival compared to exclusive radical chemoradiation treatment.

 The major handicap of all studies addressing the role of surgery in IIIA-N2 NSCLC is the difficulty of recruiting patients.

 Therefore, multicenter studies are necessary to confirm the hypothesis generated by the INT 0139.

.

 N2 Lung Cancer Project: Neoadjuvant Treatment Followed Surgery Versus Chemoradiation@highlight

The objective of this multicenter retrospective study is to compare overall survival in patients with stage IIIA-N2 NSCLC treated with neoadjuvant treatment and surgery versus definitive chemoradiation.

 Secondary objectives are to analyze disease-free survival, median survival, locoregional and distant relapses as well as mortality and toxicity related to treatment.

