(fifthQuint)The Study of Mindfulness-based Cognitive Therapy and Major Depressive Disorder.

 The study is designed as a prospective, assessor-blinded, randomized-control, case-control clinical trial with 70 MDD cases and 35 matched normal controls.

After signed the Informed consents, MDD cases will be assigned to two groups randomly by the table generated by Microsoft Excel 2010 to ensure the random distribution between groups.

 The group of each patient will be allotted by the research coordinator so that evaluators will be blind about it, and patients will be asked to not mention the intervention conditions to evaluators.

 As the research tools, a range of self-rating scales, other-rating scales and behavioral tests and EEG will be mainly applied to assess clinical symptoms and brain state of participants at baseline (week 0), during the intervention (week 2, 4 and 6), at the end of the intervention (week 8), and during the maintenance phase (week 12, 20 and 32).

 After 8-week intervention, all of the participants including MDD cases and normal controls will enter the follow-up.

 Participants of medication group will continue their treatment options without changing the types and doses of medication compared with what they used in the intervention period.

 MBCT group is the same that participants will maintain their medication treatment and practice MBCT exercises at home.

.

 The Study of Mindfulness-based Cognitive Therapy and Major Depressive Disorder@highlight

The primary objective of the study is to evaluate the clinical curative effect of mindfulness-based cognitive therapy(MBCT) for major depressive disorder(MDD).

 Moreover, we will also explore the relationship between P300 potential and erroneous negative potential (ERN) variation and clinical symptoms in MDD and MBCT.

 This study is a randomized-control trial with two study arms: half of patient cases will receive usual medication treatment with the serotonin reuptake inhibitors (SSRIs) and half of patient cases will receive MBCT added to the usual medication treatment.

 This study is also a case-control trial, there will be matched normal controls compared with patient cases through a range of psychological scales and electroencephalogram.

