(fifthQuint)IMAGE-HF Project I-C: Computed Tomographic Coronary Angiography for Heart Failure Patients.

 Hypotheses Primary Hypothesis: Compared to ICA, a diagnostic strategy algorithm using CTA for patients with HF of unknown etiology or where the definition of coronary anatomy is required for diagnosis and management, will result in a reduction in downstream resource utilization and per patient cost.

 Secondary Hypotheses: I) Compared to standard care, a strategy that uses CTA will achieve: a) similar composite clinical events (CCE), quality of life (QoL), major adverse cardiac events (MACE); b) a lower rate of procedure related complications (death, MI, stroke, vascular complications, severe allergic reactions; contrast nephropathy); c) a lower rate of normal ICA.

 II) Using patient-based analysis and vessel-based analysis, CTA has very good agreement with ICA among patients with HF in the CTA arm who proceed to ICA.

 Objectives The primary objective is to understand the role of CTA in patients with HF of unknown etiology.

 We propose a prospective randomized study of 250 patients to examine the potential impact of CTA compared to ICAon resource utilization and health care costs in patients with HF with unknown CAD status.

 Secondary objectives are to: compare CCE, QoL and MACE in the CTA and ICA arms.

 Radiation exposure and safety in both groups will also be assessed.

 Trial design The proposed trial is a multicentre randomized controlled trial of 250 patients.

 In addition, a retrospective review of the current CTA and ICA databases at the University of Ottawa Heart Institute will be conducted to identify an additional cohort of patients (200-400) where the imaging modality decision has already been made.

 These patients are not eligible for randomization, but will be entered into a registry.

 Trial interventions - Randomization All HF patients requiring investigation to determine the etiology of HF (ischemic versus non-ischemic) will be screened for the study.

 Patients will be randomized to the investigation arm CTA or ICA.

 Patients will be stratified according to recruitment site and pre-test probability for obstructive CAD.

 A stratified block (varying sizes) randomization scheme will be used.

 Within each strata, patients will be randomized with varying block sizes into the two study groups.

 A central randomization scheme (envelope), which will ensure concealment, will be used and the local research co-ordinator will perform patient assignments.

 The randomization scheme will be generated by a statistician using a SAS macro.

.

 IMAGE-HF Project I-C: Computed Tomographic Coronary Angiography for Heart Failure Patients@highlight

Background: The prevalence of heart failure (HF) is rapidly rising in industrialized and developing countries.

 Though invasive coronary angiography (ICA) remains the gold standard for anatomical assessment of coronary arteries and luminal stenoses in these patients, alternatives have been sought.

 Computed tomographic coronary angiography (CTA) has emerged as an accurate non-invasive diagnostic tool for CAD and has been demonstrated to have prognostic value.

 Whether or not CTA can be used in patients with HF for diagnosis and to guide patient investigations and management is unknown.

 Acknowledging the aging population in industrialized counties, the increasing burden of healthcare and growing prevalence of HF, there is a need to identify non-invasive diagnostic tests that are cost-effective, readily available, safe and of sufficient accuracy to risk stratify patients and guide investigations and management.

 Methods: The proposed randomized controlled trial (RCT) will evaluate the clinical utility of computed tomographic coronary angiography (CTA) and investigate its potential benefit on resource utilization and health economics in patients with progressive or newly diagnosed heart failure (HF) of unknown etiology (i.

e.

 ischemic versus non- ischemic) or in whom the definition of coronary anatomy is required for diagnosis and management.

 The experimental algorithm will be compared to invasive coronary angiography (ICA) Analysis of composite clinical events and major adverse cardiac events will be performed to determine the impact of these strategies upon patient outcomes.

 Accuracy of CTA in detection of coronary anatomy and obstruction will be assessed in patients undergoing ICA.

 It is expected that CTA will be a more cost-effective strategy for diagnosis; yielding similar outcomes with fewer procedural risks and improved resource utilization.

