(fifthQuint)Clinical Investigation Plan for IQon Spectral CT at Utrecht Medical Center (UMC).

 The study aim is to assess the added diagnostic value and impact on workflow of Philips IQon Spectral Computed Tomography.

 The IQon Spectral CT generates two result types: - Conventional CT images which are equivalent to images produced by the commercially available Brilliance iCT scanner - Spectral CT images which are unique to this product.

 The CT examination would be a standard of care CT performed as per the clinical indication.

 In addition to the aim mentioned above, the investigators would like to develop recommendations for the clinical application of the spectral images in routine use.

 Such recommendations could include optimization of scanning parameters, optimization of reconstruction parameters to utilize the capabilities of the IQon system etc.

 The clinical system includes: - The IQon Spectral CT scanner - Spectral Diagnostic suite (Philips IntelliSpace Portal): includes 5 applications.

 Spectral Enhanced CT Viewer, Spectral Enhanced Advanced Analysis, Spectral Enhanced Comprehensive Cardiac Analysis, Spectral Enhanced Tumor Tracking, spectral magic glass on PACS.

 The testing will be conducted under this project plan.

 This is a single center research study that is expected to be conducted over a one year period.

.

 Clinical Investigation Plan for IQon Spectral CT at Utrecht Medical Center (UMC)@highlight

The CT examination on IQon Spectral CT would be a standard of care CT performed as per the clinical indication.

 The conventional CT images generated by the scanner will be used for clinical purposes as routinely practiced.

 And therefore, the primary study aim is to assess the impact of IQon Spectral CT scanner and applications on the clinical workflow of the site as well as the diagnostic confidence levels of the physicians reading the CT cases.

 In addition to the aim mentioned above, the investigators would like to develop recommendations for the clinical application of the spectral images in routine use.

 Such recommendations could include optimization of scanning protocols, optimization of reconstruction parameters; evaluate the utility of iodine maps and other supported materials.

