(fifthQuint)A Pilot Study of the Effectiveness of Acceptance and Commitment Therapy With a Post-Upper GI Cancer Population.

 Design: This pilot study will take the form of a 2 group randomised controlled trial (intervention vs treatment as usual).

 Measures will be administered at baseline, midpoint, post-intervention and 2 month follow-up.

 Setting: Outpatients' clinic.

 Target population: Adults with oesphagectomy in the previous 3-12 months for oesophageal cancer.

 Exclusion Criteria: In receipt of a psychological intervention; have had a reoccurrence of the disease since their surgery; evidence of cognitive impairment impeding ability to engage with the intervention.

 Health technology: A group-based acceptance and commitment therapy (ACT) intervention.

 There will be 2 intervention groups, both of which will receive an 8 week (1.

5 hours per week) intervention.

 Measurement of costs and outcomes: Participants will be allocated to treatment or control using a randomisation procedure, generated by a statistician outside the research team.

 According to the COMET initiative, there are no recommended core outcomes available for use in oesophageal cancer.

 Work to develop these outcome measures is currently underway and the investigators will contact the authors of this work for the latest updates prior to submitting a full application to ensure that our choice of outcome measures is commensurate with any recommendations they are about to make.

 In the absence of this work being advanced sufficiently to inform this proposal, the following reliable and valid measures will be used: EORTC Quality of Life Questionnaire and Oesophageal Cancer Module, Acceptance and Action Questionnaire II, which provides a measure of psychological inflexibility, and (secondarily) Depression, Anxiety and Stress Scale.

 Sample size: A sample size of 50 (25 per study arm).

[42] This will also allow us to estimate a participation rate of 70% to within a 95% confidence interval of 13%, which will inform the design of the definitive trial.

 Current pathway: Patients can seek support for emotional issues from the specialist nurses in the service.

 Expertise: Multidisciplinary team including cancer specialist nurses, a service user representative, health economist, statistician, psychologists and with expertise in the intervention to be tested, trials methodology, qualitative and quantitative methods, and research among people with oesophageal cancer.

 A Pilot Study of the Effectiveness of Acceptance and Commitment Therapy With a Post-Upper GI Cancer Population@highlight

This pilot research study aims to assess the effectiveness of an Acceptance and Commitment Therapy (ACT; Hayes Strosahl & Wilson, 2011) group based intervention at improving quality of life (QOL) and increasing Psychological Flexibility with survivors of Upper GI cancer following curative treatment.

 Participants will be invited to take part in an eight week intervention with outcomes being measured at baseline, midpoint, post-intervention and two month follow up.

 Outcomes will be compared with a randomised control group who will receive treatment as usual.

 Research has indicated that this population are under considerable psychological distress however within the UK there are currently no specifically tailored psychological interventions on offer to reduce this distress (Dempster, McCorry, Brennan, Donnelly, Murray & Johnston, 2012).

