(firstQuint)The Application of Extremely Low Level Magnetic Fields as Adjunctive Treatment for Type II Diabetes.

 The purpose of this pilot study is to determine whether application of magnetic fields generated by the Resonator TM, as an adjunctive therapy to oral medications results in statistically significant reductions in fasting blood glucose levels, post prandial glucose levels and hemoglobin A1c levels.

 The study will also investigate any induced changes in serum lipids.

.

 The Application of Extremely Low Level Magnetic Fields as Adjunctive Treatment for Type II Diabetes@highlight

The purpose of this study is to see if using a device called the Resonator, that puts out very low level electromagnetic fields, effects blood glucose and A1c levels in people with Type 2 Diabetes.

