(fifthQuint)CNS Sarcoidosis and Acthar Gel.

 Sarcoidosis is a chronic and frequently progressive systemic disease that affects the central nervous system (CNS) in approximately 5% of patients.

 The hallmark of the disease is the development of chronic inflammation with formation of non-caseating granulomas that can involve the brain parenchyma and meninges and appear as contrast-enhancing mass lesions on magnetic resonance imaging.

 The granulomas are primarily comprised of proinflammatory T cells (Th1 cells and Th17 cells) and macrophages which accumulate during the early stages of granuloma formation.

 The inflammation that is generated by these cells is modulated by anti-inflammatory responses mediated by Th2 cells and regulatory T (Treg) cells that later appear and populate the outer regions of the granuloma.

 The presence of Treg cells are of particular interest since these cell are also detected in high numbers in peripheral blood and the immune suppression that results may underlie the occurrence of anergy in patients with the disease.

 The treatment of CNS sarcoidosis involves the use of either corticosteroids or potent immunosuppressive agents, both which can induce severe long-term side effects.

 The adverse effects of steroids may be avoided by treatment with adrenocorticotropic hormone (ACTH), which is available for patient use as H.

P.

 Acthar(R) Gel.

 The efficacy of H.

P.

 Acthar(R) Gel in the treatment of CNS sarcoidosis and the impact on quality of life have not been previously examined.

 In addition, little is known regarding the expression of immune markers in CNS sarcoidosis and the association of such markers with disease activity and response to treatment.

 These issues, therefore, will be explored in the context of this proposal.

.

 CNS Sarcoidosis and Acthar Gel@highlight

The purpose of this study is to see if treatment with H.

P.

 Acthar(R) Gel will result in the improvement and long-term stabilization of clinical and radiographic abnormalities that occur in patients with CNS sarcoidosis.

 In addition, it will also look at whether treatment will be also associated with improvement in measures of quality of life.

 The treatment of CNS sarcoidosis involves the use of either corticosteroids such as prednisone or potent immunosuppressive agents such as methotrexate, both which can induce severe long term side effects.

 The adverse effects of steroids may be avoided by treatment with adrenocorticotropic hormone (ACTH), which is available for patient use as H.

P.

 Acthar(R) Gel.

 The efficacies of H.

P.

 Acthar(R) Gel in the treatment of CNS sarcoidosis and the impact on quality of life have not been previously studied.

 In addition, little is known regarding the expression of immune markers in CNS sarcoidosis and the association of such markers with disease activity and response to treatment.

