(fifthQuint)Chronic Lymphocytic Leukemia Electronic Patient Reported Outcomes Study.

 Chronic lymphocytic leukemia (CLL) is the most common type of adult leukemia in Western countries with 18,960 new cases and 4660 deaths expected in 2016.

 Rapid therapeutic advances in the past five years have changed the landscape of CLL treatment giving patients many more treatment options.

 Fit patients with favorable disease features such as mutated immunoglobulin heavy chain variable region (IgHV genes) have long term benefit from chemoimmunotherapy and new oral agents such as ibrutinib and idelalisib and the BCL-2 inhibitor, venetoclax, provide effective options for relapsed patients.

 With recent FDA approvals, the treatment armamentarium for relapsed/refractory CLL has been transformed in the past several years.

 Clinicians are faced with a plethora of new treatment options and associated guideline updates, making clinical decision-making much more complex.

 It is challenging for the modern-day hematologist to stay current on the comparative evidence of the risks/benefits of various treatment options with so many choices.

 Such novel regimens are changing the survival outcomes and offering new opportunities for the long-term management of CLL.

 While risk-benefit profiles are favorable, diligent supportive care practices are required to promote patient engagement and successful clinical outcomes as such agents are powerful, leading to potential toxicities that must be diligently monitored.

 Since new agents have had limited use in the clinic, real-world evidence on patient symptom experience is not available to guide practice and there is limited data on the effectiveness of evidence-based supportive care recommendations.

 This is a challenge for hematology teams, particularly because CLL patients are amongst the highest rates of emergency department (ED) visits and hospitalizations (along with lung and colon cancers).

 Retrospective data demonstrated that patient demographic and clinical characteristics, as well as chemotherapy choice, were associated with ER visits and hospitalizations in patients with CLL.

 Specifically, significant increases in ER visits and hospitalizations were associated with age, comorbidities, use of supportive care, number of CLL-related adverse events, chemotherapy duration, use of certain therapies, living in the Northeast region of the United States, and treatment following relapse.

 The outcomes of CLL treatment have been found to vary with age, with poorer outcomes in older patients.

 However, the elderly population is highly heterogeneous - ranging from "fit" to "frail".

 A number of recent studies conclude that while chronological age is an important consideration when making treatment decisions for hematologic malignancies, functional status is more predictive of treatment outcomes.

 A review of 83 CLL treatment articles published from 1949 to 2011 reported fit patients had more treatment options than the frail elderly and most studies included patients younger than 65 years.

 It has been noted by a number of researchers that elderly and frail patients with LGL are under-represented in clinical trials and there is need for data to support a tailored treatment plan.

 This study will explore the symptom assessment and management practices of providers caring for individuals receiving new and active therapy for CLL, and will also employ a two-part intervention (with both patients and providers) to evaluate the impact of a novel existing technology, the Carevive Care Planning System (CPS), on supportive care and symptom management.

 The primary objective of this study is to evaluate adherence to evidence-based practices for symptom assessment and management (i.

e.

, "symptom care behaviors") of physicians and nurses (providers) caring for individuals receiving active treatment for CLL.

 The intervention will include personalized supportive care and symptom management plans for patients auto-generated by the Carevive CPS based on each individual's data.

 The care plans were created based on nationally recognized National Comprehensive Cancer Network (NCCN) supportive care guidelines and validated by CLL nurse and physician experts.

.

 Chronic Lymphocytic Leukemia Electronic Patient Reported Outcomes Study@highlight

This multi-site study will enroll approximately 100 CLL patients across 5 cancer institutions.

 The aim of the project is to ensure hematology care teams that are participating in new value-based reimbursement models have an accurate understanding of the evidence and roles of new therapies for CLL and best practice supportive care protocols to proactively assess, monitor, and manage symptoms to promote successful clinical outcomes.

 Hematology teams at seven health systems across the U.

S.

 will be given online clinical training on the latest evidence for treatment planning in CLL along with best supportive care practices for patients on novel CLL treatments, prior to using Carevive's patient engagement software.

 Once training is complete, the Carevive software will be employed in the clinic whereby CLL patients will use the Carevive patient portal to report any symptoms at and in between clinic visits.

 Patients will be given a user name and password to a web-based portal for 24/7 reporting of symptoms experienced.

 Patient-reported and clinical data will be processed by the Carevive rules engine technology to generate evidence-based supportive care plans providing patients with direction regarding self-management strategies, care coordination for relevant cancer center services, and direction on when to go to the emergency department (ED) or call their hematologist based on their institution's protocol.

 For patients who require ongoing and routine monitoring, such supportive care recommendations will be included in supportive care plans generated at the clinic visit.

 On the visits subsequent to the delivery of the care plan, patients will report on the perceived effectiveness of the intervention (or barriers to non-adherence to the intervention).

 Patients and clinicians will assess symptom severity at each visit for a 16-week period and both data sets will be stored and analyzed for research purposes.

