(fifthQuint)Nutritional Therapy Improves Dyslipidemia in HIV Infected Teenagers With Antiretroviral Treatment.

 This is a open randomized clinical trial.

 The participants were adolescents (13 to 19 years old) diagnosed with HIV / AIDS from the Pediatric Infectious Disease Outpatient Clinic - zone 4, from a tertiary care university hospital in the South Region in Brazil, along with their caregivers.

 Present Dyslipidemia, characterized by Total Cholesterol> 200mg / dL associated with:Triglycerides 150mg HDL cholesterol (male 160 mg / dL.

 The clinical profile, immunological, virological, the biochemical parameters will be accessed by the patient's chart and the dietary parameters will be evaluated by means of 24-hour reminder instrument.

 The sample was calculated, using a software, from an alpha error of 5%, reliability power of 80%, to obtain detection difference and standard deviation for each of the group of 40, totaling 36 patients.

 The randomization will be performed through simple randomization in blocks of 2 patients generated by computer program, available at www.

randomization.

com.

 The intervention group received nutritional counseling for 12 weeks and weekly flights to nutritional counseling.

 The control group received standard care consisting of medical care.

 Demographic, clinical, nutritional variables, food surveys and lipid profiles were collected at baseline and at the end of the study for both groups.

.

 Nutritional Therapy Improves Dyslipidemia in HIV Infected Teenagers With Antiretroviral Treatment@highlight

Introduction: Prolonged use of antiretroviral therapy is associated with metabolic and bodily changes such as lipodystrophy, diabetes mellitus, insulin resistance and dyslipidemia latter being associated with a higher chance of cardiovascular events and death.

 Objective: To evaluate the effect of nutritional therapy in dyslipidemic adolescents living with HIV / AIDS in antiretroviral therapy.

 Method: This is a randomized clinical trial with young people 13-19 years in outpatient treatment in a general hospital to present dyslipidemia.

 The intervention group received nutritional counseling for 12 weeks and weekly flights to nutritional counseling.

 The control group received standard care consisting of medical care.

 Demographic, clinical, nutritional variables, food surveys and lipid profiles were collected at baseline and at the end of the study for both groups.

