(thirdQuint)Optimal Planning Target Volume With Stereotactic Radiosurgery.

 Stereotactic radiosurgery (SRS) is used either as definitive treatment alone or as a "boost" in combination with whole-brain radiotherapy (WBRT) for the treatment of brain metastases.

 To establish a target for SRS, the gross tumor volume (GTV) is typically defined as the contrast-enhancing volume on T1-weighted axial MRI images.

 In turn, the volume chosen for treatment (the planning target volume or PTV) is generated by expanding the GTV to account for microscopic extension of tumor beyond the MRI-visualized volume and deviations in patient positioning at the time of treatment.

, However, the optimal PTV in patients undergoing SRS of brain metastases has not been established.

 This pilot randomized study of approximately 49 patients (representing a total of 80 brain lesions) should be sufficient to explore the effect of margin expansion around the GTV for brain metastases.

 The patients enrolled in this study will undergo radiosurgery to a planning treatment volume generated by expanding the GTV of each lesion by either a 1mm or 3mm margin.

 Each lesion, not each patient, will be randomized to receive either the 1mm or 3mm margin with 40 lesions randomized to each arm (a patient with multiple lesions potentially could have a lesion randomized to the 1mm arm and a different lesion randomized to the 3mm arm).

 The primary outcome of 12-month local recurrence and the secondary outcome of the rate of radionecrosis at the SRS treatment site will be lesion-specific outcomes.

 All other secondary outcomes will be patient-specific outcomes.

.

 Optimal Planning Target Volume With Stereotactic Radiosurgery@highlight

The purpose of this study is to estimate the rate of local control at the treated site of the metastasis as a function of 1mm versus 3mm expansion about the gross tumor volume (GTV).

 Each lesion, not each patient will be ranndomized to either the 1mm or 3mm margin with 40 lesions randomized to each arm.

