(fifthQuint)Epidural Spinal Cord Stimulation for Sensory Restoration and Phantom Limb Pain in Upper-Limb Amputees.

 The purpose of this research study is to characterize the types of sensations that can be produced by stimulating the spinal nerves in upper-limb amputees, as well as the effects of that stimulation on phantom limb pain.

 The study involves a medical procedure to temporarily place one to three stimulation electrodes in the space near the spinal cord.

 This medical procedure will be performed under local anesthesia, and will take approximately one to two hours.

 Afterwards, the electrodes will be connected to an external stimulator and a series of experiments will be performed to characterize the types of sensations generated by electrical stimulation of the spinal cord and spinal nerves, as well as to measure the effect of stimulation on phantom limb sensations and phantom limb pain.

 Over the course of less than 30 days, there will be up to 20 of these experimental sessions.

 At the end of the final experimental session, the stimulation electrodes will be removed by gently pulling on them.

 The investigators are inviting participants to consider participating in this research because they have an upper-limb amputation.

 Participants must be between the ages of 18 and 70 and at least one year post-amputation.

 Participants must be willing to travel to the University of Pittsburgh at least twice per week for 30 days.

 Participants cannot have any serious diseases or disorders that affect your ability to participate in this study.

 Women who are pregnant or plan to become pregnant during the study cannot be included.

 The investigators will ask females of child-bearing potential to undergo a urine pregnancy test prior to any procedures (such as MRI, x-ray, fluoroscopy) that may disrupt the healthy development of an unborn child.

 If participants are currently taking any medications that thin their blood, participants will not be eligible for this study.

 Participants will have to meet other criteria to be eligible, which will be reviewed with participants upon their consent.

 The investigators will screen 15 people and expect that up to 10 individuals will complete this study.

.

 Epidural Spinal Cord Stimulation for Sensory Restoration and Phantom Limb Pain in Upper-Limb Amputees@highlight

Individuals with upper-limb amputation usually have intact nerves within the residual limb, and studies have demonstrated that electrical stimulation of those nerves can produce sensations that appear to emanate from the amputated limb.

 In this study, investigators will examine the sensations that are produced by electrical stimulation of these nerves at the location where they exit the spinal cord.

 Stimulation of the spinal cord is commonly used to treat intractable back and limb pain, and the procedure includes a test phase in which electrodes are temporarily placed under the skin near the spinal cord and removed at the end of testing.

 Similarly, in this study, electrodes will be placed near the spinal cord in the upper back and neck, and stimulation will be applied over the course of multiple testing sessions, lasting less than 30 days.

 The electrodes will be removed at the last day of testing.

 During each testing session, electrical stimulation will be applied through the electrodes and a series of tests will be performed to determine the types of sensations produced by stimulation.

 In addition to producing meaningful sensations with electrical stimulation, this study will also test the effect of stimulation on phantom limb sensations and phantom limb pain.

