(secondQuint)Smoking and Body Weight: Analysis of HHANES.

 BACKGROUND: The study was supported by the Small Grants Program established by the National Heart, Lung, and Blood Institute in January 1990 to provide limited support to extend analyses of research data generated by clinical trials, population research, and demonstration and education research studies.

 DESIGN NARRATIVE: The first study used HHANES I data and analysis of variance to determine the possible body composition differences between subgroups of gender and smoking categories.

 Caloric differences in dietary intake were analyzed in a second ANOVA design.

 The second study used data from HHANES I and NHANES II to evaluate the independent and additive or synergistic contribution of smoking rate and fasting glucose on body weight.

.

 Smoking and Body Weight: Analysis of HHANES@highlight

To evaluate the relationships between smoking rate, gender, and body weight in the Hispanic Health and Nutrition Examination I Survey (HHANES) I.

 Also, to evaluate the independent and additive contribution of smoking rate and fasting glucose on body weight in HHANES I and NHANES II.

