(fifthQuint)Trial of Routine Abdominal Wall Closure Versus Reinforcement With TIGR Matrix Onlay.

 Purpose and aims Wound dehiscence (WD), i.

e.

 the rupturing of the wound along sutures, and incisional hernias (IH), i.

e.

 protrusion of the peritoneum with its contents through the incompletely healed abdominal wall, are common and potentially serious complications after abdominal surgery.

 Various medical reports indicate that 10-35% of all laparotomy patients suffer from wound complications, leading to extended hospital stay and severe patient morbidity.

 One approach to mitigate this problem is to use prophylactic surgical mesh at surgery in order to reinforce the suture line.

 Conventional surgical meshes commonly composed of polypropylene have been successfully demonstrated to reduce the incidence of IH by approximately 70%.

 However, a synthetic polypropylene mesh is a permanent implant, which may cause chronic inflammation, seroma, pain and infection.

 Furthermore, if additional surgery is necessary, the implanted polypropylene mesh complicates the procedure.

 A solution to the problem of suture reinforcement is the use of a resorbable (biologically degradable) non-permanent mesh that provides structural support during the healing phase, while gradually being absorbed.

 The TIGR Matrix Surgical Mesh is a completely synthetic resorbable mesh that has the desired properties for use in non-permanent wound reinforcement.

 The patented TIGR mesh is a weave of two different types of fibers, one fast and one slowly resorb able.

 This allows for resorbtion to take place in two distinct stages.

 The fast fiber is a copolymer of glycotide, lactide and trimethylene carbonate, while the slow fiber is a copolymer of lactide and trimethylene carbonate.

 The two-stage resorbtion of the matrix provides for initial high strength wound support, with gradual loss of mechanical strength as the fibers are degraded.

 The fast fibers lose mechanical strength after two weeks, with full resorbtion in approximately four months; the slow fibers lose mechanical strength after 9 months, with full resorbtion following 3 years.

 The TIGR(R) Matrix Surgical Mesh has been evaluated in animal models and has been included in clinical studies for abdominal wall repair and breast surgery.

 A pilot study with the use of the TIGR(R) mesh has successfully demonstrated its safety in prevention of IH.

 In order to extend the clinical use of the TIGR mesh for prophylactic management of WD and IH, we intend to carry out a multicenter randomized clinical study to further evaluate the safety and effectiveness of the TIGR(R) mesh in patients with increased risk of developing post-surgical wound complications.

 The intended study will have the impact of widespread prophylactic use of the TIGR mesh in surgery worldwide, resulting in significantly decreased hospital costs and improved quality of life for patients.

 Table 1.

 Risk factors for incisional hernia - Reoperation - Age over 80 years - Generalised malignant decease (presence of distant metastases at the time of surgery) - COPD (Chronic obstructive pulmonary disease).

 Grade III-IV according to the GOLD classification (FEV1 45, no additional risk factors are required for inclusion) - Hemoglobin cent Incisional hernia Secondary outcomes: - Time to discharge - Postoperative wound dehiscence - Postoperative seroma - Postoperative infection - Incisional hernia (including date confirmed) - Health-related quality of life assessed with Ventral Hernia Pain Questionnaire (VHPQ) 7a Sample size Patients with at least two risk factors are expected to have a risk of at least 10 % to develop an incisional hernia after one year if no prophylactic mesh is used.

7 If a prophylactic mesh reduces this risk to 1.

5% one year after surgery, 90 patients in each group with complete data are required to achieve a chance of 80% to detect a difference at the p<0.

05 level.

 In order to compensate for drop-outs and death before end of follow-up, a total of 100 patients would be required in each group.

 8a Randomisation: sequence generation The random allocation sequence will be generated by computer.

 No blocking will be done.

 9 Randomisation: allocation concealment mechanism The surgeon responsible for the procedure will be informed about the allocation, but not the personnel responsible for the postoperative care of the patient.

 The intervention, i.

e.

 the application of the mesh, will be performed during the procedure and documented separately.

 10 Randomisation: implementation The patients will be performed about the study prior to the procedure by the surgeon responsible for the procedure.

 11a Blinding The patient, the crew responsible for postoperative care and the surgeon who does the follow-up are blinded to the allocation.

 12a Statistical methods The risk of postoperative wound dehiscence within thirty days after surgery will be analysed with chi-two test.

 The risk of incisional hernia will be tested with Kaplan-Meier statistics.

 12b Additional analyses Subgroup analyses will be performed for patients who undergo abdominal surgery through other approaches than midline incision and based on the risk factors listed in Table 1.

 Significance If the study shows a significant reduction in the incidence of WD and IH without a substantial increase in the risk of would complications, it may have a very great impact on how wound closure is practiced.

 Applying an onlay mesh requires little efforts in terms of technical skills and time and the mesh can be produced at very low cost if the market becomes large enough.

 If the risk of developing IH and WD can be reduced with resorbable mesh to the same extent as with a permanent mesh,1 health care costs may be reduced substantially8 and health-related quality of life improved for a large group.

.

 Trial of Routine Abdominal Wall Closure Versus Reinforcement With TIGR Matrix Onlay@highlight

Patients with at least two risk factors for incisional hernia undergoing abdominal surgery are eligible for inclusion.

 After accepting informed consent, patients are randomized into either closing the abdominal wall in a regular way with fascial sutures, or closing with fascial sutures together with placing a TIGR mesh as described.

 All patients are then monitored for signs of infection, wound rupture, incisional hernias, subcutaneous seroma as well as postoperative symptoms.

 All patients will be followed for at least 5 years.

 One year postoperatively, a computer scan is performed to detect asymptomatic incisional hernias.

