(fifthQuint)Phenylbutyrate/Genistein Duotherapy in Delta F508-Heterozygotes (for Cystic Fibrosis).

 This protocol is investigating novel pharmaceutical agents (Phenylbutyrate and Genistein), which are aimed at improving the physiologic function of mutant Cystic Fibrosis Transmembrane conductance Regulator (CFTR).

 CFTR is absent or dysfunctional in cystic fibrosis.

 Nasal epithelial CFTR function will be assessed by the NPD procedure.

 We will test the hypotheses that: 1.

 Phenylbutyrate given orally for 4 days will be safe in adult Delta F508- heterozygous subjects with CF and will result in small improvements in nasal epithelial CFTR function.

 2.

 Topical administration of Genistein to the nasal epithelia of Phenylbutyrate treated Delta F508-heterozygous CF subjects will be safe and lead to augmentation of the improved nasal epithelial CFTR function observed during Phenylbutyrate treatment, but not during placebo treatment.

 Study Flow If eligibility is confirmed at the screening visit, there will be an additional 3 outpatient visits over a 1-2 week period, lasting 2-4 hours each.

 Visit 1, all study related safety evaluations will be completed.

 There will also be a Nasal Potential Difference (NPD) measurement performed.

 To measure nasal potentials, or voltages, a small butterfly needle will be placed in the skin of the forearm and connected by a thin plastic tube to a monitoring device.

 A very small soft plastic catheter or tube will be placed against the inner surface of the nose.

 This catheter will pump a very small amount of saltwater onto the nose and it will connect to the monitoring machine.

 This machine senses very small electrical voltages that are generated by the body.

 It does not and cannot send electricity or shocks to the subject.

 A measurement is made and then the fluid pumped into the nose is changed to one containing a drug called amiloride.

 Amiloride changes the makeup of salt transported in the nose and reduces the electrical voltage.

 Then the fluid is changed to saltwater that does not contain chloride.

 The fluid is then changed to one that has the drug isoproterenol.

 Isoproterenol causes the cells in subjects without CF to move chloride.

 The doses of amiloride and isoproterenol used in this study are much lower than those typically used in patients for other reasons.

 Finally, the fluid will be changed to one containing the experimental drug Genistein.

 Subject will then be randomized and given a 4-day supply of the study drug.

 Visit 2, subject will have safety evaluations and NPD performed in the same manner as previous visit.

 No more study drug after this visit.

 Visit 3, subject will have safety evaluations and NPD performed without the perfusion of Genistein.

.

 Phenylbutyrate/Genistein Duotherapy in Delta F508-Heterozygotes (for Cystic Fibrosis)@highlight

The purpose of this research study is to test a new combination of medicines, Phenylbutyrate and Genistein, to determine if they could be used to treat cystic fibrosis (CF).

 The most common genetic mutation found in patients with CF is called Delta F508.

 Due to this mutation, there is a lack of salt (chloride) movement in your nose, sinuses, lungs, intestines, pancreas and sweat glands.

 This lack of movement causes the clinical manifestations of the disease.

 Although Phenylbutyrate has been extensively used to treat patients with rare metabolic diseases, Phenylbutyrate is an investigational drug for the purpose of this study.

 Genistein is a naturally occurring substance that is found in food products such as soy and tofu, but is also an investigational drug for this study.

 When used together, both drugs may be able to restore normal chloride and salt (water) movements in body organs and glands in people with CF.

 We will be studying salt and water movement in the nose by a technique called nasal transepithelial potential difference (NPD).

