(fifthQuint)Undiagnosed Sleep Apnea and Bypass OperaTion.

 The SABOT Study is an observational study designed to study the impact of sleep apnea on cardiovascular outcomes after non-urgent coronary artery bypass surgery (CABG).

 Patients between the ages of 18 and 90 who are scheduled undergo an non-urgent CABG were eligible for the study Sleep Apnea Screening Questionnaire All recruited patients will be asked to complete the Berlin Questionnaire and Epworth Sleepiness Scale questionnaire.

 The Berlin Questionnaire is a validated screening tool used to identify individuals at high risk of sleep apnea.

 It consists of 10 items in three categories, assessing the presence and intensity of snoring, the severity of daytime somnolence, and the presence of hypertension and obesity.

 A positive score in two or more categories indicates a high risk of sleep apnea.

 The Epworth Sleepiness Scale is a validated questionnaire that identifies the perceived likelihood of falling asleep during eight everyday situations.

 Patients were asked to rate their likelihood of falling asleep during each scenario on a scale of 0-3, for a total score ranging from 0 to 24.

 Excessive daytime sleepiness was defined as an Epworth Sleepiness Scale score > 10.

 Overnight Sleep Study The consenting participants were scheduled to undergo a hospital-based overnight sleep study using a US Food and Drug Administration-approved portable monitoring devices: the Watch-PAT (Itamar Medical, Caesarea, Israel).

 Watch-PAT is a four-channel unattended sleep monitoring device that measures peripheral arterial tone (PAT), pulse oximetry, heart rate, and actigraphy from a built-in actigraph.

 Respiratory events are identified by digital vasoconstriction mediated by -adrenergic receptors that are sensitive to surges in sympathetic activity.

 Respiratory events are considered to be present when one of the following three criteria was met: a reduction in PAT amplitude with an acceleration of the pulse rate or an increase in wrist activity; a reduction in PAT amplitude with 3% oxyhemoglobin desaturation; and 4% oxyhemoglobin desaturation only.

 Although manual scoring and editing of the Watch-PAT signals are possible, we adopted results generated by the device algorithm alone with no intervention by the operator.

 The diagnosis of sleep apnea is confirmed if the AHI was greater than 15 events/h.

 End Points The pre-specified primary end point is a major adverse cardiac and cerebrovascular event (MACCE), defined as a composite of cardiovascular mortality, non-fatal myocardial infarction, non-fatal stroke, and repeat revascularization.

 The secondary end point comprised sudden cardiac death or resuscitated cardiac arrest, all-cause mortality, and hospitalization for heart failure.

.

 Undiagnosed Sleep Apnea and Bypass OperaTion@highlight

Sleep apnea is a prevalent disorder in patients with coronary artery disease.

 Previous studies suggested sleep apnea was associated with coronary plaque burden and future adverse cardiovascular events.

 Sleep apnea is also associated with a high incidence of atrial fibrillation in patients undergoing coronary artery bypass grafting.

 Yet, previous reports used Berlin Questionnaire and Epworth Sleepiness Scale Questionnaire to diagnose sleep apnea.

 However, these screening questionnaires are not as accurate as a proper sleep study.

 In the SABOT study, the investigators used the portable sleep device to diagnose sleep apnea, and evaluate the relationship between sleep apnea and cardiovascular outcomes after coronary artery bypass surgery.

