(fifthQuint)Telephone Follow-up After Treatment for Endometrial Cancer.

 The focus of the study is; 1.

 To generate an evidence-based checklist of signs and symptoms of recurrence of endometrial cancer.

 2.

 To assess the sensitivity and specificity of a telephone follow-up compared to the current clinic-based follow-up in the detection of recurrence of endometrial cancer.

 3.

 To determine patients' satisfaction with the clinic and telephone follow-up.

 4.

 To assess patients' self reported well being (physical activity, smoking, diet, anxiety, depression and quality of life).

 The proposed project will involve generation of an evidence-based checklist of signs and symptoms of recurrence.

 The generated symptom checklist will be used to follow study participants over a period of 12 months.

 During the follow-up period, patients' routine clinic follow-up schedules will not be altered, however; the study participants will be interviewed via telephone 2 to 5 days prior to their scheduled clinic visits dates.

 The checklist of signs and symptoms generated by this study will form the basis for this interview.

 In addition, we will also enquire about the participant's wellbeing and provide resources on physical activity, diet and other life style behaviours and supportive care when needed.

 The data analysis will include determining: i.

 Sensitivity- Proportion of those with the condition who have a positive test.

 ii.

 Specificity-Proportion of those without the condition who have a negative test.

 iii.

 Positive predictive value (PV+) - Proportion of those with a positive test who have the condition.

 iv.

 Negative predictive value (PV-) - Proportion of those with a negative test who do not have the condition.

 Overall accuracy of the symptom checklist compared to the clinic-based follow-up program will also be calculated.

.

 Telephone Follow-up After Treatment for Endometrial Cancer@highlight

The aim of this study is to investigate the feasibility, safety and accuracy of a telephone follow-up for women previously treatment for endometrial cancer.

 To achieve this aim, potentially eligible women attending the Queensland Centre for Gynaecological Cancer (QCGC) outpatient clinic for review following previous treatment for endometrial cancer will be recruited by this study.

 The study aims to recruit all new patients as well as all patients who return to QCGC for their follow-up and who had treatment within the previous 2 years.

 The proposed project will involve generation of an evidence-based checklist of signs and symptoms of disease recurrence from a thorough literature review.

 The generated symptom checklist will be pilot tested and the refined symptom checklist will be used to follow study participants over a period of 12 months.

 During the follow-up period, the basic standard of follow-up after primary treatment for endometrial cancer at the QCGC, Royal Brisbane and Women's Hospital (RBWH)will not be altered; however, the study participants will be interview via telephone 2 to 5 days prior to their scheduled review dates.

 The main outcome measure will be the estimated recurrence rate as derived from the telephone assessment and this will be compared to the clinically detected recurrences as recorded in patients' medical files.

 It is hypothesized, that the telephone follow-up will identify 90% of all recurrences correctly that are later confirmed during the clinical follow-up.

 In addition to the main outcome, we will also assess patients' satisfaction with each of the follow-up programs, whether or not lifestyle behaviours were queried and support offered to improve wellbeing.

