(fifthQuint)fMRI Study of Treatment Recommendations Comparing Recently Diagnosed Multiple Sclerosis (MS) Patients to Controls.

 The development of the immunomodulatory, disease-modifying therapies (DMT) represents a major advance for the treatment of multiple sclerosis (MS).

 To date, immunomodulatory agents approved for the treatment of MS in the United States include two forms of recombinant interferon-beta (IFN-beta-1a [Avonex, Rebif] and IFN-beta-1b [Betaseron]) and synthetic glatiramer acetate [Copaxone].

 These drugs have been shown to favorably alter the natural history of relapsing remitting MS by slowing the progression of disability, reducing relapse rate, and decreasing brain inflammation as measured by MRI.

 There is evidence that the treatment effects of both IFN-beta and glatiramer acetate are related to their properties in regulating various components of the immune system, in particular, the T cell functions (e.

g.

 proliferation and migratory behavior) and cytokine production.

 Though demonstrating clear efficacy on a number of short-term clinical measures, these agents are not cures and most patients with MS continue to experience disease activity in spite of treatment.

 Over the last ten years, clinicians have become comfortable initiating therapy with DMT.

 Now, attention is focused on monitoring the results of a chosen therapy and deciding whether or not a patient is responding optimally to treatment.

 At present, however, clinicians lack criteria for defining optimal response to DMT as well as evidence-based recommendations on how to improve treatment outcomes for individual patients.

 Using a recently published model generated by an advisory board from the United States, as a framework, The Canadian Multiple Sclerosis Working Group (CMSWG) developed practical, evidence-based recommendations on how neurologists can assess the status of patients on DMT and decide when it may be necessary to modify treatment in order to optimize outcomes.

 The CMSWG's recommendations are based on monitoring relapses, neurological progression and MRI activity.

 These recommendations have yet to be implemented in a prospective, randomized, comparative Phase IV clinical trial.

 Traditional measures do not provide critical information about the neural systems that underlie change in behavioral performance.

 The goal of developing a surrogate biological marker of drug efficacy is to be able to measure the extent to which a drug reaches its intended targeted neural system, and to understand and predict the impact of treatment on existing neuropathology.

 Ideally, relevant clinical outcome measures should be well correlated with the biomarker.

 fMRI is a new tool for noninvasive imaging of human brain function.

 Without the use of contrast agents, fMRI detects regional MR signal increases that have been hypothesized to reflect decreases in deoxyhemoglobin due to local increases in blood flow/volume during task activation.

 fMRI has higher spatial and temporal resolution than other existing functional imaging techniques, making it ideal for the study of complex cognitive functions in patient populations.

.

 fMRI Study of Treatment Recommendations Comparing Recently Diagnosed Multiple Sclerosis (MS) Patients to Controls@highlight

Impaired short term memory, attention and concentration lapses, and slower processing of information occur in up to 40-65% of patients with Multiple Sclerosis (MS).

 The quality of life of individuals with MS is impacted to the degree with which they experience these symptoms.

 There are several medications approved by the United States Food and Drug Administration (FDA) to treat MS symptoms and to modify (slow) disease course.

 Traditional approaches to determining the effectiveness of medications used in treating MS rely on reports of the number of relapses an individual experiences, as well as standard clinical tests, such as the Kurtzke Expanded Disability Status Scale (EDSS).

 This research study will look at whether the functional magnetic resonance imaging (fMRI) scan can be used as a tool for measuring changes in the brain associated with treatment in MS patients.

 Unlike a typical MRI which provides structural information about the brain, the fMRI provides information about brain activity during performance of cognitive or motor tasks.

