(fifthQuint)Statin Therapy In Atrial Refractoriness and Reperfusion Injury.

 Evidence that pre- or perioperative statin treatment may reduce the occurrence of post-operative atrial fibrillation and improve clinical outcome in patients undergoing coronary artery bypass graft (CABG) or major vascular surgery has been largely generated by observational studies.

 In a recent meta-analysis of 6 randomized trials (of which only 2 had postoperative atrial fibrillation (AF) as a predefined outcome) evaluating the use of perioperative statin treatment in patients undergoing cardiac surgery (n=651 patients in total - study size between 40 and 200 patients), statin use was found to reduce the patients' relative risk of developing postoperative AF by 43% (RR 0.

57, 95%CI 0.

45,0.

72) and their absolute risk by 14% (95% CI 8%,20%).

 Although these findings would be consistent with a rapid and, possibly, lipid-independent antiarrhythmic effect of statins, they have important limitations (e.

g.

, single-centre, small size, lack of continuous ECG monitoring, mostly "ancillary" findings") and less bearing on current clinical practice, as they mostly included statin-naive patients.

 For these reasons, the recent guidelines for the management of AF have not given a strong recommendation for the use of statins in the prevention of postoperative AF.

 Thus, whether intensive statin treatment in the perioperative period can confer cardio protection by reduction of atrial oxidative stress & improvement in atrial electrical remodelling remains to be demonstrated.

As endothelial function is a strong determinant of clinical outcomes, improvement of vascular redox state & increase in nitric oxide bioavailability of arterial & venous grafts of patients undergoing cardiac surgery may improve post operative outcomes.

However it is still unclear whether higher doses of atorvastatin could confer additional beneficial effects on human vessels.

 Adipose tissue (AT) by releasing vasoactive molecules & adipokines can affect myocardial and vascular biology.

 Recent evidence suggests that statins may favourably alter AT biosynthetic activity and increase the AT release of adiponectin (An adipokine that has been shown to have anti-inflammatory and anti-atherogenic effects) in turn improving the vascular & myocardial redox state.

 However there are only limited data on the effects of statins on human adipose tissue biology and most findings to date are based on cell lines and/or relevant mouse models.

.

 Statin Therapy In Atrial Refractoriness and Reperfusion Injury@highlight

Patients with coronary artery disease are often prescribed drugs called statins because research has shown that, by lowering cholesterol, they reduce the risk of having a heart attack or other complications in the long-term.

 Experimental studies have suggested that statins may also have rapid anti-inflammatory, anti-oxidant and anti arrhythmic actions; however, whether these effects are of any benefit to patients remains to be proven.

 The purpose of STARR trial (Statin Therapy in Atrial Refractoriness and Reperfusion injury) is to evaluate whether a short course of a commonly used statin (atorvastatin, 80 mg once a day) decreases inflammation and stabilises electrical properties of the upper chamber of the heart in the post operative period of patients undergoing cardiac surgery on the heart-lung machine either for valve replacement and/or coronary artery bypass grafting.

 It will also examine whether this treatment can protect the heart from sustaining tissue damage when blood supply is restored after a period of ischaemia during the course of the surgery.

In addition it will also explore the impact of this intervention on biology of the vessels used for bypass surgery and the fat tissue in the vicinity of the heart & blood vessels.

