(firstQuint)Acupuncture in the Regulation of Dai Meridian for the Metabolism of Visceral Adipose Tissue in Abdominal Obese Patients.

 This subject is a prospective, single-blind, parallel-group, randomized controlled clinical trial.

120 patients with abdominal obesity are allocated into two groups with a ratio of 2:1.

Randomized series was generated by computer.

 The allocation was concealed.

 Patients in the intervention group are received acupuncture therapy and healthy education.

 Patients in the control group are only given healthy education.

 The treatment in both intervention group and control group lasts for 8 weeks.

 Comparison of two groups of patients with abdominal fat thickness, fasting serum visfatin concentration, simple anthropometric parameters (including body weight, body mass index, waist circumference, hip circumference, waist-to-hip radio, waist-to-height radio, the percentage of body fat), fasting blood glucose, fasting insulin, glycosylated hemoglobin, fasting blood lipid (total cholesterol, triglyceride, high density lipoprotein, low density lipoprotein), uric acid, blood pressure, insulin resistance level, and obesity related lifestyle survey.

.

 Acupuncture in the Regulation of Dai Meridian for the Metabolism of Visceral Adipose Tissue in Abdominal Obese Patients@highlight

To evaluate the effectiveness of acupuncture therapy combined with healthy education for patients with abdominal obesity.

